//!MAGPIE EFFECT
//!VERSION 4
// MagpieFX shader generated by magpie_gen.py (nene2x project's own code).
// config: 3x3_4,3x3_9,1x1_9,1x1_4
// base upscaler: EDI   channels: YCgCo luma   activation: ReLU
//!TEXTURE
Texture2D INPUT;
//!TEXTURE
//!WIDTH INPUT_WIDTH * 2
//!HEIGHT INPUT_HEIGHT * 2
Texture2D OUTPUT;
//!TEXTURE
//!WIDTH INPUT_WIDTH
//!HEIGHT INPUT_HEIGHT
//!FORMAT R16G16B16A16_FLOAT
Texture2D texYcgCo;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 4
//!HEIGHT INPUT_HEIGHT + 4
//!FORMAT R16G16B16A16_FLOAT
Texture2D texYPad;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 4
//!HEIGHT INPUT_HEIGHT + 4
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 4
//!HEIGHT INPUT_HEIGHT + 4
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 4
//!HEIGHT INPUT_HEIGHT + 4
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 4
//!HEIGHT INPUT_HEIGHT + 4
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_2;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 4
//!HEIGHT INPUT_HEIGHT + 4
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 4
//!HEIGHT INPUT_HEIGHT + 4
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 4
//!HEIGHT INPUT_HEIGHT + 4
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_2;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 4
//!HEIGHT INPUT_HEIGHT + 4
//!FORMAT R16G16B16A16_FLOAT
Texture2D texResid;
//!TEXTURE
//!WIDTH INPUT_WIDTH * 2
//!HEIGHT INPUT_HEIGHT * 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texBase;

//!COMMON

float4 LoadClamp(Texture2D<float4> tex, int2 pos, int2 size) {
    pos = clamp(pos, int2(0, 0), size - 1);
    return tex.Load(int3(pos, 0));
}

float4 BilinearExtrap(Texture2D<float4> tex, int2 size, uint2 p) {
    // Chroma/alpha upsample: infer.py's bil_up interpolates with tap weights
    // that go outside [0,1] at the border (linear extrapolation), so border
    // pixels do NOT replicate the edge texel — clamping them would make the
    // edge look clamped one texel early.
    float2 q = (float2(p) - 0.5) * 0.5;
    int2 f = (int2)floor(q);
    int2 i0 = clamp(f, int2(0, 0), size - 2);
    int2 i1 = i0 + 1;
    float2 t = q - (float2)i0;
    float4 a = tex.Load(int3(i0, 0));
    float4 b = tex.Load(int3(int2(i1.x, i0.y), 0));
    float4 c = tex.Load(int3(int2(i0.x, i1.y), 0));
    float4 d = tex.Load(int3(i1, 0));
    return a*(1.0-t.x)*(1.0-t.y) + b*t.x*(1.0-t.y) + c*(1.0-t.x)*t.y + d*t.x*t.y;
}

float EDI_Bilinear(Texture2D<float4> tex, int2 size, int2 pos, int comp) {
    // pos is in 2x OUTPUT space (up to 2*size-1), so clamp to the 2x bounds —
    // clamping to size-1 here force-clamped reads to the LR texture edge for
    // every pixel past the top-left quadrant (the "clamped copies" bug).
    pos = clamp(pos, int2(0, 0), size * 2 - 1);
    float ux = ((float)pos.y + 0.5) * 0.5;   // row
    float uy = ((float)pos.x + 0.5) * 0.5;   // col
    int ix = (int)floor(ux - 0.5) + 1;       // row index
    int iy = (int)floor(uy - 0.5) + 1;       // col index
    float s_a = LoadClamp(tex, int2(iy - 1, ix - 1), size)[comp];
    float s_b = LoadClamp(tex, int2(iy - 1, ix),     size)[comp];
    float s_c = LoadClamp(tex, int2(iy,     ix - 1), size)[comp];
    float s_d = LoadClamp(tex, int2(iy,     ix),     size)[comp];
    float tx = ux - (float)ix + 0.5;         // row weight
    float ty = uy - (float)iy + 0.5;         // col weight
    return s_a*(1.0-tx)*(1.0-ty) + s_b*tx*(1.0-ty) + s_c*(1.0-tx)*ty + s_d*tx*ty;
}
float EDI_Base(Texture2D<float4> tex, int2 size, int comp, uint2 p) {
    float ux = ((float)p.y + 0.5) * 0.5;   // row
    float uy = ((float)p.x + 0.5) * 0.5;   // col
    int ix = (int)floor(ux - 0.5) + 1;     // row index
    int iy = (int)floor(uy - 0.5) + 1;     // col index
    float s_a = LoadClamp(tex, int2(iy - 1, ix - 1), size)[comp];
    float s_b = LoadClamp(tex, int2(iy - 1, ix),     size)[comp];
    float s_c = LoadClamp(tex, int2(iy,     ix - 1), size)[comp];
    float s_d = LoadClamp(tex, int2(iy,     ix),     size)[comp];
    float tx = ux - (float)ix + 0.5;       // row weight
    float ty = uy - (float)iy + 0.5;       // col weight
    float dd = clamp((abs(s_c - s_b) - abs(s_d - s_a)) * 8.0, -1.0, 1.0) * 0.5 + 0.5;
    float iBS = (tx + ty < 1.0)
        ? s_c*ty + s_b*tx + s_a*(1.0 - (tx + ty))
        : s_c*(1.0-tx) + s_b*(1.0-ty) + s_d*(1.0 - ((1.0-tx) + (1.0-ty)));
    float iFS = (tx > ty)
        ? s_a*(1.0-tx) + s_d*ty + s_b*(1.0 - ((1.0-tx) + ty))
        : s_a*(1.0-ty) + s_d*tx + s_c*(1.0 - (tx + (1.0-ty)));
    float bil = EDI_Bilinear(tex, size, int2(p), comp);
    float ev = (round(dd) > 0.5) ? iFS : iBS;
    float mix = abs(dd - 0.5) * 2.0;
    float resv = (1.0 - mix) * bil + mix * ev;
    float hf = 0.5*(2.0/3.0)*bil - 0.5/6.0*(EDI_Bilinear(tex, size, int2(p) + int2(0, -2), comp)
        + EDI_Bilinear(tex, size, int2(p) + int2(-2, 0), comp)
        + EDI_Bilinear(tex, size, int2(p) + int2(0, 2), comp)
        + EDI_Bilinear(tex, size, int2(p) + int2(2, 0), comp));
    return resv + hf;
}


//!PASS 1
//!IN INPUT
//!OUT texYcgCo
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass1(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texYcgCo.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    float4 c = INPUT.Load(int3(int2(p), 0));
    float y = 0.25*c.r + 0.5*c.g + 0.25*c.b;
    float cg = -0.25*c.r + 0.5*c.g - 0.25*c.b + 0.5;
    float co = 0.5*c.r - 0.5*c.b + 0.5;
    texYcgCo[p] = float4(y, cg, co, c.a);
}

//!PASS 2
//!IN INPUT
//!OUT texYPad
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass2(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texYPad.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    float4 c = LoadClamp(INPUT, int2(p) - int2(2, 2), int2((int)GetInputSize().x, (int)GetInputSize().y));
    float y = 0.25*c.r + 0.5*c.g + 0.25*c.b;
    float cg = -0.25*c.r + 0.5*c.g - 0.25*c.b + 0.5;
    float co = 0.5*c.r - 0.5*c.b + 0.5;
    texYPad[p] = float4(y, cg, co, c.a);
}

//!PASS 3
//!IN texYPad
//!OUT texL0_0
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass3(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL0_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL0_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(0.00273340289, 0.000155610862, 0.00116294052, 0.00449689617);
    min16float4 pv0_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(4.8448e-02, 8.4468e-04, -5.9765e-03, 5.1702e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv1_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(-1.0329e-01, -4.5246e-03, -6.7500e-04, -5.6596e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv2_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(1.4582e-03, 3.4721e-03, 2.2156e-02, 9.1584e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv3_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(-2.1563e-01, 2.2493e-02, -1.7086e-02, -2.4750e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv4_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(8.3491e-01, 3.0785e-01, 2.3364e-01, 4.2330e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv5_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(3.6976e-03, -8.1638e-03, -6.3190e-01, 4.9703e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv6_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(-2.9530e-01, 1.9085e-01, -1.6300e-02, 4.5994e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv7_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(-2.6417e-01, -5.1852e-01, 2.1184e-01, 3.1140e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv8_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(-1.1962e-02, 5.1651e-03, 2.0101e-01, -4.3229e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r0 = max(r0, 0.0);
    texL0_0[p] = r0;
}

//!PASS 4
//!IN texL0_0
//!OUT texL1_0, texL1_1, texL1_2
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass4(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL1_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL1_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.000291020784, -0.00283616874, -0.00769420294, -0.00457364414);
    min16float4 r1 = min16float4(-0.00137503014, 0.00141286408, -0.0033391756, 0.00135347876);
    min16float4 r2 = min16float4(-0.00286309631, 0.0, 0.0, 0.0);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(7.8680e-03, 4.3353e-02, -5.1199e-02, 9.3833e-02, -4.9347e-02, -2.9404e-02, 1.5414e-02, 4.7573e-02, 1.7266e-01, 7.4387e-02, 1.0663e-01, -7.0213e-02, -2.2523e-02, 9.3575e-03, -6.9739e-02, -1.0115e-01));
    r1 += mul(pv0_0, min16float4x4(-1.2219e-01, 1.5735e-02, -8.7094e-02, -4.1873e-02, -2.5418e-01, -5.9344e-01, -1.3938e-01, -6.7361e-02, 3.5980e-02, 1.0168e-01, -2.6285e-02, 2.6093e-01, -1.0713e-02, 2.7172e-03, 3.5199e-02, -9.1855e-02));
    r2 += mul(pv0_0, min16float4x4(-4.2008e-02, 0, 0, 0, -2.5863e-01, 0, 0, 0, -1.5033e-01, 0, 0, 0, -5.1834e-02, 0, 0, 0));
    min16float4 pv1_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(1.4946e-01, 2.8191e-01, 7.2870e-02, 7.6719e-02, 1.0058e+00, 5.8817e-01, -2.7935e-01, -2.9763e-02, 1.5016e-01, -6.4047e-02, 4.5815e-01, 1.2874e-01, 2.1318e-02, 3.3297e-02, -4.2789e-02, -4.5287e-03));
    r1 += mul(pv1_0, min16float4x4(1.1954e-01, -4.9691e-02, -9.7506e-02, 1.8160e-01, -1.7360e+00, 2.0930e-01, -1.1342e-01, 2.4868e-01, -4.2988e-02, 6.7522e-02, -1.2271e-01, 5.2592e-01, -5.9325e-02, 2.6238e-02, -1.9892e-02, -6.1727e-02));
    r2 += mul(pv1_0, min16float4x4(1.3599e-01, 0, 0, 0, -1.8431e-01, 0, 0, 0, 3.0819e-01, 0, 0, 0, -1.6183e-02, 0, 0, 0));
    min16float4 pv2_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(1.7100e-01, 3.1277e-02, 8.8340e-02, 2.2029e-01, 2.0622e-01, 3.0474e-03, 1.1366e-01, -8.6178e-02, -1.3589e-02, -1.6949e-02, -2.2659e-02, 9.1665e-03, 5.4634e-03, -2.1044e-02, -5.2696e-03, -4.5171e-02));
    r1 += mul(pv2_0, min16float4x4(8.6618e-03, 4.2988e-02, 2.4947e-01, 1.4842e-01, 2.0097e-01, -7.2048e-02, -2.0901e-01, 1.5594e-01, -5.5018e-03, -8.5616e-02, 3.9642e-02, -1.6987e-02, 1.7138e-02, 1.9081e-02, -6.8885e-02, -4.8236e-03));
    r2 += mul(pv2_0, min16float4x4(2.1567e-01, 0, 0, 0, -2.5398e-01, 0, 0, 0, -1.2089e-02, 0, 0, 0, 1.0842e-02, 0, 0, 0));
    min16float4 pv3_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(-1.2699e-02, 3.7715e-02, 1.0538e-02, -8.4779e-03, -8.8695e-02, 8.7965e-02, 3.8161e-02, 1.0179e-01, -6.2731e-01, 3.1641e-01, -7.6376e-01, 9.2289e-01, -1.4404e-02, -1.0573e-01, 1.3533e-01, -4.6368e-02));
    r1 += mul(pv3_0, min16float4x4(8.1678e-03, -1.4097e-02, -5.5015e-01, 2.3325e-02, -6.5431e-03, -7.0582e-02, 7.9477e-02, 1.2586e-01, -2.3288e-01, 3.6387e-02, 1.1789e-01, -5.2326e-01, -3.0093e-01, -2.1845e+00, -1.1903e-01, 2.1778e-01));
    r2 += mul(pv3_0, min16float4x4(1.0688e-01, 0, 0, 0, 8.5484e-02, 0, 0, 0, 3.6433e-01, 0, 0, 0, -5.6293e-01, 0, 0, 0));
    min16float4 pv4_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(1.0376e-01, -3.2843e-01, 6.4054e-01, -7.7380e-01, -1.4428e-01, 4.8425e-02, 3.9587e-01, -2.5353e-01, -1.7035e-02, -5.9341e-01, 4.9612e-01, -1.1935e-01, 1.7996e-01, -3.5319e-02, 3.2175e-01, 6.6799e-02));
    r1 += mul(pv4_0, min16float4x4(3.7623e-01, -1.0377e-01, -2.2574e-01, 9.4311e-01, 1.9580e-01, 1.2104e-01, -3.1841e-02, 6.1225e-01, 1.4539e-01, -1.4899e-01, 8.8045e-02, 6.0879e-01, 2.7413e-01, -1.6417e-02, 3.2087e-02, 3.8710e-01));
    r2 += mul(pv4_0, min16float4x4(2.5455e-02, 0, 0, 0, -9.6597e-02, 0, 0, 0, 1.4058e-01, 0, 0, 0, 1.3151e-01, 0, 0, 0));
    min16float4 pv5_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(1.0348e-01, 4.3548e-01, -1.3207e-01, 1.9706e-01, -8.9986e-02, -3.1655e-01, 1.2754e-01, -9.1370e-02, 5.3062e-02, 6.8296e-02, -1.3467e-02, 8.8368e-02, 3.6579e-02, -1.7768e-01, 1.0316e-01, 2.1824e-02));
    r1 += mul(pv5_0, min16float4x4(1.6116e-02, -7.4654e-02, 2.6157e-01, -1.4195e-02, 1.2694e-01, -3.0487e-02, 1.8418e-01, 5.8259e-02, 7.2629e-03, -1.2474e-01, 1.0886e-01, -3.1649e-02, 6.7694e-03, -4.2152e-02, 8.4040e-02, 1.2072e-01));
    r2 += mul(pv5_0, min16float4x4(2.1622e-01, 0, 0, 0, -1.0906e-01, 0, 0, 0, 9.2784e-02, 0, 0, 0, 1.2318e-01, 0, 0, 0));
    min16float4 pv6_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(1.9670e-02, -3.9971e-02, -3.2568e-02, -7.8677e-02, -2.0453e-02, -8.1935e-02, -1.2643e-01, -1.9961e-01, 9.0081e-02, -6.7555e-02, -2.9914e-02, -3.5632e-01, -1.2169e-01, 5.6425e-02, 1.2744e-01, 2.3023e-01));
    r1 += mul(pv6_0, min16float4x4(3.2232e-02, -7.9961e-03, -1.2730e-01, -5.8427e-02, 8.1294e-03, -6.8988e-02, -8.7568e-02, -2.1345e-01, 2.2186e-02, -8.8834e-02, -3.8906e-01, -2.5790e-02, -3.5924e-02, 5.5654e-02, 3.1533e-01, 3.6189e-01));
    r2 += mul(pv6_0, min16float4x4(-8.0946e-02, 0, 0, 0, -1.3030e-01, 0, 0, 0, -8.8036e-02, 0, 0, 0, 4.2151e-01, 0, 0, 0));
    min16float4 pv7_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(-2.0392e-01, 1.5036e-01, 9.1228e-02, 2.1405e-01, -1.3756e-01, 1.9430e-02, -1.8338e-01, -6.2240e-02, -1.9557e-01, 1.8993e-02, 1.6646e-02, -3.4315e-01, -1.6545e-01, 3.6958e-01, -7.2644e-02, -4.6424e-03));
    r1 += mul(pv7_0, min16float4x4(-1.3918e-01, 8.0759e-02, 1.2679e-01, 1.5979e-01, -3.4167e-02, 3.4842e-02, -9.4013e-02, -2.7994e-01, -6.4271e-03, 1.2349e-01, -1.0182e-01, -3.5497e-02, -3.7989e-02, -1.8481e+00, 3.0390e-01, -1.2303e-01));
    r2 += mul(pv7_0, min16float4x4(1.8267e-01, 0, 0, 0, -3.3960e-02, 0, 0, 0, -4.3286e-02, 0, 0, 0, 2.2615e-01, 0, 0, 0));
    min16float4 pv8_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(6.9052e-02, -3.0380e-02, 1.9185e-02, 1.6180e-01, -6.0343e-02, -2.0854e-02, -2.9003e-02, -1.8476e-01, 1.4783e-02, 2.4315e-03, -1.3704e-02, -2.8698e-02, -1.9826e-03, -4.7797e-02, -3.3090e-02, -7.9023e-02));
    r1 += mul(pv8_0, min16float4x4(6.0841e-02, -6.5344e-02, 1.2430e-01, 6.0725e-02, -6.8814e-03, 8.0933e-02, -8.8510e-02, -6.2449e-02, -9.4591e-03, -6.4395e-02, -6.3368e-02, -1.9282e-02, 7.2593e-03, 1.9901e-02, -2.5728e-01, -4.6104e-02));
    r2 += mul(pv8_0, min16float4x4(6.8222e-02, 0, 0, 0, -5.2014e-02, 0, 0, 0, 4.7874e-03, 0, 0, 0, -7.7684e-02, 0, 0, 0));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    r2 = max(r2, 0.0);
    texL1_0[p] = r0;
    texL1_1[p] = r1;
    texL1_2[p] = r2;
}

//!PASS 5
//!IN texL1_0, texL1_1, texL1_2
//!OUT texL2_0, texL2_1, texL2_2
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass5(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL2_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL2_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(0.000117254996, -0.00694351923, 0.000585215457, -0.00432240963);
    min16float4 r1 = min16float4(-0.0052239825, -0.000805653108, -0.0108581586, -0.00358523126);
    min16float4 r2 = min16float4(-0.00368226576, 0.0, 0.0, 0.0);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_2 = (min16float4)LoadClamp(texL1_2, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(1.2311e-01, -5.5839e-01, -9.2661e-02, -3.2858e-01, 4.0836e-01, -2.6454e-01, -6.4988e-03, 1.0811e+00, 6.4822e-03, -6.8313e-02, -3.4279e-01, 1.2520e+00, -1.1500e-01, 6.2628e-01, 1.3725e-01, -3.2311e-01));
    r0 += mul(pv0_1, min16float4x4(3.3565e-01, 2.6196e-01, 7.6379e-02, 5.7809e-02, -4.8076e-02, 7.1851e-01, 5.3505e-01, -9.0222e-01, 2.4091e-01, -4.9263e-02, -1.6013e-01, 4.1046e-01, -1.1544e-01, 4.9369e-01, -2.4791e-01, 1.7606e-01));
    r0 += mul(pv0_2, min16float4x4(-1.0811e-01, -4.9917e-01, 4.1289e-01, -1.1700e+00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv0_0, min16float4x4(-2.3694e-01, 5.7914e-01, 4.4092e-02, 5.8349e-01, 1.7489e-01, -7.1306e-03, -3.4617e-01, -3.7107e-01, 2.3872e-02, -3.7650e-01, -4.0739e-01, -4.9933e-01, -2.3680e-01, 2.3671e-01, -1.5843e-01, -2.6194e-01));
    r1 += mul(pv0_1, min16float4x4(-7.6877e-02, -3.4174e-01, -2.6624e-01, 1.0687e-01, 7.3847e-01, -6.9344e-01, 1.4086e+00, 3.9423e-01, -6.5200e-01, 1.9502e-01, -3.3992e-01, 2.8271e-01, 4.2204e-01, -5.6775e-01, 6.3880e-01, -5.7369e-02));
    r1 += mul(pv0_2, min16float4x4(-7.7805e-01, -5.3035e-01, -2.0520e-01, 6.8328e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv0_0, min16float4x4(7.1909e-01, 0, 0, 0, 3.6621e-01, 0, 0, 0, -4.4810e-01, 0, 0, 0, -5.8652e-01, 0, 0, 0));
    r2 += mul(pv0_1, min16float4x4(7.8661e-01, 0, 0, 0, -1.0238e+00, 0, 0, 0, 5.2029e-01, 0, 0, 0, -2.8018e-01, 0, 0, 0));
    r2 += mul(pv0_2, min16float4x4(2.6734e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    r2 = max(r2, 0.0);
    texL2_0[p] = r0;
    texL2_1[p] = r1;
    texL2_2[p] = r2;
}

//!PASS 6
//!IN texL2_0, texL2_1, texL2_2
//!OUT texResid
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass6(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texResid.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texResid.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-3.45335167e-07, 2.17931556e-05, -1.31488951e-05, -1.63616789e-06);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(-1.3260e+00, -1.5049e+00, -5.4348e-01, 2.2151e-03, -9.3459e-01, -1.1986e+00, 1.2604e+00, 1.0653e+00, 6.9110e-02, 2.7620e-01, -9.3442e-01, -8.8358e-01, -2.8879e-01, 9.3366e-01, -6.3693e-01, 3.5229e-01));
    r0 += mul(pv0_1, min16float4x4(1.5253e+00, -2.4686e-01, -7.6422e-02, -4.1262e-01, -8.0165e-01, -8.6013e-01, 7.9818e-01, 1.5411e-01, 7.4877e-01, -5.9440e-01, 6.6983e-01, -1.6609e+00, -2.5361e-01, -8.6005e-02, -9.5183e-01, 1.0119e+00));
    r0 += mul(pv0_2, min16float4x4(8.1213e-01, 1.6861e-01, 6.1643e-01, -3.9232e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    texResid[p] = r0;
}

//!PASS 7
//!IN texYcgCo, texYPad
//!OUT texBase
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass7(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texBase.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    int2 PSZ = int2((int)GetOutputSize().x / 2 + 4, (int)GetOutputSize().y / 2 + 4);
    uint2 pp = p + uint2(4, 4);
    float4 ycg = BilinearExtrap(texYcgCo, int2((int)GetOutputSize().x / 2, (int)GetOutputSize().y / 2), p);
    float bY = EDI_Base(texYPad, PSZ, 0, pp);
    texBase[p] = float4(bY, ycg.g, ycg.b, ycg.a);
}

//!PASS 8
//!IN texBase, texResid
//!OUT OUTPUT
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass8(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; OUTPUT.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint2 lr = p >> 1;
    int c = 2 * (int)(p.y & 1u) + (int)(p.x & 1u);
    float4 r4 = texResid.Load(int3(int2(lr), 0));
    float rv = c == 0 ? r4.r : (c == 1 ? r4.g : (c == 2 ? r4.b : r4.a));
    float4 base4 = texBase.Load(int3(int2(p), 0));
    float y = clamp(base4.r + rv, 0.0, 1.0);
    float cg = base4.g - 0.5;
    float co = base4.b - 0.5;
    float tmp = y - cg;
    float r = clamp(tmp + co, 0.0, 1.0);
    float g = clamp(y + cg, 0.0, 1.0);
    float b = clamp(tmp - co, 0.0, 1.0);
    OUTPUT[p] = float4(r, g, b, base4.a);
}
