//!MAGPIE EFFECT
//!VERSION 4
// MagpieFX shader generated by magpie_gen.py (nene2x project's own code).
// config: 3x3_12,1x1_8,3x3_12,3x3_4
// base upscaler: EDI   channels: YCgCo luma   activation: ReLU
//!TEXTURE
Texture2D INPUT;
//!TEXTURE
//!WIDTH INPUT_WIDTH * 2
//!HEIGHT INPUT_HEIGHT * 2
Texture2D OUTPUT;
//!TEXTURE
//!WIDTH INPUT_WIDTH
//!HEIGHT INPUT_HEIGHT
//!FORMAT R16G16B16A16_FLOAT
Texture2D texYcgCo;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texYPad;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_2;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_2;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texResid;
//!TEXTURE
//!WIDTH INPUT_WIDTH * 2
//!HEIGHT INPUT_HEIGHT * 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texBase;

//!COMMON

float4 LoadClamp(Texture2D<float4> tex, int2 pos, int2 size) {
    pos = clamp(pos, int2(0, 0), size - 1);
    return tex.Load(int3(pos, 0));
}

float4 BilinearExtrap(Texture2D<float4> tex, int2 size, uint2 p) {
    // Chroma/alpha upsample: infer.py's bil_up interpolates with tap weights
    // that go outside [0,1] at the border (linear extrapolation), so border
    // pixels do NOT replicate the edge texel — clamping them would make the
    // edge look clamped one texel early.
    float2 q = (float2(p) - 0.5) * 0.5;
    int2 f = (int2)floor(q);
    int2 i0 = clamp(f, int2(0, 0), size - 2);
    int2 i1 = i0 + 1;
    float2 t = q - (float2)i0;
    float4 a = tex.Load(int3(i0, 0));
    float4 b = tex.Load(int3(int2(i1.x, i0.y), 0));
    float4 c = tex.Load(int3(int2(i0.x, i1.y), 0));
    float4 d = tex.Load(int3(i1, 0));
    return a*(1.0-t.x)*(1.0-t.y) + b*t.x*(1.0-t.y) + c*(1.0-t.x)*t.y + d*t.x*t.y;
}

float EDI_Bilinear(Texture2D<float4> tex, int2 size, int2 pos, int comp) {
    // pos is in 2x OUTPUT space (up to 2*size-1), so clamp to the 2x bounds —
    // clamping to size-1 here force-clamped reads to the LR texture edge for
    // every pixel past the top-left quadrant (the "clamped copies" bug).
    pos = clamp(pos, int2(0, 0), size * 2 - 1);
    float ux = ((float)pos.y + 0.5) * 0.5;   // row
    float uy = ((float)pos.x + 0.5) * 0.5;   // col
    int ix = (int)floor(ux - 0.5) + 1;       // row index
    int iy = (int)floor(uy - 0.5) + 1;       // col index
    float s_a = LoadClamp(tex, int2(iy - 1, ix - 1), size)[comp];
    float s_b = LoadClamp(tex, int2(iy - 1, ix),     size)[comp];
    float s_c = LoadClamp(tex, int2(iy,     ix - 1), size)[comp];
    float s_d = LoadClamp(tex, int2(iy,     ix),     size)[comp];
    float tx = ux - (float)ix + 0.5;         // row weight
    float ty = uy - (float)iy + 0.5;         // col weight
    return s_a*(1.0-tx)*(1.0-ty) + s_b*tx*(1.0-ty) + s_c*(1.0-tx)*ty + s_d*tx*ty;
}
float EDI_Base(Texture2D<float4> tex, int2 size, int comp, uint2 p) {
    float ux = ((float)p.y + 0.5) * 0.5;   // row
    float uy = ((float)p.x + 0.5) * 0.5;   // col
    int ix = (int)floor(ux - 0.5) + 1;     // row index
    int iy = (int)floor(uy - 0.5) + 1;     // col index
    float s_a = LoadClamp(tex, int2(iy - 1, ix - 1), size)[comp];
    float s_b = LoadClamp(tex, int2(iy - 1, ix),     size)[comp];
    float s_c = LoadClamp(tex, int2(iy,     ix - 1), size)[comp];
    float s_d = LoadClamp(tex, int2(iy,     ix),     size)[comp];
    float tx = ux - (float)ix + 0.5;       // row weight
    float ty = uy - (float)iy + 0.5;       // col weight
    float dd = clamp((abs(s_c - s_b) - abs(s_d - s_a)) * 8.0, -1.0, 1.0) * 0.5 + 0.5;
    float iBS = (tx + ty < 1.0)
        ? s_c*ty + s_b*tx + s_a*(1.0 - (tx + ty))
        : s_c*(1.0-tx) + s_b*(1.0-ty) + s_d*(1.0 - ((1.0-tx) + (1.0-ty)));
    float iFS = (tx > ty)
        ? s_a*(1.0-tx) + s_d*ty + s_b*(1.0 - ((1.0-tx) + ty))
        : s_a*(1.0-ty) + s_d*tx + s_c*(1.0 - (tx + (1.0-ty)));
    float bil = EDI_Bilinear(tex, size, int2(p), comp);
    float ev = (round(dd) > 0.5) ? iFS : iBS;
    float mix = abs(dd - 0.5) * 2.0;
    float resv = (1.0 - mix) * bil + mix * ev;
    float hf = 0.5*(2.0/3.0)*bil - 0.5/6.0*(EDI_Bilinear(tex, size, int2(p) + int2(0, -2), comp)
        + EDI_Bilinear(tex, size, int2(p) + int2(-2, 0), comp)
        + EDI_Bilinear(tex, size, int2(p) + int2(0, 2), comp)
        + EDI_Bilinear(tex, size, int2(p) + int2(2, 0), comp));
    return resv + hf;
}


//!PASS 1
//!IN INPUT
//!OUT texYcgCo
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass1(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texYcgCo.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    float4 c = INPUT.Load(int3(int2(p), 0));
    float y = 0.25*c.r + 0.5*c.g + 0.25*c.b;
    float cg = -0.25*c.r + 0.5*c.g - 0.25*c.b + 0.5;
    float co = 0.5*c.r - 0.5*c.b + 0.5;
    texYcgCo[p] = float4(y, cg, co, c.a);
}

//!PASS 2
//!IN INPUT
//!OUT texYPad
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass2(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texYPad.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    float4 c = LoadClamp(INPUT, int2(p) - int2(3, 3), int2((int)GetInputSize().x, (int)GetInputSize().y));
    float y = 0.25*c.r + 0.5*c.g + 0.25*c.b;
    float cg = -0.25*c.r + 0.5*c.g - 0.25*c.b + 0.5;
    float co = 0.5*c.r - 0.5*c.b + 0.5;
    texYPad[p] = float4(y, cg, co, c.a);
}

//!PASS 3
//!IN texYPad
//!OUT texL0_0, texL0_1, texL0_2
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass3(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL0_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL0_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.00589540042, 0.00513533968, 0.00430190656, -0.00186427706);
    min16float4 r1 = min16float4(0.000245634437, 0.0117857344, -0.00157748931, -0.00193399924);
    min16float4 r2 = min16float4(0.000431414403, 0.00346327899, 0.000825940806, 0.00333453319);
    min16float4 pv0_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(2.9855e-02, 6.1759e-02, 7.2964e-02, -4.8218e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv0_0, min16float4x4(-4.1456e-02, -7.5984e-02, 8.2455e-02, 4.0744e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv0_0, min16float4x4(-4.8098e-03, -2.6718e-02, -5.8083e-02, -1.0802e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv1_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(-7.0897e-03, 8.5407e-02, -3.7880e-01, -1.6931e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv1_0, min16float4x4(-2.6539e-02, 4.6100e-02, -1.4698e-01, 1.5200e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv1_0, min16float4x4(-1.7505e-02, 2.4089e-02, -3.2680e-02, -4.2463e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv2_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(1.1559e-01, 2.4838e-02, 1.6759e-01, 1.7412e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv2_0, min16float4x4(-1.1103e-01, -1.4985e-01, -2.8879e-02, 5.0389e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv2_0, min16float4x4(1.2046e-02, 4.1276e-02, 1.2630e-01, -6.3246e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv3_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(1.6041e-03, 3.7349e-02, 2.4828e-03, 5.3002e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv3_0, min16float4x4(2.3538e-03, -2.1584e-02, -2.1176e-01, 1.5335e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv3_0, min16float4x4(-2.2099e-02, -4.2959e-02, -3.8265e-02, 1.2980e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv4_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(1.3080e-01, -3.8381e-01, 8.3085e-02, -3.4204e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv4_0, min16float4x4(2.1763e-01, 6.2363e-02, 1.2932e-01, -1.7822e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv4_0, min16float4x4(3.0269e-01, 1.5201e-01, 1.8171e-01, 1.3877e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv5_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(-1.3310e-01, 3.3013e-04, 6.2542e-02, 2.4979e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv5_0, min16float4x4(2.4983e-01, 2.0239e-01, -1.0411e-01, -1.2608e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv5_0, min16float4x4(-1.6240e-01, 1.9010e-01, -1.3977e-01, -9.3944e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv6_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(8.0029e-03, 1.2782e-01, 3.0636e-02, -3.9489e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv6_0, min16float4x4(1.9972e-02, 5.3367e-03, 8.3057e-02, -5.8534e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv6_0, min16float4x4(2.7865e-02, 3.2179e-02, 1.2995e-01, -8.5376e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv7_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(-2.7882e-01, 8.4234e-02, -4.8008e-02, 1.8196e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv7_0, min16float4x4(-3.5069e-01, -1.6456e-01, 1.7476e-01, 9.7958e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv7_0, min16float4x4(-6.3416e-02, -1.3564e-01, -1.0703e-01, 1.7262e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv8_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(1.3974e-01, -4.2552e-02, 1.3930e-02, -9.7107e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv8_0, min16float4x4(5.9850e-02, 1.0651e-02, 4.7939e-02, -5.2269e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv8_0, min16float4x4(-7.2643e-02, -2.0668e-01, -8.1871e-02, -1.1026e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    r2 = max(r2, 0.0);
    texL0_0[p] = r0;
    texL0_1[p] = r1;
    texL0_2[p] = r2;
}

//!PASS 4
//!IN texL0_0, texL0_1, texL0_2
//!OUT texL1_0, texL1_1
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass4(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL1_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL1_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.00436353683, 0.00481147319, -0.000168693252, -0.000344622706);
    min16float4 r1 = min16float4(0.00308695226, 0.00232774904, 0.00298785628, -0.006690952);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_2 = (min16float4)LoadClamp(texL0_2, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(3.1351e-02, 4.4925e-01, -2.4969e-01, 5.8384e-02, 7.9293e-01, -3.5355e-01, 2.3289e-01, 2.6746e-01, -1.5516e-01, -7.5634e-02, 1.2498e-01, 8.4710e-01, 1.2286e-01, 4.5695e-02, 8.0785e-02, -2.0700e-01));
    r0 += mul(pv0_1, min16float4x4(-1.1181e-01, -2.7033e-01, 1.0985e+00, -2.0159e-01, 1.9639e-01, 2.0716e-01, 3.3146e-03, -2.0713e-01, -5.6951e-01, 2.9523e-01, -3.0750e-01, -1.7665e-01, 4.0154e-02, 2.0071e-01, -7.7455e-01, 4.8100e-01));
    r0 += mul(pv0_2, min16float4x4(-5.6772e-01, 9.3166e-01, 1.5592e+00, -4.4256e-01, 1.8619e-01, -1.9108e-01, -1.7835e-01, -8.7528e-02, -2.2649e-01, 3.1185e-01, -8.0966e-01, -9.5407e-02, 5.2932e-01, 3.5415e-02, -6.7130e-01, -9.8073e-02));
    r1 += mul(pv0_0, min16float4x4(-1.1226e-01, 3.3842e-01, -2.5928e-01, -7.0031e-01, 5.3141e-01, -3.2543e-01, -1.1908e+00, -4.5820e-01, -2.2136e-01, 8.5636e-01, -2.6218e-02, 6.4803e-01, 1.3177e+00, 3.5307e-01, 4.0128e-01, -5.6992e-01));
    r1 += mul(pv0_1, min16float4x4(2.8712e-01, 5.5979e-01, -9.2644e-01, 4.2053e-01, 1.7966e-01, -1.3224e-01, -3.4439e-02, 3.8519e-01, -1.8765e-01, 1.8515e-01, 4.0315e-01, 2.8230e-01, -1.0101e+00, 4.1232e-02, 5.3381e-01, -7.8362e-02));
    r1 += mul(pv0_2, min16float4x4(-1.3091e+00, 1.1737e-01, -1.7668e+00, 1.7578e-01, -1.6141e-01, 4.0871e-01, -4.6281e-01, -1.7126e-01, -2.0722e-01, 1.7490e-01, 6.3307e-02, -5.0342e-02, -3.8038e-02, 5.7598e-02, 6.9531e-01, 3.0274e-01));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    texL1_0[p] = r0;
    texL1_1[p] = r1;
}

//!PASS 5
//!IN texL1_0, texL1_1
//!OUT texL2_0, texL2_1, texL2_2
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass5(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL2_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL2_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.00318869669, -0.000886814902, -0.0015115618, 6.15441313e-05);
    min16float4 r1 = min16float4(-0.00202738913, 0.00451478595, 0.000483792071, -0.000522613293);
    min16float4 r2 = min16float4(-0.00136811368, -0.00198385655, -0.000837494095, -0.00393932499);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(2.4520e-02, -1.1397e-01, -1.9154e-01, 3.4865e-02, -5.2738e-02, -1.0116e-01, 6.2795e-02, 2.2070e-02, 5.9513e-02, -2.1726e-01, -2.9514e-01, 8.7432e-02, -2.4777e-03, -7.6224e-02, 5.5693e-02, 5.3194e-02));
    r0 += mul(pv0_1, min16float4x4(5.5393e-02, -2.3518e-01, -1.3178e-02, 4.5827e-02, 1.1698e-02, -3.3702e-02, 8.7923e-03, 1.3175e-02, -1.6171e-01, -3.5546e-04, -1.1629e-01, -1.3977e-02, -4.5204e-02, 3.7701e-03, -3.6883e-02, -1.5050e-02));
    r1 += mul(pv0_0, min16float4x4(2.1119e-02, 3.0554e-01, 1.8475e-01, 4.7105e-02, 5.2232e-02, -1.6469e-01, -1.3736e-01, 3.9842e-02, 2.0511e-01, 2.8046e-01, 3.0502e-01, 1.1372e-01, 3.8456e-02, -1.1449e-01, -6.4919e-01, 3.0939e-02));
    r1 += mul(pv0_1, min16float4x4(-2.0394e-01, 7.5087e-02, 3.5625e-02, 4.7290e-02, 1.2456e-01, 1.6075e-01, 1.4406e-01, 2.9371e-02, 4.2314e-03, -1.5763e-02, -9.8032e-02, -6.6799e-02, -4.9879e-02, -1.8884e-01, -1.6229e-01, -9.3922e-02));
    r2 += mul(pv0_0, min16float4x4(-1.6499e-02, -1.4213e-02, 4.4134e-02, -1.0832e-02, 5.5029e-02, 3.3516e-01, -4.0496e-01, 8.3167e-02, 2.9990e-01, -5.3866e-02, -1.0561e-01, -9.3816e-02, 1.1463e-01, 6.4598e-02, -1.8324e-01, 1.9449e-02));
    r2 += mul(pv0_1, min16float4x4(2.7261e-02, 7.7422e-02, -9.9374e-02, -6.3470e-02, -6.2966e-02, -6.2418e-02, 1.3008e-01, 1.0692e-02, -7.9346e-02, -1.9828e-02, 4.3336e-02, -7.4067e-02, -1.0819e-01, -3.2632e-03, -1.2032e-01, -8.3357e-02));
    min16float4 pv1_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(1, 0), SZ);
    min16float4 pv1_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(2.0096e-01, 1.9424e-01, -2.0928e-01, -1.2490e-01, 1.0712e-01, 1.8984e-01, 4.1311e-02, -4.5260e-02, 1.5762e-01, 2.1178e-01, 1.4688e-01, 4.8456e-02, -1.2773e-01, -1.2523e-01, 5.2407e-02, 9.9676e-02));
    r0 += mul(pv1_1, min16float4x4(1.3439e-01, -5.1361e-03, 2.5613e-01, 6.6419e-02, 5.5745e-02, 1.1665e-01, -1.2467e-01, -4.0887e-02, 2.9837e-02, -1.0463e-01, -9.0131e-02, -6.6152e-03, -4.3965e-02, 3.8524e-02, 1.8735e-01, -9.6576e-02));
    r1 += mul(pv1_0, min16float4x4(-5.6670e-01, 5.2455e-02, 7.4950e-02, -8.8118e-02, -2.0059e-01, -4.9269e-01, -6.9770e-02, -1.3008e-01, 3.3751e-01, 1.6293e-01, -1.3456e+00, -3.6230e-01, -1.0463e-01, -1.3318e-01, 1.4021e-01, 4.1086e-02));
    r1 += mul(pv1_1, min16float4x4(5.6184e-02, -4.7911e-02, 9.5052e-02, 9.2853e-02, 3.9296e-02, 2.3916e-01, -2.3003e-01, -8.9776e-02, 2.0104e-01, 4.5820e-01, -1.7698e-01, -5.8293e-02, -2.7995e-01, -3.7387e-01, 1.8005e-01, -4.3035e-02));
    r2 += mul(pv1_0, min16float4x4(6.7665e-02, -6.4212e-01, 2.5214e-01, -2.0751e-01, -3.4717e-02, 2.2659e-01, 1.2191e-01, 6.2917e-02, 6.8800e-02, 1.9227e-02, -1.9614e-01, 1.2318e-01, -1.1829e-01, 4.7277e-02, -2.1396e-01, -2.2486e-02));
    r2 += mul(pv1_1, min16float4x4(4.9933e-02, 1.8290e-01, 8.5325e-02, -4.5365e-02, 1.9827e-02, -1.5255e-01, -3.3001e-02, 1.4296e-02, 7.9646e-03, -1.0721e-01, 1.1180e-01, -5.6306e-03, -2.1566e-01, 2.4767e-01, 3.2853e-01, 6.4731e-02));
    min16float4 pv2_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(2, 0), SZ);
    min16float4 pv2_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(-1.0503e-01, -4.7419e-01, -6.3757e-02, 4.0685e-02, -3.8496e-03, 1.2472e-01, 5.2451e-02, -3.3613e-02, 8.0656e-02, -8.5651e-04, 1.0682e-01, -6.7407e-02, 1.0314e-01, 1.8035e-01, 9.8932e-02, -9.6430e-02));
    r0 += mul(pv2_1, min16float4x4(2.8602e-04, 1.1317e-01, 1.6337e-02, -7.1676e-02, -6.6516e-02, -1.8390e-01, -6.7846e-02, 6.6182e-02, -1.5167e-01, 5.1618e-02, 1.9729e-03, 2.3745e-02, -6.6395e-02, -1.2843e-01, -5.8814e-02, 2.3682e-02));
    r1 += mul(pv2_0, min16float4x4(2.1351e-01, -5.4535e-03, -7.0666e-04, -6.1532e-02, -3.2459e-02, -1.0606e-01, -4.6041e-02, -7.2844e-02, 1.2676e-01, -5.1692e-02, -9.0350e-02, -6.9491e-02, -8.3774e-02, 1.3485e-01, 1.5540e-02, 3.7472e-02));
    r1 += mul(pv2_1, min16float4x4(-2.6915e-02, 7.2973e-02, -1.0346e-02, -1.1759e-01, 1.4353e-01, -9.6870e-02, 2.4998e-02, 5.1795e-02, 1.5308e-01, 6.3916e-02, -7.8193e-03, -1.2292e-01, -5.5602e-02, 1.4806e-01, 7.4269e-02, 6.4638e-02));
    r2 += mul(pv2_0, min16float4x4(-7.8981e-02, 1.7765e-01, 7.0006e-02, -2.4547e-01, -4.6411e-02, -8.4621e-02, 2.3382e-01, 8.5963e-02, -7.4221e-02, -1.8658e-02, 3.8974e-01, -3.9066e-01, 1.0699e-01, -5.0329e-02, 1.2567e-01, 1.2840e-01));
    r2 += mul(pv2_1, min16float4x4(-9.5919e-03, -6.7301e-02, 2.7430e-01, 5.8680e-02, -4.1230e-02, 3.0638e-02, -1.6572e-01, -1.1234e-01, -1.9365e-01, -3.7526e-01, -1.6944e-01, -5.0935e-03, 7.0350e-02, -5.9100e-02, -2.5244e-01, -5.0066e-02));
    min16float4 pv3_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(0, 1), SZ);
    min16float4 pv3_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(-9.7630e-02, 9.4764e-02, 9.8971e-02, 1.4149e-03, 2.6985e-01, 3.9185e-01, -7.4867e-01, 1.3211e-01, 1.4925e-03, -1.8170e-01, -1.0261e-01, 4.3504e-01, 1.6274e-01, 2.8170e-01, -1.2281e-02, -4.8631e-02));
    r0 += mul(pv3_1, min16float4x4(-1.9288e-02, -4.4896e-02, -3.9386e-02, 1.6744e-01, -3.1059e-01, -5.9277e-02, 1.2804e-01, -6.1593e-02, 8.7648e-02, 2.5328e-02, -3.4380e-01, 5.8891e-02, 2.8682e-01, -2.0568e-02, -7.5033e-02, 4.7988e-02));
    r1 += mul(pv3_0, min16float4x4(-2.6379e-01, -1.0792e-01, 1.8958e-01, -4.6932e-02, -2.4694e-02, -4.0088e-01, 1.4939e-01, 1.6680e-01, 1.6200e-01, 7.0129e-02, 2.9501e-01, 4.9753e-01, 7.0535e-02, -1.8918e-01, -7.3890e-01, -5.5043e-02));
    r1 += mul(pv3_1, min16float4x4(2.3219e-01, -7.9451e-02, 2.9656e-01, 1.6445e-01, 5.6289e-02, -4.2167e-01, -2.1042e-01, -8.2782e-02, -3.7352e-01, 1.8530e-01, 8.0061e-02, 9.4440e-02, 2.3813e-01, 6.4005e-02, 2.4322e-01, 1.5957e-01));
    r2 += mul(pv3_0, min16float4x4(8.8349e-02, -1.2077e-01, 1.6813e-01, 1.2975e-02, 3.3492e-01, -4.1778e-02, -7.2240e-01, 4.2177e-01, 2.2636e-02, 1.5803e-02, -2.1876e-01, -1.4966e-02, -1.8138e-01, -1.3031e-01, -1.4492e-01, 1.8251e-01));
    r2 += mul(pv3_1, min16float4x4(1.4128e-01, 1.9306e-02, -1.6102e-01, 6.5112e-02, -1.5056e-02, -2.8647e-04, 3.0378e-01, -2.4993e-01, -2.2796e-02, -2.5180e-01, 1.2102e-01, -1.5446e-03, 5.7158e-01, -1.6806e-01, -3.9436e-02, -1.6081e-02));
    min16float4 pv4_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(1, 1), SZ);
    min16float4 pv4_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(-6.2105e-01, -5.6668e-01, -2.7529e-01, 1.5128e-02, -8.6831e-02, -1.4551e-01, 6.7286e-01, -2.1661e-02, -3.3328e-01, 4.5389e-01, 3.7731e-01, 4.4686e-01, -3.9153e-03, -2.8074e-01, -5.7719e-01, -1.0956e-01));
    r0 += mul(pv4_1, min16float4x4(-3.5542e-01, 4.6325e-01, 3.0264e-01, -4.4479e-02, -3.5283e-01, -2.7595e-01, -7.2536e-02, 4.8968e-02, 6.4324e-01, -7.7160e-02, 3.6676e-02, -8.0938e-02, 8.8242e-03, -1.9694e-01, 1.4342e-01, -3.3191e-01));
    r1 += mul(pv4_0, min16float4x4(-6.5714e-01, 5.1756e-02, -2.7989e-01, -1.0265e-02, -5.2208e-02, -6.5645e-01, -2.3747e-01, -4.3621e-02, -2.1747e-01, 5.2179e-01, -6.8956e-02, 5.1384e-01, -6.9812e-01, -6.1145e-01, -3.7754e-01, -2.9306e-01));
    r1 += mul(pv4_1, min16float4x4(5.8618e-02, 1.1114e-01, -9.5615e-01, -3.9320e-01, 4.6447e-02, -3.5380e-01, 9.3782e-02, 1.3066e-01, -3.6865e-01, -9.6668e-02, 8.5680e-03, 2.7107e-01, 4.1300e-02, 3.3634e-01, -2.6714e-01, -3.3075e-01));
    r2 += mul(pv4_0, min16float4x4(-7.6753e-01, -5.7741e-01, -8.9689e-01, -4.6055e-01, -2.9266e-02, 3.2299e-01, 3.9156e-01, -8.7028e-01, 3.6753e-02, -1.4516e-01, 4.1421e-02, 1.1843e-01, 1.7835e-01, 1.3126e-02, 8.4685e-01, -2.5526e-01));
    r2 += mul(pv4_1, min16float4x4(-5.4073e-01, 2.9823e-01, -1.3324e-01, 2.2651e-01, 4.7266e-03, 2.0402e-01, -5.1004e-01, 1.3909e-01, -5.4506e-02, -6.4717e-03, -2.8628e-01, 2.6195e-02, 3.2172e-01, 1.4416e-01, 7.3336e-02, -1.4223e-02));
    min16float4 pv5_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(2, 1), SZ);
    min16float4 pv5_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(3.5707e-01, -1.1038e-01, 1.1461e-02, -1.6573e-01, 8.4912e-02, 6.1000e-02, 8.5411e-03, -3.2178e-02, 1.3506e-01, 4.1206e-02, 8.8902e-02, -8.3689e-02, 6.2930e-02, 3.1350e-01, 2.2262e-02, -9.6459e-04));
    r0 += mul(pv5_1, min16float4x4(-4.3192e-02, 9.8165e-03, 4.7675e-02, -2.8614e-02, 1.8740e-02, 8.2312e-03, -2.3446e-02, 2.8033e-02, -2.9481e-02, 1.2241e-02, 2.8800e-01, 7.0788e-03, 2.1353e-01, -3.1300e-01, -1.5927e-01, 9.9722e-02));
    r1 += mul(pv5_0, min16float4x4(-6.2847e-01, 6.8454e-02, 6.5745e-03, 1.4242e-01, -2.1623e-01, -1.3032e-02, -1.0622e-01, -6.4780e-02, -4.3890e-02, 2.3987e-01, -1.4300e-01, -1.4223e-01, 8.5157e-02, -1.5639e-01, 7.3399e-02, 3.3601e-01));
    r1 += mul(pv5_1, min16float4x4(4.1463e-02, 2.3645e-02, 1.6849e-02, -2.5102e-02, -2.8020e-01, 3.5689e-02, -3.0414e-02, -5.1004e-02, -3.1655e-01, 1.1210e-01, -2.3091e-01, 7.8827e-02, -2.1288e-01, -2.2002e-01, 1.4817e-01, 8.4502e-02));
    r2 += mul(pv5_0, min16float4x4(5.0427e-02, -2.6154e-02, -3.7828e-01, 3.8491e-01, -8.7612e-02, -3.7136e-01, -1.5008e-01, 1.3156e-01, -8.2941e-02, 9.2956e-02, 3.0441e-01, -2.0004e-01, 1.1327e-01, 3.7439e-01, -7.3515e-01, 8.7633e-02));
    r2 += mul(pv5_1, min16float4x4(5.3125e-03, -7.2650e-02, 2.1779e-01, -1.8969e-01, -5.1569e-02, -1.4080e-01, -9.8362e-02, 1.4364e-01, 4.8833e-02, 2.4311e-01, 2.4471e-01, -3.1932e-02, 1.0603e-01, -7.1978e-02, -4.0112e-01, -4.1994e-02));
    min16float4 pv6_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(0, 2), SZ);
    min16float4 pv6_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(-4.7935e-02, -1.4874e-01, -2.0503e-01, -5.5954e-02, -3.7917e-02, 1.2809e-01, -1.2351e-01, 1.0118e-01, -1.4913e-02, 1.2269e-01, -9.7791e-02, 2.4024e-01, 1.9448e-02, -5.8857e-02, 1.5570e-01, 8.4887e-02));
    r0 += mul(pv6_1, min16float4x4(1.4381e-02, 9.1066e-02, 8.6663e-02, 5.6987e-02, 7.1880e-02, -2.5363e-01, 1.1068e-01, -2.4663e-01, -3.5062e-01, -3.3354e-02, -1.5607e-01, -8.4710e-02, 2.7651e-01, 2.4352e-01, 2.2682e-02, 5.3983e-02));
    r1 += mul(pv6_0, min16float4x4(-1.0200e-02, 5.8131e-02, 1.5124e-01, -4.0271e-02, 4.2782e-01, 2.1640e-02, 2.1962e-02, 1.5344e-01, 9.9505e-02, -2.2847e-02, 1.3888e-01, 1.5125e-01, 2.2221e-01, 1.8845e-01, -4.6888e-01, 1.0350e-01));
    r1 += mul(pv6_1, min16float4x4(-1.1590e-01, -1.3953e-01, -2.1197e-02, 1.3584e-01, -4.7162e-01, -2.1898e-02, -1.7505e-01, -1.1778e-01, -5.8833e-02, -3.2253e-02, -6.3845e-02, -8.6422e-02, 1.8313e-03, 2.5649e-01, -1.7086e-01, 2.9279e-03));
    r2 += mul(pv6_0, min16float4x4(-1.4176e-01, -1.0651e-01, -4.0914e-02, -6.9623e-02, -1.1759e-01, 3.9029e-02, -3.4401e-01, -1.8490e-02, -6.7858e-02, -2.0378e-02, -1.0078e-01, 8.5907e-02, 1.1834e-01, 9.8092e-02, -1.5555e-02, -1.8247e-01));
    r2 += mul(pv6_1, min16float4x4(7.8016e-02, 5.8359e-04, -4.1205e-02, 9.3157e-02, 7.6383e-02, 9.9947e-03, 1.9437e-01, -1.1962e-01, -1.1189e-01, -9.2451e-02, -4.3750e-02, -2.5755e-02, -1.1317e-01, -1.2111e-01, -6.9963e-02, 9.2687e-02));
    min16float4 pv7_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(1, 2), SZ);
    min16float4 pv7_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(-5.8740e-01, -1.7981e-01, -4.7549e-02, 2.1593e-01, -8.0227e-03, -7.0529e-02, 1.1848e-01, -6.7864e-02, -2.6444e-01, -1.4705e-01, 1.6543e-01, 1.7617e-01, 6.7917e-01, -2.8677e-02, -3.6273e-01, 6.8866e-02));
    r0 += mul(pv7_1, min16float4x4(-3.0797e-02, 2.3667e-02, -1.7651e-01, -8.7743e-02, 3.6224e-01, 2.9886e-01, -2.5716e-01, -2.7499e-01, -6.8784e-01, 1.1834e-01, 8.7482e-02, 2.7915e-01, -6.1260e-02, 2.2638e-01, -1.7955e-01, 3.3859e-01));
    r1 += mul(pv7_0, min16float4x4(1.8064e-01, 1.2281e-01, 8.4159e-02, 2.6865e-01, 3.4078e-01, 1.0574e-01, 1.4996e-01, 4.6787e-02, 7.5905e-03, 1.9039e-01, 2.3584e-02, 2.5948e-01, -1.5915e-01, -7.7290e-01, -1.5060e-01, -1.2395e-01));
    r1 += mul(pv7_1, min16float4x4(-2.7233e-01, -9.2046e-02, -4.2136e-02, -1.9543e-01, -3.6389e-01, -4.0350e-01, 3.3720e-03, -4.1657e-01, -3.7441e-01, -1.1049e-01, 1.1190e-02, 1.2796e-01, 2.5898e-01, 2.1024e-01, 4.8933e-02, 2.5218e-01));
    r2 += mul(pv7_0, min16float4x4(4.4414e-02, 2.2404e-01, -1.2315e-01, -6.9319e-02, -6.6613e-02, -2.1406e-01, 1.5053e-01, 1.7389e-01, 6.8421e-02, 6.9990e-02, -7.1549e-02, -1.1501e-01, 3.1320e-02, -7.3855e-01, 6.8349e-01, 6.2537e-02));
    r2 += mul(pv7_1, min16float4x4(-3.6149e-02, -8.6969e-02, -2.7701e-01, -6.0010e-02, -1.5133e-01, -2.4017e-01, -4.1653e-02, 1.1591e-01, 8.5152e-02, -9.8657e-02, -1.9325e-01, -5.6014e-02, -3.0256e-01, 5.0933e-02, 3.3115e-02, -9.3561e-02));
    min16float4 pv8_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(2, 2), SZ);
    min16float4 pv8_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(-3.0237e-01, -2.5830e-01, 6.4179e-02, -2.5244e-02, -9.4221e-02, 2.0675e-02, 1.0305e-01, 2.0247e-02, -3.6148e-02, -3.8235e-02, 4.7024e-02, -1.8227e-02, -7.4074e-02, 1.1094e-01, 5.5455e-02, 1.0433e-01));
    r0 += mul(pv8_1, min16float4x4(3.5790e-02, -3.2280e-02, -2.8605e-02, -5.7299e-02, -8.4417e-02, 1.4859e-02, -4.8653e-02, -1.5286e-02, -5.0910e-01, -7.7265e-02, -3.9082e-02, -5.6318e-02, -1.1121e-01, 1.2137e-01, -5.0028e-02, 1.6587e-02));
    r1 += mul(pv8_0, min16float4x4(3.4275e-02, 1.7196e-01, 8.2592e-02, -1.3850e-01, 1.3927e-01, 6.0932e-02, 5.4075e-03, -4.7963e-02, -1.4108e-01, 2.0712e-01, -2.2292e-02, -7.8482e-03, 2.2446e-01, -1.3746e-01, 9.4231e-02, 3.7958e-01));
    r1 += mul(pv8_1, min16float4x4(-3.7056e-02, -4.7631e-02, 1.7700e-02, 2.1977e-02, 6.5187e-02, -1.8754e-01, 2.3742e-02, 3.1850e-02, -2.5705e-02, 2.6669e-01, 4.7929e-02, -1.9810e-02, 6.0296e-01, 3.8976e-02, 6.3252e-03, 1.1656e-01));
    r2 += mul(pv8_0, min16float4x4(-7.7809e-02, -1.3619e-01, 1.3337e-01, -9.6580e-02, 3.0496e-02, 8.1173e-02, 2.6189e-01, -1.9902e-01, -4.5746e-02, -8.6746e-02, 8.5886e-02, -1.0465e-01, 1.4772e-01, 3.7942e-01, -5.4131e-01, 1.3439e-02));
    r2 += mul(pv8_1, min16float4x4(8.1587e-03, 2.2284e-02, -1.3938e-02, -1.2952e-01, 5.0953e-02, 1.0066e-01, -1.4741e-01, 1.1144e-01, -5.2886e-02, -1.1772e-01, -1.0860e-01, 3.1173e-02, -7.9085e-02, 5.3399e-02, 8.6720e-02, -3.9449e-01));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    r2 = max(r2, 0.0);
    texL2_0[p] = r0;
    texL2_1[p] = r1;
    texL2_2[p] = r2;
}

//!PASS 6
//!IN texL2_0, texL2_1, texL2_2
//!OUT texResid
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass6(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texResid.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texResid.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(4.59601943e-05, -6.05407695e-05, 1.56482765e-05, 9.49649257e-06);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(1.6767e-01, 2.3318e-02, -2.5740e-02, -4.0876e-03, 3.6704e-02, 1.3170e-01, -7.3605e-02, 9.1838e-03, 6.4481e-02, 2.7309e-02, 4.4465e-02, -7.3560e-03, 1.7156e-01, -6.0088e-02, -2.5383e-02, 1.5167e-02));
    r0 += mul(pv0_1, min16float4x4(-5.8812e-02, 8.8914e-02, 4.8372e-02, -7.8066e-03, -5.0598e-01, -4.5235e-02, 2.4027e-01, 4.8673e-02, -1.2832e-02, -2.2485e-02, -9.0662e-04, -1.0878e-03, -9.1458e-02, 7.1771e-02, -2.4877e-03, -8.6936e-03));
    r0 += mul(pv0_2, min16float4x4(1.3331e-02, -1.8594e-02, 6.3293e-04, -7.2316e-04, -2.9268e-02, 8.9719e-03, -3.5551e-02, -6.7450e-03, 3.0837e-01, -3.0680e-01, -4.3456e-02, -1.6142e-01, 4.5297e-01, -3.7370e-01, 3.3826e-02, -8.1565e-02));
    min16float4 pv1_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(1, 0), SZ);
    min16float4 pv1_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(1, 0), SZ);
    min16float4 pv1_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(1.6607e-01, 1.8851e-01, -6.8379e-02, -5.8846e-02, -1.6874e-01, -1.1307e-01, 1.7123e-01, 1.9705e-01, 1.5343e-01, 2.1186e-01, -5.1699e-02, -9.0867e-02, -7.9374e-01, 2.2182e-02, 2.2382e-02, 1.1477e-01));
    r0 += mul(pv1_1, min16float4x4(-3.3631e-01, -2.7965e-01, 1.4975e-01, 9.4873e-02, 4.1321e-02, -5.5769e-01, 1.9524e-01, 4.3812e-01, 5.0575e-01, 1.3079e-01, -3.9614e-01, 1.5005e-01, 2.6447e-01, -2.7021e-03, -7.6408e-02, -1.0899e-01));
    r0 += mul(pv1_2, min16float4x4(-1.1243e-01, 9.4006e-04, -9.2310e-03, 2.5883e-03, -9.8929e-02, -2.2809e-01, 2.4595e-02, 4.8114e-02, -4.1134e-02, 3.2181e-02, 7.9429e-03, -4.5154e-02, -1.7298e-01, 2.6739e-01, -3.1765e-01, 3.9895e-02));
    min16float4 pv2_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(2, 0), SZ);
    min16float4 pv2_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(2, 0), SZ);
    min16float4 pv2_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(-4.1420e-02, 1.3553e-01, -5.5480e-03, -1.3507e-02, -1.1926e-02, 3.0142e-02, 2.3101e-02, 5.7360e-02, 3.2261e-02, -5.4362e-03, -5.6489e-03, -7.0373e-03, 1.4131e-01, -2.6619e-01, -4.7459e-02, -5.9010e-02));
    r0 += mul(pv2_1, min16float4x4(7.6072e-02, -1.8587e-01, -1.9514e-02, 5.4378e-02, 2.6057e-04, 3.6111e-01, -6.4256e-02, 2.8496e-02, 1.5381e-01, -5.1766e-01, 1.5309e-01, 2.8770e-01, 1.9280e-02, -6.4299e-02, 2.7431e-02, -4.8890e-02));
    r0 += mul(pv2_2, min16float4x4(1.2182e-02, -8.0209e-02, 5.6919e-03, -3.2039e-03, -1.1020e-02, -6.4089e-03, 4.7835e-03, -9.2330e-04, -5.9815e-03, -9.5772e-03, 1.1653e-03, -9.5386e-04, -9.2409e-03, -5.9494e-03, 1.0227e-02, -6.6289e-04));
    min16float4 pv3_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(0, 1), SZ);
    min16float4 pv3_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(0, 1), SZ);
    min16float4 pv3_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(-4.4761e-01, -2.0108e-03, 4.8970e-01, 5.0571e-02, -3.3116e-01, 2.0353e-01, -2.6063e-01, 4.2318e-01, 3.1680e-01, -1.8603e-01, 1.7437e-01, -1.9595e-01, 2.2267e-01, 2.1294e-02, 3.5592e-01, -7.3715e-02));
    r0 += mul(pv3_1, min16float4x4(7.1421e-01, 6.6247e-02, -7.7895e-01, -1.2905e-01, 4.6999e-02, -9.0353e-02, 1.2947e-01, 4.4036e-02, 5.7267e-02, 1.8475e-02, 4.2715e-04, -1.7998e-02, -2.7176e-01, -2.1290e-02, -2.7839e-01, 8.5928e-02));
    r0 += mul(pv3_2, min16float4x4(-1.1816e-01, 4.8493e-03, 2.3411e-02, -4.1059e-02, -8.0572e-01, 1.4208e-01, -6.1147e-02, 1.6573e-01, 1.0698e+00, -1.1649e+00, 1.2034e+00, -1.0781e+00, 5.7637e-01, -3.9005e-01, 1.2591e+00, -7.6452e-01));
    min16float4 pv4_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(1, 1), SZ);
    min16float4 pv4_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(1, 1), SZ);
    min16float4 pv4_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(-7.6329e-01, -1.1338e+00, 6.7876e-01, 1.1666e+00, 2.8311e-01, -1.6892e-01, -7.8375e-02, -8.5980e-01, -3.8529e-01, 5.7144e-01, -2.2411e-01, 1.1057e+00, -8.1727e-02, 6.5458e-01, -8.7826e-01, 4.2536e-01));
    r0 += mul(pv4_1, min16float4x4(6.4913e-01, 1.2996e+00, -4.6884e-01, -1.3286e+00, 1.1353e+00, 1.0614e+00, -1.2988e+00, -8.3709e-01, -6.7874e-01, -1.7720e-01, 8.5703e-01, -2.4383e-01, 3.9918e-02, -6.9234e-01, 1.2027e+00, -1.8843e-01));
    r0 += mul(pv4_2, min16float4x4(1.2131e+00, 5.4948e-02, -3.1419e-01, -2.1210e-01, 1.4939e-02, 5.4065e-01, 2.9931e-02, -5.5472e-01, -6.6127e-03, -6.4534e-02, 7.7999e-03, -1.9473e-01, -9.2645e-02, -5.3601e-01, -2.3727e-01, 8.3784e-01));
    min16float4 pv5_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(2, 1), SZ);
    min16float4 pv5_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(2, 1), SZ);
    min16float4 pv5_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(-6.6471e-02, -8.6844e-02, 1.1914e-02, 5.1823e-02, 6.1833e-03, 6.1675e-02, -3.1484e-02, 4.2073e-02, -2.5726e-02, -9.9108e-02, 1.1736e-03, -4.1767e-02, 4.8530e-02, -7.6363e-02, 1.3454e-01, -6.9230e-03));
    r0 += mul(pv5_1, min16float4x4(1.6603e-02, -1.4768e-03, -9.0456e-02, -1.3630e-02, 1.9661e-02, 8.2456e-02, 7.6162e-02, -3.0765e-01, -8.2347e-01, 1.3764e+00, -7.2923e-01, 2.7467e-01, -6.4914e-02, -3.8226e-02, -3.9070e-02, 9.8533e-02));
    r0 += mul(pv5_2, min16float4x4(-2.6979e-01, 5.8901e-01, -1.3505e-02, -1.6009e-01, -3.5806e-03, -1.9894e-03, -1.0903e-02, -1.5702e-03, -5.0815e-03, 1.5744e-02, 5.0113e-03, -3.0807e-03, 6.0631e-03, -1.3878e-02, 3.3491e-03, -4.0196e-02));
    min16float4 pv6_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(0, 2), SZ);
    min16float4 pv6_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(0, 2), SZ);
    min16float4 pv6_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(9.5127e-02, -1.0267e-02, -8.9149e-02, -2.6540e-02, 1.9646e-02, 4.9178e-02, -6.1093e-04, 5.0124e-03, 2.2719e-02, 5.3630e-03, 4.3004e-02, 6.3306e-02, -1.0194e-02, 7.8418e-03, 3.6724e-02, 5.1017e-03));
    r0 += mul(pv6_1, min16float4x4(-6.4515e-02, -5.4602e-02, 2.5284e-01, 1.8322e-02, 4.0429e-02, 2.2233e-02, -7.0544e-02, -7.7931e-03, -7.0869e-02, 1.5078e-02, -5.2847e-03, 1.7098e-02, 1.6356e-02, -6.4047e-03, -5.4841e-02, 5.6371e-03));
    r0 += mul(pv6_2, min16float4x4(1.1505e-01, -3.1445e-02, -1.0465e-02, -3.2545e-02, 4.3678e-02, 7.7509e-02, -6.5923e-01, 1.5811e-02, 4.8263e-02, 4.5008e-02, 1.9558e-03, -2.9534e-01, -1.1704e-01, 5.1535e-02, 6.4336e-02, 1.0367e-01));
    min16float4 pv7_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(1, 2), SZ);
    min16float4 pv7_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(1, 2), SZ);
    min16float4 pv7_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(1.7304e-02, 3.0221e-02, -1.4442e-02, -6.2054e-02, -1.0072e-02, -2.3921e-02, 8.7397e-02, 6.6561e-02, 2.7184e-02, 4.2834e-02, -3.7778e-02, -1.3426e-01, -1.0374e-01, 1.4283e-02, 3.9138e-02, 1.9097e-01));
    r0 += mul(pv7_1, min16float4x4(1.4875e-02, -3.6123e-02, -3.6089e-02, 9.7202e-02, -1.4104e-01, 1.5682e-02, 2.3897e-01, -2.0749e-01, 6.6804e-02, 6.5551e-02, -2.9257e-01, 1.0910e-01, 7.6638e-02, -1.5760e-02, -5.0032e-02, -2.3558e-01));
    r0 += mul(pv7_2, min16float4x4(1.9994e-02, -2.1542e-02, -2.1604e-01, -1.5014e-01, 1.6648e-02, -3.3472e-01, 2.3611e-03, 3.5018e-01, 4.1028e-02, -5.4319e-02, 4.5268e-02, 4.7415e-02, -4.0909e-02, 1.4443e-01, 1.5814e-01, -2.9905e-02));
    min16float4 pv8_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(2, 2), SZ);
    min16float4 pv8_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(2, 2), SZ);
    min16float4 pv8_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(-3.8249e-02, 1.7240e-02, -1.9463e-02, -3.4395e-02, 6.6192e-03, -6.1021e-03, -5.5140e-03, 4.2881e-03, -1.2783e-02, 1.0641e-02, -2.4441e-04, -1.7515e-02, -1.0683e-02, 2.0179e-02, 4.6249e-03, 3.9496e-02));
    r0 += mul(pv8_1, min16float4x4(-1.4395e-02, -3.0916e-02, 1.4343e-02, 5.3033e-02, -4.6316e-02, -1.4151e-01, -4.1065e-02, 3.5183e-01, -4.6152e-02, 7.0586e-02, -3.6562e-01, 5.4585e-02, 1.3713e-02, -3.0259e-02, -2.5168e-02, -2.1940e-02));
    r0 += mul(pv8_2, min16float4x4(-4.5731e-03, 5.8867e-02, -8.3804e-02, -1.1231e-01, 1.5214e-02, 1.6175e-02, 5.3864e-03, -5.9243e-03, 1.6420e-02, 3.0405e-03, -3.0888e-03, -3.0020e-03, -1.0021e-02, 1.3013e-03, 3.9626e-03, 1.4925e-02));
    texResid[p] = r0;
}

//!PASS 7
//!IN texYcgCo, texYPad
//!OUT texBase
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass7(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texBase.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    int2 PSZ = int2((int)GetOutputSize().x / 2 + 6, (int)GetOutputSize().y / 2 + 6);
    uint2 pp = p + uint2(6, 6);
    float4 ycg = BilinearExtrap(texYcgCo, int2((int)GetOutputSize().x / 2, (int)GetOutputSize().y / 2), p);
    float bY = EDI_Base(texYPad, PSZ, 0, pp);
    texBase[p] = float4(bY, ycg.g, ycg.b, ycg.a);
}

//!PASS 8
//!IN texBase, texResid
//!OUT OUTPUT
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass8(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; OUTPUT.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint2 lr = p >> 1;
    int c = 2 * (int)(p.y & 1u) + (int)(p.x & 1u);
    float4 r4 = texResid.Load(int3(int2(lr), 0));
    float rv = c == 0 ? r4.r : (c == 1 ? r4.g : (c == 2 ? r4.b : r4.a));
    float4 base4 = texBase.Load(int3(int2(p), 0));
    float y = clamp(base4.r + rv, 0.0, 1.0);
    float cg = base4.g - 0.5;
    float co = base4.b - 0.5;
    float tmp = y - cg;
    float r = clamp(tmp + co, 0.0, 1.0);
    float g = clamp(y + cg, 0.0, 1.0);
    float b = clamp(tmp - co, 0.0, 1.0);
    OUTPUT[p] = float4(r, g, b, base4.a);
}
