//!MAGPIE EFFECT
//!VERSION 4
// MagpieFX shader generated by magpie_gen.py (nene2x project's own code).
// config: g,3x3_8,3x3_32d,1x1_12,3x3_12,3x3_4
// base upscaler: blurred-bilinear   channels: YCgCo luma   activation: ReLU
//!TEXTURE
Texture2D INPUT;
//!TEXTURE
//!WIDTH INPUT_WIDTH * 2
//!HEIGHT INPUT_HEIGHT * 2
Texture2D OUTPUT;
//!TEXTURE
//!WIDTH INPUT_WIDTH
//!HEIGHT INPUT_HEIGHT
//!FORMAT R16G16B16A16_FLOAT
Texture2D texYcgCo;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texYPad;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texBlurY;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_2;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_3;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_4;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_5;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_6;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_7;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_2;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL3_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL3_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL3_2;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 8
//!HEIGHT INPUT_HEIGHT + 8
//!FORMAT R16G16B16A16_FLOAT
Texture2D texResid;
//!TEXTURE
//!WIDTH INPUT_WIDTH * 2
//!HEIGHT INPUT_HEIGHT * 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texBase;

//!COMMON

float4 LoadClamp(Texture2D<float4> tex, int2 pos, int2 size) {
    pos = clamp(pos, int2(0, 0), size - 1);
    return tex.Load(int3(pos, 0));
}

float4 BilinearExtrap(Texture2D<float4> tex, int2 size, uint2 p) {
    // Chroma/alpha upsample: infer.py's bil_up interpolates with tap weights
    // that go outside [0,1] at the border (linear extrapolation), so border
    // pixels do NOT replicate the edge texel — clamping them would make the
    // edge look clamped one texel early.
    float2 q = (float2(p) - 0.5) * 0.5;
    int2 f = (int2)floor(q);
    int2 i0 = clamp(f, int2(0, 0), size - 2);
    int2 i1 = i0 + 1;
    float2 t = q - (float2)i0;
    float4 a = tex.Load(int3(i0, 0));
    float4 b = tex.Load(int3(int2(i1.x, i0.y), 0));
    float4 c = tex.Load(int3(int2(i0.x, i1.y), 0));
    float4 d = tex.Load(int3(i1, 0));
    return a*(1.0-t.x)*(1.0-t.y) + b*t.x*(1.0-t.y) + c*(1.0-t.x)*t.y + d*t.x*t.y;
}

float Blur1(Texture2D<float4> tex, int2 size, int2 pos, int comp) {
    return 0.25*LoadClamp(tex, pos + int2(0, -1), size)[comp]
         + 0.5 *LoadClamp(tex, pos, size)[comp]
         + 0.25*LoadClamp(tex, pos + int2(0, 1), size)[comp];
}
float Blur(Texture2D<float4> tex, int2 size, int2 pos, int comp) {
    return 0.25*Blur1(tex, size, pos + int2(-1, 0), comp)
         + 0.5 *Blur1(tex, size, pos, comp)
         + 0.25*Blur1(tex, size, pos + int2(1, 0), comp);
}

float BilinearBase(Texture2D<float4> tex, int2 size, int comp, uint2 p) {
    int x = (int)p.x, y = (int)p.y;
    int x0 = (p.x & 1u) == 0u ? x / 2 - 1 : x / 2;
    int x1 = (p.x & 1u) == 0u ? x / 2 : x / 2 + 1;
    int y0 = (p.y & 1u) == 0u ? y / 2 - 1 : y / 2;
    int y1 = (p.y & 1u) == 0u ? y / 2 : y / 2 + 1;
    float wx0 = (p.x & 1u) == 0u ? 0.25 : 0.75;
    float wx1 = (p.x & 1u) == 0u ? 0.75 : 0.25;
    float wy0 = (p.y & 1u) == 0u ? 0.25 : 0.75;
    float wy1 = (p.y & 1u) == 0u ? 0.75 : 0.25;
    int2 c0 = clamp(int2(x0, y0), int2(0, 0), size - 1);
    int2 c1 = clamp(int2(x1, y0), int2(0, 0), size - 1);
    int2 c2 = clamp(int2(x0, y1), int2(0, 0), size - 1);
    int2 c3 = clamp(int2(x1, y1), int2(0, 0), size - 1);
    return wy0*wx0*LoadClamp(tex, c0, size)[comp] + wy0*wx1*LoadClamp(tex, c1, size)[comp]
         + wy1*wx0*LoadClamp(tex, c2, size)[comp] + wy1*wx1*LoadClamp(tex, c3, size)[comp];
}


//!PASS 1
//!IN INPUT
//!OUT texYcgCo
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass1(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texYcgCo.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    float4 c = INPUT.Load(int3(int2(p), 0));
    float y = 0.25*c.r + 0.5*c.g + 0.25*c.b;
    float cg = -0.25*c.r + 0.5*c.g - 0.25*c.b + 0.5;
    float co = 0.5*c.r - 0.5*c.b + 0.5;
    texYcgCo[p] = float4(y, cg, co, c.a);
}

//!PASS 2
//!IN INPUT
//!OUT texYPad
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass2(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texYPad.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    float4 c = LoadClamp(INPUT, int2(p) - int2(4, 4), int2((int)GetInputSize().x, (int)GetInputSize().y));
    float y = 0.25*c.r + 0.5*c.g + 0.25*c.b;
    float cg = -0.25*c.r + 0.5*c.g - 0.25*c.b + 0.5;
    float co = 0.5*c.r - 0.5*c.b + 0.5;
    texYPad[p] = float4(y, cg, co, c.a);
}

//!PASS 3
//!IN texYPad
//!OUT texBlurY
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass3(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texBlurY.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint bw, bh; texBlurY.GetDimensions(bw, bh);
    int2 SZ = int2((int)bw, (int)bh);
    float b0 = Blur(texYPad, SZ, int2(p), 0);
    texBlurY[p] = float4(b0, 0.0, 0.0, 0.0);
}

//!PASS 4
//!IN texYPad
//!OUT texL0_0, texL0_1
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass4(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL0_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL0_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(0.0338336304, 0.0126342373, -0.0135239232, 0.000530741585);
    min16float4 r1 = min16float4(0.000139670301, 0.111394413, 0.000297152146, 0.256383717);
    min16float4 pv0_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(-4.1775e-02, -5.1381e-02, -8.2996e-02, -4.5222e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv0_0, min16float4x4(1.4986e-02, 4.7625e-03, 1.4792e-02, -4.1393e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv1_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(7.7252e-02, 4.9037e-01, 1.9197e-01, 1.3773e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv1_0, min16float4x4(-4.3070e-01, 2.7367e-02, 3.5902e-02, 2.1568e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv2_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(-5.1673e-02, -6.0706e-03, -3.4492e-02, 3.0770e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv2_0, min16float4x4(1.8980e-02, -1.4026e-02, -1.1321e-02, -4.5581e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv3_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(-4.5066e-02, 8.2881e-02, 6.0239e-02, -9.8450e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv3_0, min16float4x4(-1.5012e-02, 1.8805e-01, 2.8135e-01, 5.9404e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv4_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(5.1913e-01, 3.3024e-02, 3.1227e-01, 5.3747e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv4_0, min16float4x4(4.3158e-01, -2.8124e-01, -3.4407e-01, -2.5770e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv5_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(5.2713e-02, 5.3154e-02, -1.0142e-01, -7.4485e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv5_0, min16float4x4(-1.9722e-02, 1.9492e-01, 2.3190e-02, -7.4020e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv6_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(1.2803e-02, -3.1615e-02, 1.1574e-02, 1.2330e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv6_0, min16float4x4(3.0826e-03, 2.0778e-02, 1.0877e-02, -9.6548e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv7_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(1.0550e-02, -1.4819e-03, -6.4428e-02, -4.2059e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv7_0, min16float4x4(-3.4178e-03, -3.2234e-02, 3.4909e-03, 3.3246e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv8_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(-5.5608e-03, -1.4272e-02, 2.8522e-02, 4.3362e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv8_0, min16float4x4(9.9482e-05, 4.1216e-03, -1.4786e-02, 1.0358e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    texL0_0[p] = r0;
    texL0_1[p] = r1;
}

//!PASS 5
//!IN texL0_0, texL0_1
//!OUT texL1_0, texL1_1, texL1_2
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass5(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL1_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL1_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.00706050592, -0.00153453904, 0.00638878113, 0.000112070004);
    min16float4 r1 = min16float4(-0.00176158268, 0.103197232, -7.07690051e-05, -0.0399024785);
    min16float4 r2 = min16float4(0.00481386622, -0.00137869036, 0.00152144011, 0.0852493793);
    min16float4 pv0_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 0), SZ);
    r0.r += -1.5225e-01 * pv0_0_0.r;
    r0.g += -1.6774e-02 * pv0_0_0.r;
    r0.b += 1.4620e-01 * pv0_0_0.r;
    r0.a += 6.4487e-02 * pv0_0_0.r;
    min16float4 pv0_1_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 0), SZ);
    r1.r += 3.2325e-02 * pv0_1_0.g;
    r1.g += -2.6605e-02 * pv0_1_0.g;
    r1.b += -6.7270e-02 * pv0_1_0.g;
    r1.a += -4.1875e-01 * pv0_1_0.g;
    min16float4 pv0_2_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 0), SZ);
    r2.r += -2.7946e-01 * pv0_2_0.b;
    r2.g += -4.0088e-02 * pv0_2_0.b;
    r2.b += -7.6204e-02 * pv0_2_0.b;
    r2.a += 1.9546e-02 * pv0_2_0.b;
    min16float4 pv1_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 0), SZ);
    r0.r += -2.8584e-01 * pv1_0_0.r;
    r0.g += -1.8293e-01 * pv1_0_0.r;
    r0.b += 2.3756e-01 * pv1_0_0.r;
    r0.a += -3.1267e-02 * pv1_0_0.r;
    min16float4 pv1_1_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 0), SZ);
    r1.r += 5.7966e-03 * pv1_1_0.g;
    r1.g += 1.2665e-01 * pv1_1_0.g;
    r1.b += 7.5711e-03 * pv1_1_0.g;
    r1.a += -4.9995e-01 * pv1_1_0.g;
    min16float4 pv1_2_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 0), SZ);
    r2.r += -1.9840e-01 * pv1_2_0.b;
    r2.g += 1.5563e-01 * pv1_2_0.b;
    r2.b += -1.7621e-03 * pv1_2_0.b;
    r2.a += -1.4157e-01 * pv1_2_0.b;
    min16float4 pv2_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 0), SZ);
    r0.r += -4.4199e-02 * pv2_0_0.r;
    r0.g += -1.0811e-01 * pv2_0_0.r;
    r0.b += 4.2589e-02 * pv2_0_0.r;
    r0.a += -3.8024e-02 * pv2_0_0.r;
    min16float4 pv2_1_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 0), SZ);
    r1.r += -9.0289e-02 * pv2_1_0.g;
    r1.g += -3.3024e-02 * pv2_1_0.g;
    r1.b += 2.6890e-03 * pv2_1_0.g;
    r1.a += -7.5572e-01 * pv2_1_0.g;
    min16float4 pv2_2_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 0), SZ);
    r2.r += 1.5921e-01 * pv2_2_0.b;
    r2.g += 2.1681e-01 * pv2_2_0.b;
    r2.b += -2.0616e-02 * pv2_2_0.b;
    r2.a += -9.6599e-02 * pv2_2_0.b;
    min16float4 pv3_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 1), SZ);
    r0.r += 2.1132e-01 * pv3_0_0.r;
    r0.g += -5.2226e-02 * pv3_0_0.r;
    r0.b += -1.9852e-01 * pv3_0_0.r;
    r0.a += -1.5460e-01 * pv3_0_0.r;
    min16float4 pv3_1_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 1), SZ);
    r1.r += -3.8409e-02 * pv3_1_0.g;
    r1.g += -1.3116e-01 * pv3_1_0.g;
    r1.b += 1.9137e-01 * pv3_1_0.g;
    r1.a += -8.4190e-02 * pv3_1_0.g;
    min16float4 pv3_2_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 1), SZ);
    r2.r += -1.1871e-01 * pv3_2_0.b;
    r2.g += 7.8762e-03 * pv3_2_0.b;
    r2.b += 5.3795e-01 * pv3_2_0.b;
    r2.a += -2.1648e-01 * pv3_2_0.b;
    min16float4 pv4_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 1), SZ);
    r0.r += 3.6775e-01 * pv4_0_0.r;
    r0.g += -2.1938e-02 * pv4_0_0.r;
    r0.b += -3.0950e-01 * pv4_0_0.r;
    r0.a += -2.2408e-01 * pv4_0_0.r;
    min16float4 pv4_1_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 1), SZ);
    r1.r += -3.9439e-01 * pv4_1_0.g;
    r1.g += -2.5731e-01 * pv4_1_0.g;
    r1.b += -3.7166e-03 * pv4_1_0.g;
    r1.a += -1.4593e-01 * pv4_1_0.g;
    min16float4 pv4_2_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 1), SZ);
    r2.r += 5.7422e-01 * pv4_2_0.b;
    r2.g += -1.5322e-01 * pv4_2_0.b;
    r2.b += -1.2105e-01 * pv4_2_0.b;
    r2.a += -1.0701e-01 * pv4_2_0.b;
    min16float4 pv5_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 1), SZ);
    r0.r += -1.1855e-02 * pv5_0_0.r;
    r0.g += 3.6851e-02 * pv5_0_0.r;
    r0.b += 5.9819e-03 * pv5_0_0.r;
    r0.a += 3.5904e-01 * pv5_0_0.r;
    min16float4 pv5_1_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 1), SZ);
    r1.r += 4.4374e-01 * pv5_1_0.g;
    r1.g += -1.3302e-02 * pv5_1_0.g;
    r1.b += -8.9285e-03 * pv5_1_0.g;
    r1.a += -5.2899e-01 * pv5_1_0.g;
    min16float4 pv5_2_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 1), SZ);
    r2.r += -4.0201e-01 * pv5_2_0.b;
    r2.g += 2.2522e-01 * pv5_2_0.b;
    r2.b += 1.9758e-01 * pv5_2_0.b;
    r2.a += -2.0833e-02 * pv5_2_0.b;
    min16float4 pv6_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 2), SZ);
    r0.r += -1.9851e-01 * pv6_0_0.r;
    r0.g += 4.3256e-02 * pv6_0_0.r;
    r0.b += 1.6947e-01 * pv6_0_0.r;
    r0.a += 2.0650e-01 * pv6_0_0.r;
    min16float4 pv6_1_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 2), SZ);
    r1.r += -2.7779e-02 * pv6_1_0.g;
    r1.g += 2.0203e-01 * pv6_1_0.g;
    r1.b += -1.3064e-01 * pv6_1_0.g;
    r1.a += -2.4479e-01 * pv6_1_0.g;
    min16float4 pv6_2_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 2), SZ);
    r2.r += 1.4484e-01 * pv6_2_0.b;
    r2.g += 1.2597e-02 * pv6_2_0.b;
    r2.b += 6.7716e-03 * pv6_2_0.b;
    r2.a += -8.4993e-02 * pv6_2_0.b;
    min16float4 pv7_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 2), SZ);
    r0.r += 3.1695e-01 * pv7_0_0.r;
    r0.g += 2.3227e-01 * pv7_0_0.r;
    r0.b += -2.7180e-01 * pv7_0_0.r;
    r0.a += -1.1510e-01 * pv7_0_0.r;
    min16float4 pv7_1_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 2), SZ);
    r1.r += -2.8096e-01 * pv7_1_0.g;
    r1.g += -1.8392e-01 * pv7_1_0.g;
    r1.b += 4.0691e-01 * pv7_1_0.g;
    r1.a += -5.1095e-01 * pv7_1_0.g;
    min16float4 pv7_2_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 2), SZ);
    r2.r += -2.9865e-01 * pv7_2_0.b;
    r2.g += 1.5765e-02 * pv7_2_0.b;
    r2.b += -4.4330e-01 * pv7_2_0.b;
    r2.a += 5.1442e-01 * pv7_2_0.b;
    min16float4 pv8_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 2), SZ);
    r0.r += -1.4513e-01 * pv8_0_0.r;
    r0.g += 7.3966e-02 * pv8_0_0.r;
    r0.b += 1.2446e-01 * pv8_0_0.r;
    r0.a += -6.7430e-02 * pv8_0_0.r;
    min16float4 pv8_1_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 2), SZ);
    r1.r += 3.6650e-01 * pv8_1_0.g;
    r1.g += 3.4484e-01 * pv8_1_0.g;
    r1.b += -3.8413e-01 * pv8_1_0.g;
    r1.a += -4.9732e-01 * pv8_1_0.g;
    min16float4 pv8_2_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 2), SZ);
    r2.r += -1.8810e-01 * pv8_2_0.b;
    r2.g += -4.1066e-01 * pv8_2_0.b;
    r2.b += -8.3391e-02 * pv8_2_0.b;
    r2.a += 5.7285e-02 * pv8_2_0.b;
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    r2 = max(r2, 0.0);
    texL1_0[p] = r0;
    texL1_1[p] = r1;
    texL1_2[p] = r2;
}

//!PASS 6
//!IN texL0_0, texL0_1
//!OUT texL1_3, texL1_4, texL1_5
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass6(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL1_3.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL1_3.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(0.0043444233, 0.000906471512, 4.47476814e-05, 0.00177386438);
    min16float4 r1 = min16float4(0.0046135108, -0.00243744138, 0.00126007502, -2.47636144e-05);
    min16float4 r2 = min16float4(0.0801036134, -0.0261783767, -0.0219320487, 0.106005929);
    min16float4 pv0_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 0), SZ);
    r0.r += 1.7241e-01 * pv0_0_0.a;
    r0.g += 1.1691e-01 * pv0_0_0.a;
    r0.b += -1.6307e-01 * pv0_0_0.a;
    r0.a += 1.9775e-01 * pv0_0_0.a;
    min16float4 pv0_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 0), SZ);
    r1.r += -5.2955e-02 * pv0_1_0.r;
    r1.g += 2.0760e-03 * pv0_1_0.r;
    r1.b += -5.2333e-03 * pv0_1_0.r;
    r1.a += -2.4831e-02 * pv0_1_0.r;
    min16float4 pv0_2_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 0), SZ);
    r2.r += -8.2804e-02 * pv0_2_0.g;
    r2.g += 1.7051e-01 * pv0_2_0.g;
    r2.b += -1.9736e-01 * pv0_2_0.g;
    r2.a += 2.5998e-02 * pv0_2_0.g;
    min16float4 pv1_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 0), SZ);
    r0.r += 2.9445e-01 * pv1_0_0.a;
    r0.g += 5.5610e-01 * pv1_0_0.a;
    r0.b += 9.0468e-02 * pv1_0_0.a;
    r0.a += 1.1533e-01 * pv1_0_0.a;
    min16float4 pv1_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 0), SZ);
    r1.r += -1.4648e-01 * pv1_1_0.r;
    r1.g += -1.9615e-01 * pv1_1_0.r;
    r1.b += 6.0557e-02 * pv1_1_0.r;
    r1.a += -1.8807e-02 * pv1_1_0.r;
    min16float4 pv1_2_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 0), SZ);
    r2.r += 8.5845e-02 * pv1_2_0.g;
    r2.g += -1.7081e-01 * pv1_2_0.g;
    r2.b += -2.4142e-01 * pv1_2_0.g;
    r2.a += -3.7588e-01 * pv1_2_0.g;
    min16float4 pv2_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 0), SZ);
    r0.r += 3.1197e-03 * pv2_0_0.a;
    r0.g += 1.6764e-01 * pv2_0_0.a;
    r0.b += 2.1364e-02 * pv2_0_0.a;
    r0.a += 6.5513e-02 * pv2_0_0.a;
    min16float4 pv2_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 0), SZ);
    r1.r += -7.6706e-02 * pv2_1_0.r;
    r1.g += 4.1357e-04 * pv2_1_0.r;
    r1.b += 2.4786e-03 * pv2_1_0.r;
    r1.a += 4.3200e-02 * pv2_1_0.r;
    min16float4 pv2_2_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 0), SZ);
    r2.r += -9.2349e-03 * pv2_2_0.g;
    r2.g += -6.9325e-02 * pv2_2_0.g;
    r2.b += 6.7241e-04 * pv2_2_0.g;
    r2.a += 1.2021e-01 * pv2_2_0.g;
    min16float4 pv3_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 1), SZ);
    r0.r += 1.6756e-01 * pv3_0_0.a;
    r0.g += 2.0990e-04 * pv3_0_0.a;
    r0.b += 1.9234e-01 * pv3_0_0.a;
    r0.a += 2.2186e-01 * pv3_0_0.a;
    min16float4 pv3_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 1), SZ);
    r1.r += 5.3533e-02 * pv3_1_0.r;
    r1.g += 1.2853e-01 * pv3_1_0.r;
    r1.b += -2.6263e-01 * pv3_1_0.r;
    r1.a += 1.7426e-01 * pv3_1_0.r;
    min16float4 pv3_2_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 1), SZ);
    r2.r += 2.8900e-02 * pv3_2_0.g;
    r2.g += 2.1435e-01 * pv3_2_0.g;
    r2.b += 9.7568e-02 * pv3_2_0.g;
    r2.a += 1.4683e-01 * pv3_2_0.g;
    min16float4 pv4_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 1), SZ);
    r0.r += 1.6706e-01 * pv4_0_0.a;
    r0.g += -4.8206e-01 * pv4_0_0.a;
    r0.b += -2.5603e-01 * pv4_0_0.a;
    r0.a += 1.0028e+00 * pv4_0_0.a;
    min16float4 pv4_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 1), SZ);
    r1.r += 4.7064e-01 * pv4_1_0.r;
    r1.g += -2.6579e-01 * pv4_1_0.r;
    r1.b += 4.7717e-01 * pv4_1_0.r;
    r1.a += 4.8157e-01 * pv4_1_0.r;
    min16float4 pv4_2_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 1), SZ);
    r2.r += -4.0327e-01 * pv4_2_0.g;
    r2.g += 1.1212e-01 * pv4_2_0.g;
    r2.b += -9.2338e-02 * pv4_2_0.g;
    r2.a += -2.1122e-01 * pv4_2_0.g;
    min16float4 pv5_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 1), SZ);
    r0.r += -1.3611e-01 * pv5_0_0.a;
    r0.g += -3.4688e-01 * pv5_0_0.a;
    r0.b += 5.9376e-03 * pv5_0_0.a;
    r0.a += 6.1216e-02 * pv5_0_0.a;
    min16float4 pv5_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 1), SZ);
    r1.r += 1.0074e-02 * pv5_1_0.r;
    r1.g += -1.9534e-01 * pv5_1_0.r;
    r1.b += 1.8184e-02 * pv5_1_0.r;
    r1.a += -7.5865e-02 * pv5_1_0.r;
    min16float4 pv5_2_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 1), SZ);
    r2.r += 5.0658e-02 * pv5_2_0.g;
    r2.g += -1.4117e-01 * pv5_2_0.g;
    r2.b += -8.2441e-02 * pv5_2_0.g;
    r2.a += -4.1435e-01 * pv5_2_0.g;
    min16float4 pv6_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 2), SZ);
    r0.r += -1.0821e-02 * pv6_0_0.a;
    r0.g += -5.3898e-04 * pv6_0_0.a;
    r0.b += -6.7135e-02 * pv6_0_0.a;
    r0.a += -1.0905e-02 * pv6_0_0.a;
    min16float4 pv6_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 2), SZ);
    r1.r += 8.4370e-02 * pv6_1_0.r;
    r1.g += 2.7551e-01 * pv6_1_0.r;
    r1.b += -5.4578e-01 * pv6_1_0.r;
    r1.a += -4.7280e-03 * pv6_1_0.r;
    min16float4 pv6_2_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 2), SZ);
    r2.r += 2.2452e-02 * pv6_2_0.g;
    r2.g += -1.5759e-01 * pv6_2_0.g;
    r2.b += 1.6401e-01 * pv6_2_0.g;
    r2.a += -7.5004e-02 * pv6_2_0.g;
    min16float4 pv7_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(1, 2), SZ);
    r0.r += 1.9811e-02 * pv7_0_0.a;
    r0.g += 5.0447e-02 * pv7_0_0.a;
    r0.b += -1.7673e-01 * pv7_0_0.a;
    r0.a += 3.6221e-02 * pv7_0_0.a;
    min16float4 pv7_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 2), SZ);
    r1.r += 3.3253e-01 * pv7_1_0.r;
    r1.g += -1.6047e-01 * pv7_1_0.r;
    r1.b += 3.3726e-01 * pv7_1_0.r;
    r1.a += -1.3728e+00 * pv7_1_0.r;
    min16float4 pv7_2_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 2), SZ);
    r2.r += 3.0583e-01 * pv7_2_0.g;
    r2.g += 1.1123e-01 * pv7_2_0.g;
    r2.b += -1.9487e-01 * pv7_2_0.g;
    r2.a += 1.7802e-01 * pv7_2_0.g;
    min16float4 pv8_0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(2, 2), SZ);
    r0.r += -5.9113e-02 * pv8_0_0.a;
    r0.g += 3.7718e-03 * pv8_0_0.a;
    r0.b += 6.2930e-02 * pv8_0_0.a;
    r0.a += 1.0780e-02 * pv8_0_0.a;
    min16float4 pv8_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 2), SZ);
    r1.r += 2.0407e-01 * pv8_1_0.r;
    r1.g += 2.6670e-01 * pv8_1_0.r;
    r1.b += -2.1456e-01 * pv8_1_0.r;
    r1.a += -2.5188e-02 * pv8_1_0.r;
    min16float4 pv8_2_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 2), SZ);
    r2.r += -1.6669e-02 * pv8_2_0.g;
    r2.g += 6.4342e-02 * pv8_2_0.g;
    r2.b += -1.5382e-01 * pv8_2_0.g;
    r2.a += -2.8530e-01 * pv8_2_0.g;
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    r2 = max(r2, 0.0);
    texL1_3[p] = r0;
    texL1_4[p] = r1;
    texL1_5[p] = r2;
}

//!PASS 7
//!IN texL0_0, texL0_1
//!OUT texL1_6, texL1_7
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass7(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL1_6.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL1_6.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.00552756339, -0.000260617555, 4.31044173e-05, 0.000166463768);
    min16float4 r1 = min16float4(0.0570833646, 0.0641638711, 0.0155231627, -0.0909994021);
    min16float4 pv0_0_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 0), SZ);
    r0.r += -1.6470e-01 * pv0_0_0.b;
    r0.g += 1.9018e-02 * pv0_0_0.b;
    r0.b += -3.6191e-02 * pv0_0_0.b;
    r0.a += -3.0297e-02 * pv0_0_0.b;
    min16float4 pv0_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 0), SZ);
    r1.r += 1.2699e-01 * pv0_1_0.a;
    r1.g += 3.8103e-02 * pv0_1_0.a;
    r1.b += 1.3550e-01 * pv0_1_0.a;
    r1.a += 1.5811e-01 * pv0_1_0.a;
    min16float4 pv1_0_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 0), SZ);
    r0.r += 3.0041e-01 * pv1_0_0.b;
    r0.g += -1.2141e-01 * pv1_0_0.b;
    r0.b += 3.2767e-01 * pv1_0_0.b;
    r0.a += 8.1975e-02 * pv1_0_0.b;
    min16float4 pv1_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 0), SZ);
    r1.r += 2.7013e-01 * pv1_1_0.a;
    r1.g += -1.5769e-01 * pv1_1_0.a;
    r1.b += -1.4885e-01 * pv1_1_0.a;
    r1.a += 9.7178e-03 * pv1_1_0.a;
    min16float4 pv2_0_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 0), SZ);
    r0.r += 7.1593e-02 * pv2_0_0.b;
    r0.g += 5.0623e-01 * pv2_0_0.b;
    r0.b += 4.0567e-01 * pv2_0_0.b;
    r0.a += 5.4085e-01 * pv2_0_0.b;
    min16float4 pv2_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 0), SZ);
    r1.r += 1.9239e-01 * pv2_1_0.a;
    r1.g += 1.0156e-01 * pv2_1_0.a;
    r1.b += -3.3813e-01 * pv2_1_0.a;
    r1.a += 5.3861e-02 * pv2_1_0.a;
    min16float4 pv3_0_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 1), SZ);
    r0.r += 7.7336e-03 * pv3_0_0.b;
    r0.g += 1.3124e-02 * pv3_0_0.b;
    r0.b += 6.8887e-02 * pv3_0_0.b;
    r0.a += 8.7150e-02 * pv3_0_0.b;
    min16float4 pv3_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 1), SZ);
    r1.r += -1.4904e-01 * pv3_1_0.a;
    r1.g += 2.2944e-01 * pv3_1_0.a;
    r1.b += -3.4608e-01 * pv3_1_0.a;
    r1.a += 7.3145e-02 * pv3_1_0.a;
    min16float4 pv4_0_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 1), SZ);
    r0.r += 1.0449e-01 * pv4_0_0.b;
    r0.g += 5.5549e-02 * pv4_0_0.b;
    r0.b += 5.4025e-01 * pv4_0_0.b;
    r0.a += -2.5112e+00 * pv4_0_0.b;
    min16float4 pv4_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 1), SZ);
    r1.r += -3.9236e-01 * pv4_1_0.a;
    r1.g += 1.1448e-01 * pv4_1_0.a;
    r1.b += -1.0730e-01 * pv4_1_0.a;
    r1.a += 5.1465e-01 * pv4_1_0.a;
    min16float4 pv5_0_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 1), SZ);
    r0.r += -4.9334e-01 * pv5_0_0.b;
    r0.g += 9.2398e-01 * pv5_0_0.b;
    r0.b += -2.3446e-02 * pv5_0_0.b;
    r0.a += 4.1126e-01 * pv5_0_0.b;
    min16float4 pv5_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 1), SZ);
    r1.r += 1.7896e-01 * pv5_1_0.a;
    r1.g += -2.8761e-02 * pv5_1_0.a;
    r1.b += 2.4200e-01 * pv5_1_0.a;
    r1.a += -1.8026e-01 * pv5_1_0.a;
    min16float4 pv6_0_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 2), SZ);
    r0.r += -2.1812e-01 * pv6_0_0.b;
    r0.g += -3.0945e-02 * pv6_0_0.b;
    r0.b += -1.6967e-02 * pv6_0_0.b;
    r0.a += -7.0018e-02 * pv6_0_0.b;
    min16float4 pv6_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 2), SZ);
    r1.r += -2.8620e-01 * pv6_1_0.a;
    r1.g += -5.8347e-02 * pv6_1_0.a;
    r1.b += -5.4903e-01 * pv6_1_0.a;
    r1.a += -3.4749e-02 * pv6_1_0.a;
    min16float4 pv7_0_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 2), SZ);
    r0.r += -8.8954e-02 * pv7_0_0.b;
    r0.g += 5.9232e-02 * pv7_0_0.b;
    r0.b += 5.4490e-02 * pv7_0_0.b;
    r0.a += -5.5662e-02 * pv7_0_0.b;
    min16float4 pv7_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(1, 2), SZ);
    r1.r += 3.3144e-01 * pv7_1_0.a;
    r1.g += -2.9987e-01 * pv7_1_0.a;
    r1.b += 6.9919e-01 * pv7_1_0.a;
    r1.a += -3.4011e-01 * pv7_1_0.a;
    min16float4 pv8_0_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 2), SZ);
    r0.r += -2.4620e-01 * pv8_0_0.b;
    r0.g += 1.9807e-01 * pv8_0_0.b;
    r0.b += 4.4532e-02 * pv8_0_0.b;
    r0.a += 9.7180e-02 * pv8_0_0.b;
    min16float4 pv8_1_0 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(2, 2), SZ);
    r1.r += -1.4821e-02 * pv8_1_0.a;
    r1.g += 1.1492e-01 * pv8_1_0.a;
    r1.b += 3.0408e-01 * pv8_1_0.a;
    r1.a += 1.0560e-01 * pv8_1_0.a;
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    texL1_6[p] = r0;
    texL1_7[p] = r1;
}

//!PASS 8
//!IN texL1_0, texL1_1, texL1_2, texL1_3, texL1_4, texL1_5, texL1_6, texL1_7
//!OUT texL2_0, texL2_1, texL2_2
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass8(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL2_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL2_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.0399731733, 0.00020276288, 0.115708143, -0.000588609895);
    min16float4 r1 = min16float4(-0.00434042234, -0.0453679077, 0.0114473188, -0.0122521222);
    min16float4 r2 = min16float4(-0.0486181937, -0.0426641218, -0.00503375428, -0.0431982614);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_2 = (min16float4)LoadClamp(texL1_2, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_3 = (min16float4)LoadClamp(texL1_3, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_4 = (min16float4)LoadClamp(texL1_4, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_5 = (min16float4)LoadClamp(texL1_5, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_6 = (min16float4)LoadClamp(texL1_6, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_7 = (min16float4)LoadClamp(texL1_7, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(2.8777e-01, 2.8918e-01, -8.7282e-01, 7.4013e-01, 6.9800e-02, -8.7627e-01, -2.4126e+00, 3.9892e-01, -2.4381e-01, 9.1091e-02, 1.9334e-01, -8.5228e-01, -2.8999e-01, -2.9205e-02, 7.4743e-01, 1.0457e-02));
    r0 += mul(pv0_1, min16float4x4(2.8565e-01, 9.1032e-02, -5.8479e-01, 1.4573e-01, -1.1764e-01, -4.2358e-01, -3.6240e-01, -3.6484e-01, -1.4757e-01, 4.3254e-01, 4.2906e-02, -9.8995e-02, 8.8420e-01, 1.4385e-01, 2.6289e-02, -3.5127e-01));
    r0 += mul(pv0_2, min16float4x4(-1.0111e-02, -1.9849e+00, -2.0327e-01, 3.5645e-01, 1.1878e-01, 2.4475e-02, 1.4868e-01, -3.9274e-01, 1.4304e-01, 1.1098e-03, 1.2433e-01, 7.8988e-02, -2.0303e-01, 1.2945e-02, -2.7297e-02, 2.2245e-01));
    r0 += mul(pv0_3, min16float4x4(-6.0496e-01, -7.3531e-01, 2.6129e-01, 6.7923e-01, 6.6775e-01, -1.4428e-01, -7.8519e-01, 1.4193e-01, 4.4398e-01, -8.9415e-01, 4.4499e-01, -1.9326e-01, 9.0306e-01, -3.6995e-02, -6.5136e-02, 8.1960e-02));
    r0 += mul(pv0_4, min16float4x4(-1.7982e-01, 1.3160e-01, 6.1228e-01, -4.6791e-01, -1.4470e-01, -7.4403e-01, -7.4625e-02, 2.3863e-01, 3.3473e-01, 1.3119e-01, -1.3019e+00, -3.3848e-02, -2.6605e-01, 1.5787e-01, 1.0676e+00, 5.1252e-01));
    r0 += mul(pv0_5, min16float4x4(2.2412e-01, 5.6975e-01, -5.0985e-01, 4.5601e-01, 7.0311e-02, -3.1847e-01, 1.1375e-01, 3.1687e-02, 1.7865e-02, -4.8407e-02, 4.2939e-01, -3.5322e-01, -1.5284e-01, 1.6514e+00, -7.8934e-02, -3.7139e-01));
    r0 += mul(pv0_6, min16float4x4(6.5199e-02, 4.6543e-01, -7.2688e-01, -3.2543e-01, -1.6529e-01, 3.5201e-01, 2.7691e-01, -4.1872e-01, 2.2613e-01, -6.4320e-01, -7.3938e-01, 4.2784e-01, 6.6153e-02, 1.3451e+00, 4.9070e-02, -2.4058e-01));
    r0 += mul(pv0_7, min16float4x4(3.7405e-01, 9.0930e-02, -5.9253e-01, 3.5409e-01, 1.1359e-01, -1.9451e-01, 3.8982e-01, -7.7151e-01, 2.1107e-01, -4.8096e-01, -8.7440e-02, 3.5339e-02, 3.5956e-01, 1.9315e-01, -6.8741e-01, 1.2206e-02));
    r1 += mul(pv0_0, min16float4x4(1.1624e-01, 8.4855e-01, 6.7922e-02, 2.2368e-01, -1.9531e-01, 5.6269e-01, -1.2286e+00, 9.6957e-02, 3.2372e-01, -3.1963e-01, -5.4885e-01, -1.5475e-01, 8.9845e-02, -2.4355e-01, 4.9424e-01, 1.8234e-01));
    r1 += mul(pv0_1, min16float4x4(-4.9324e-03, 5.2171e-01, -2.9363e-01, 6.4437e-01, -1.0873e-01, 1.1254e-01, -8.1388e-02, 6.7523e-02, 6.8799e-01, 7.4374e-01, 3.4481e-01, 3.4571e-01, 5.4288e-01, 6.7702e-01, 6.0096e-01, -4.6217e-01));
    r1 += mul(pv0_2, min16float4x4(5.0892e-01, 1.1811e-01, -1.7605e-01, 2.4176e-01, 1.7688e-01, 2.3996e-01, 1.8243e-01, -6.6569e-02, 2.5603e-01, 1.3175e-01, 1.8881e-01, 7.1678e-01, 1.2794e-01, 1.5975e-01, -9.6679e-03, 4.7882e-01));
    r1 += mul(pv0_3, min16float4x4(2.4588e-01, 1.1679e-01, -3.8448e-01, -3.6914e-02, 7.3323e-02, 3.7342e-01, -1.5162e-01, 4.8604e-01, 1.5177e-01, -2.6415e-01, 1.2349e-01, 5.5366e-01, 1.1192e-01, -1.0569e-01, 2.8702e-01, 1.4157e-01));
    r1 += mul(pv0_4, min16float4x4(3.5112e-01, 2.8771e-01, 1.5053e+00, 5.1466e-01, -2.8764e-01, 3.6801e-01, -5.5465e-01, 1.4339e-01, 4.2573e-01, -3.2300e-01, 6.4023e-01, -3.6619e-01, 4.8800e-01, -1.0283e-01, -2.6151e-01, -6.0472e-01));
    r1 += mul(pv0_5, min16float4x4(3.4960e-01, -5.7503e-02, 4.6119e-01, -9.7884e-01, -7.4010e-02, -1.1854e-01, -6.9832e-02, -3.8996e-01, 6.3093e-01, -1.0282e-01, -3.9424e-02, -1.3477e-01, 2.1006e-01, 1.5380e-01, -5.3221e-01, 2.2579e-01));
    r1 += mul(pv0_6, min16float4x4(-1.5153e-01, 1.8913e-01, 5.2504e-01, 8.9436e-02, 7.8758e-01, -1.2272e-01, 9.2375e-02, -4.0833e-01, 4.3080e-01, 3.2629e-01, -3.2536e-01, -3.5967e-01, -4.2203e-02, 1.9653e-01, -3.0085e-01, 4.5649e-01));
    r1 += mul(pv0_7, min16float4x4(2.4625e-01, 3.6855e-01, 1.6314e-01, 2.4222e-01, -6.0394e-01, -1.9905e-01, -8.5995e-01, 1.4479e-01, 1.3644e-01, 3.6990e-01, -2.8892e-01, 2.3719e-01, 1.2751e-02, 1.0181e-01, -1.3773e-01, -6.0627e-02));
    r2 += mul(pv0_0, min16float4x4(7.1238e-02, -6.2461e-01, -3.3223e-01, -5.5243e-01, 1.2361e-01, 1.9567e-02, 2.1882e-01, 5.5711e-02, -3.9440e-01, 3.3650e-01, 4.6729e-01, 1.1767e+00, 1.0891e-01, -4.2343e-01, -2.0028e-01, 1.3167e-01));
    r2 += mul(pv0_1, min16float4x4(2.1555e-01, -1.2873e-01, 3.9957e-02, 2.8560e-01, 2.2901e-01, 3.0137e-01, 1.6775e-02, 7.5933e-01, -4.8724e-01, -5.2599e-01, -8.4039e-02, 7.8797e-01, -1.1324e-01, 1.2187e-01, -9.7762e-01, -1.3365e-01));
    r2 += mul(pv0_2, min16float4x4(2.0298e-01, 3.0867e-01, 2.6873e-01, 1.6894e-01, -4.1970e-01, -2.2321e-01, -1.1283e-01, 2.4666e-01, 3.2213e-01, 1.7422e-01, 4.0954e-01, 7.8399e-04, -3.2294e-01, 1.4472e-01, -9.3759e-02, 1.8273e-01));
    r2 += mul(pv0_3, min16float4x4(-3.2854e-01, 1.6779e-01, 1.1325e-01, 3.0119e-03, 3.5744e-01, 2.6382e-01, 4.1043e-01, 5.7188e-02, 2.4576e-01, 4.8457e-01, 1.0506e-01, -4.9820e-02, 3.4169e-01, -1.0554e-01, 1.7966e-02, 1.8183e-01));
    r2 += mul(pv0_4, min16float4x4(1.9698e-01, -3.7644e-01, 2.2275e-01, 1.8889e-01, -4.6379e-01, 1.1375e-01, -1.8662e-01, 5.1518e-02, 6.4162e-01, 3.1064e-01, 5.1852e-02, 1.9918e-01, 3.4896e-01, 7.0024e-01, 1.8027e-01, 1.8650e-01));
    r2 += mul(pv0_5, min16float4x4(5.5126e-01, -2.2896e-01, -1.5806e-01, -5.1694e-01, 1.4775e-01, -5.5401e-01, -1.3943e-01, -2.8794e-02, -3.9329e-02, 4.9712e-02, -7.2112e-01, 3.2699e-02, 2.6187e-02, -3.8110e-01, 1.3574e-01, 1.0860e-01));
    r2 += mul(pv0_6, min16float4x4(-2.5089e-02, -3.7774e-01, 8.0669e-02, -7.0024e-02, 1.7460e-01, 4.6264e-01, 2.4752e-01, 2.2630e-01, 4.5116e-01, 2.8026e-01, 4.0378e-01, 2.4315e-01, 1.2955e-01, -2.3178e-01, 1.8736e-01, -4.0858e-02));
    r2 += mul(pv0_7, min16float4x4(-1.0770e-02, -1.2431e-01, -2.9018e-02, -4.4253e-01, 1.8958e-01, 3.9523e-01, 6.5591e-01, 5.7617e-01, 6.2246e-02, 2.0459e-01, 1.7294e-01, 1.6582e-01, -2.1106e-01, -8.4255e-02, -2.4939e-01, 3.4656e-01));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    r2 = max(r2, 0.0);
    texL2_0[p] = r0;
    texL2_1[p] = r1;
    texL2_2[p] = r2;
}

//!PASS 9
//!IN texL2_0, texL2_1, texL2_2
//!OUT texL3_0, texL3_1, texL3_2
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass9(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL3_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL3_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.00728208711, -0.00417018402, -0.00117475353, -0.0118926624);
    min16float4 r1 = min16float4(0.00208128057, 0.0110100172, 0.00644959603, -0.0024459674);
    min16float4 r2 = min16float4(0.00750356913, 0.0174946431, -0.0177582316, -0.00424189027);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(1.1322e-01, -6.1365e-02, -1.3673e-01, -2.3710e-05, -5.5110e-02, -2.3213e-02, 1.8690e-02, -3.0752e-02, 1.0015e-01, 7.3838e-02, 1.0629e-01, 4.6518e-02, 2.0558e-01, -2.4852e-02, 1.1041e-01, 1.8436e-03));
    r0 += mul(pv0_1, min16float4x4(4.0352e-02, -1.3560e-01, -2.2344e-02, 8.9068e-02, -3.9971e-01, -1.8557e-02, 5.3130e-03, -6.6428e-03, 4.6505e-02, 1.8948e-01, 7.2955e-02, -2.1538e-03, 1.9762e-01, 2.0770e-01, -5.7552e-02, -1.1988e-02));
    r0 += mul(pv0_2, min16float4x4(1.1511e-01, 9.5498e-02, -3.4152e-02, -5.1357e-02, -1.1408e-02, -4.9433e-02, -6.7891e-02, 2.0826e-02, -1.7036e-01, 1.2236e-01, 5.8188e-02, 1.8249e-02, 1.5520e-01, 3.3673e-02, 5.2917e-02, -5.4796e-02));
    r1 += mul(pv0_0, min16float4x4(1.6791e-02, 1.9902e-02, 2.6273e-02, 3.7773e-02, -9.8881e-02, 3.8569e-02, -1.2048e-01, -8.6772e-02, -3.0636e-02, 6.1454e-02, 4.5062e-02, 4.2184e-02, 5.5703e-02, -6.8761e-03, 1.5763e-02, 4.7329e-02));
    r1 += mul(pv0_1, min16float4x4(9.1681e-02, -3.0052e-03, -7.4964e-02, 5.0141e-02, 1.0261e-02, 3.4018e-02, -1.2933e-02, 4.2418e-02, 3.2132e-02, 3.6543e-02, -5.3606e-02, 2.8969e-02, -1.5817e-03, -7.1241e-02, 2.9227e-02, -1.6773e-02));
    r1 += mul(pv0_2, min16float4x4(5.4160e-02, -4.3280e-02, -4.3144e-02, -4.3681e-02, 7.4255e-02, 9.1689e-02, -2.5125e-02, 1.2847e-01, -9.9234e-02, -3.9916e-02, 2.2529e-02, 2.2230e-02, -4.7011e-02, 2.6449e-02, 1.5351e-01, -5.0207e-02));
    r2 += mul(pv0_0, min16float4x4(1.1750e-01, 9.9764e-02, 2.0563e-01, 4.8235e-02, 4.3481e-02, 6.4746e-02, 2.3205e-03, -7.9926e-02, 1.4006e-01, 1.0726e-01, 5.4743e-03, -1.3447e-01, 6.0783e-02, -2.0845e-02, 1.0733e-01, -2.5044e-02));
    r2 += mul(pv0_1, min16float4x4(-4.2176e-02, -5.0021e-02, -3.8940e-02, -6.7289e-02, -1.6875e-01, 5.0815e-02, -1.6175e-01, 9.1284e-03, 9.5353e-02, -2.7084e-02, -1.8284e-03, -5.2604e-02, 1.4136e-01, -6.9083e-03, 1.4350e-01, 8.5719e-03));
    r2 += mul(pv0_2, min16float4x4(1.5055e-01, -1.1557e-01, -5.4724e-02, -6.5179e-02, -1.7496e-01, 4.0215e-02, -1.1035e-01, 1.6137e-01, -1.5637e-02, 5.1928e-02, -2.6189e-02, -1.0841e-02, 1.0340e-02, 3.1591e-02, 1.5461e-01, 8.6602e-02));
    min16float4 pv1_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(1, 0), SZ);
    min16float4 pv1_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(1, 0), SZ);
    min16float4 pv1_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(3.4787e-01, 2.0684e-01, 1.8879e-01, 8.2892e-02, 3.0657e-02, -7.0300e-02, 5.2707e-01, -7.0950e-04, -7.4197e-01, 4.8055e-02, 1.1997e-01, 1.0301e-01, 2.1212e-02, -2.8896e-01, 3.3224e-02, 6.0028e-02));
    r0 += mul(pv1_1, min16float4x4(5.0325e-02, -1.7011e-01, -3.7511e-02, 2.6905e-01, -2.2323e-01, -2.5313e-01, -1.8341e-01, -6.5086e-03, 1.9104e-01, 2.7512e-02, 3.7214e-02, 1.8738e-02, 8.8647e-02, 1.7546e-01, 7.4163e-02, 3.0222e-02));
    r0 += mul(pv1_2, min16float4x4(-1.1033e-02, 3.0601e-01, 5.5923e-02, -1.5957e-02, -5.9125e-02, 3.7611e-02, -2.6359e-02, -8.3326e-03, -3.3211e-01, 1.1209e-03, -7.4388e-02, -1.1906e-01, 2.5240e-02, 1.4259e-01, 7.9290e-02, -1.7840e-01));
    r1 += mul(pv1_0, min16float4x4(-4.4224e-02, 1.0862e-01, -1.6689e-01, 4.6208e-02, -5.3833e-02, -3.6978e-02, 1.8832e-01, 1.0243e-01, -1.0677e-01, -6.7272e-03, -9.7403e-01, 7.6920e-02, 9.9899e-02, -1.3046e-02, 2.7728e-01, 1.3308e-01));
    r1 += mul(pv1_1, min16float4x4(-5.9065e-02, 1.1119e-01, 1.1723e-01, 1.5283e-01, -3.9744e-02, -1.2499e-01, 6.5384e-02, 2.6892e-02, 1.0812e-01, 3.0910e-02, 2.0674e-01, 5.3787e-02, -3.9122e-02, 1.6736e-01, 7.5348e-02, 3.7689e-02));
    r1 += mul(pv1_2, min16float4x4(4.4169e-02, -5.4520e-02, 1.6351e-01, 1.5571e-02, 1.3009e-01, -1.3252e-02, 3.1366e-01, 8.4899e-03, 6.8133e-02, -5.4377e-02, -2.9505e-02, -1.6950e-02, 1.3132e-01, -9.6156e-02, -2.5796e-01, -1.2016e-01));
    r2 += mul(pv1_0, min16float4x4(1.5905e-02, 2.7226e-02, 6.0971e-02, 2.9037e-01, 2.6985e-02, 1.3529e-01, -1.2358e-01, 5.2806e-02, -3.3610e-01, 1.5251e-02, 1.5520e-02, -7.6028e-01, -6.2839e-02, 7.0348e-02, -9.8340e-02, -7.4191e-02));
    r2 += mul(pv1_1, min16float4x4(2.6904e-02, 1.4267e-01, -1.0783e-01, -1.9108e-01, -1.4965e-02, 4.9332e-03, 2.8214e-02, 7.8078e-02, -4.5830e-02, -4.0408e-02, -2.2159e-02, 2.0619e-01, -1.6304e-01, 1.2451e-01, -2.8139e-03, 1.6131e-01));
    r2 += mul(pv1_2, min16float4x4(-3.7659e-02, 1.3294e-02, 1.0953e-01, -1.4703e-01, -1.4593e-01, -8.6510e-04, -2.7183e-02, 3.5539e-01, 1.3985e-01, -2.5513e-02, -7.4895e-02, -1.5106e-01, -1.1264e-02, -2.1640e-01, 2.6939e-02, -8.7205e-02));
    min16float4 pv2_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(2, 0), SZ);
    min16float4 pv2_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(2, 0), SZ);
    min16float4 pv2_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(-2.2477e-02, 1.9942e-02, -1.0989e-01, 7.1690e-03, 2.5590e-02, -1.8739e-02, -9.6452e-02, -4.3096e-02, -3.6659e-01, -1.8567e-02, -1.5684e-02, -7.9188e-02, 7.4511e-03, 1.8135e-01, 5.2326e-02, 7.1435e-02));
    r0 += mul(pv2_1, min16float4x4(-1.2810e-01, 1.1643e-01, 1.7447e-01, -3.5795e-02, 1.6541e-01, -1.2176e-01, -1.1228e-01, 1.2005e-02, 1.4293e-01, -3.5307e-02, -3.4697e-02, 1.0500e-01, 1.5035e-02, 3.3292e-01, 2.3750e-01, -7.3249e-02));
    r0 += mul(pv2_2, min16float4x4(-1.1183e-01, 3.8219e-02, 2.3357e-02, -2.9615e-02, -3.9399e-01, -6.7247e-02, -2.4363e-01, 5.8568e-02, 1.8723e-01, -1.7895e-01, 3.2617e-02, 1.4416e-01, -5.7420e-02, -1.8131e-01, -1.2749e-01, 1.5834e-01));
    r1 += mul(pv2_0, min16float4x4(-9.2859e-02, 1.5583e-02, -7.2059e-02, 4.3148e-02, -7.4090e-02, -6.2579e-03, -1.6418e-01, -3.5527e-02, 5.5409e-03, -5.3051e-02, -9.9199e-01, -2.7063e-02, 2.5601e-02, 1.3040e-03, 5.3010e-01, 9.7430e-02));
    r1 += mul(pv2_1, min16float4x4(-6.6506e-02, 2.0433e-02, 1.8894e-01, 4.2642e-02, 1.0476e-01, -2.4560e-02, 7.4161e-02, -2.1659e-02, 3.5393e-02, -1.0922e-02, 2.6915e-01, 7.4865e-02, -4.2092e-02, 1.2205e-03, -9.8515e-02, -7.5046e-02));
    r1 += mul(pv2_2, min16float4x4(1.1339e-02, 4.3967e-02, 1.1648e-01, 1.2232e-02, -1.1583e-02, -6.2254e-02, 2.7823e-01, 7.4461e-03, 6.5142e-02, 8.5456e-03, -3.1447e-02, 2.9248e-02, -2.6990e-02, -2.3567e-02, -4.8409e-02, 1.1026e-01));
    r2 += mul(pv2_0, min16float4x4(-8.7190e-02, 1.0779e-02, 5.2686e-02, -6.0858e-02, 2.3424e-02, -2.9729e-02, 9.3211e-03, 4.1244e-02, 1.8083e-03, -5.7788e-02, -5.3186e-02, -6.1461e-01, 1.8989e-01, 1.2732e-01, 1.0638e-01, -2.1714e-02));
    r2 += mul(pv2_1, min16float4x4(1.7240e-01, 2.4101e-02, -4.9946e-02, -1.0428e-01, 1.2722e-03, -5.7666e-03, 4.1784e-02, 1.2562e-01, -4.5293e-02, 7.0909e-02, 1.1176e-02, 8.8138e-02, 2.5640e-01, -8.3309e-02, -2.9104e-02, 2.2885e-02));
    r2 += mul(pv2_2, min16float4x4(-4.1819e-01, 4.8614e-02, -8.7362e-02, -6.2458e-02, 1.2929e-01, -2.6808e-02, 6.3409e-02, -2.2357e-01, -6.9018e-02, -1.9555e-03, -3.3607e-02, -2.9357e-02, -9.7474e-02, 1.0234e-01, 1.0875e-02, -1.1233e-02));
    min16float4 pv3_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(0, 1), SZ);
    min16float4 pv3_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(0, 1), SZ);
    min16float4 pv3_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(-3.1902e-01, -7.0709e-02, 5.4272e-02, -3.1841e-02, 2.7191e-01, -9.0401e-02, 1.9358e-01, 1.5216e-01, -6.7852e-01, -6.4967e-02, 6.4166e-03, -1.6382e-01, 6.0785e-02, -9.5966e-02, 1.5235e-01, -1.4275e-02));
    r0 += mul(pv3_1, min16float4x4(5.7360e-02, -1.9321e-01, -2.3886e-01, 1.6305e-01, 1.0383e-01, -3.0288e-01, 7.2616e-02, -2.9732e-02, 3.6024e-01, 3.1022e-01, 6.0459e-02, 3.4360e-02, -2.1657e-01, 3.6578e-01, -1.9039e-01, -1.7177e-02));
    r0 += mul(pv3_2, min16float4x4(-2.1818e-02, 1.2914e-01, -1.4714e-02, -4.4377e-03, 1.7114e-01, -1.6924e-01, 5.1946e-02, 2.8363e-02, 1.3663e-02, 1.9443e-02, 5.6353e-02, 3.6130e-02, -6.1083e-02, 1.5011e-01, 1.2548e-01, -8.5504e-02));
    r1 += mul(pv3_0, min16float4x4(3.6164e-02, -1.0481e-01, 3.3879e-02, 1.9146e-01, 2.6688e-01, -2.2477e-02, 1.5944e-01, 9.8121e-01, -4.5083e-01, -7.4402e-02, 3.1854e-01, -8.4005e-01, -3.8746e-02, 1.0895e-02, -2.7890e-02, -1.4812e-01));
    r1 += mul(pv3_1, min16float4x4(-1.9090e-01, -5.9421e-02, 5.7836e-02, -8.7457e-02, -6.1261e-02, 1.7552e-01, 5.8250e-02, 4.0414e-02, -5.9923e-02, 3.4534e-02, 9.1994e-03, 4.4979e-02, 1.5134e-01, -1.1167e-01, 1.8108e-02, 6.0258e-02));
    r1 += mul(pv3_2, min16float4x4(7.1641e-02, 3.4977e-02, 6.8075e-02, -1.2286e-02, 8.8613e-02, 6.7748e-02, -2.1613e-02, 2.9724e-01, 8.7329e-02, -6.0747e-02, -3.4249e-02, 2.2211e-01, 3.7318e-01, 4.9224e-02, -2.3922e-03, 1.3920e-01));
    r2 += mul(pv3_0, min16float4x4(2.2805e-02, -7.9160e-02, -2.2889e-01, 1.3673e-01, 5.0809e-01, 3.1145e-01, 2.6823e-02, 2.2652e-01, -2.4684e-01, 4.4309e-01, -5.1152e-01, 4.3414e-01, -1.8509e-01, 3.5820e-03, 1.6387e-02, -3.6394e-02));
    r2 += mul(pv3_1, min16float4x4(1.7365e-01, 1.7350e-01, -6.7453e-02, -7.4323e-02, -1.2449e-01, -9.3614e-02, -2.7946e-01, -7.3797e-02, 9.7390e-02, -5.3552e-02, 2.7291e-01, 2.1597e-01, 2.9172e-01, 4.1499e-02, 1.3779e-01, 5.5730e-02));
    r2 += mul(pv3_2, min16float4x4(2.3211e-01, 3.8775e-03, 2.1029e-01, -6.5448e-02, -1.2695e-01, -2.2366e-01, -1.1211e-01, -1.2351e-01, -3.7541e-01, 8.9958e-02, -1.4692e-02, 3.4761e-02, 8.0494e-03, 7.5643e-03, 1.3702e-01, 1.4461e-01));
    min16float4 pv4_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(1, 1), SZ);
    min16float4 pv4_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(1, 1), SZ);
    min16float4 pv4_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(-3.3606e-01, 7.4638e-02, 3.4848e-03, 1.3092e-01, 1.6047e-01, 9.5059e-02, 2.5958e-01, -2.6597e-01, 2.7579e-01, -1.3876e-01, -5.7986e-02, -8.2285e-02, -4.6608e-02, -1.4053e+00, -1.1416e-01, -1.6771e-02));
    r0 += mul(pv4_1, min16float4x4(-3.8809e-01, 2.9648e-02, -2.2652e-01, 2.6261e-02, -7.7487e-03, -6.3679e-02, 2.4772e-01, 3.9344e-02, 5.5537e-01, 1.2258e-01, 2.8948e-01, 9.9664e-02, -3.1126e-01, -3.8044e-01, -1.4421e-01, 9.5024e-02));
    r0 += mul(pv4_2, min16float4x4(-3.5953e-02, 6.2223e-01, -1.5419e-01, -1.9170e-02, -1.2774e-01, 1.3887e-02, 1.1378e-01, -1.2057e-02, 5.1475e-01, 1.1980e-01, -5.7003e-02, 1.5828e-02, 3.1350e-01, -2.2259e-01, -6.3044e-02, 2.3017e-01));
    r1 += mul(pv4_0, min16float4x4(2.9053e-01, -1.4811e-01, 1.0095e-01, 6.0305e-02, 2.5944e-01, 1.1002e-01, 9.1425e-02, -3.5423e-01, -5.2361e-01, -4.9584e-02, 1.5234e+00, -2.1719e-01, 1.7962e-01, -3.0876e-01, -3.5002e-01, 1.5264e-01));
    r1 += mul(pv4_1, min16float4x4(3.4421e-01, 4.9567e-02, -1.4412e-01, 8.4364e-02, 3.4662e-01, -2.2978e-01, -8.1309e-02, -1.1518e-01, 1.7297e-01, 2.7676e-01, -2.5195e-01, 2.2416e-01, 9.1535e-02, 1.8960e-01, 1.4719e-01, 1.8552e-01));
    r1 += mul(pv4_2, min16float4x4(-2.2728e-03, 1.0187e-01, 4.8170e-02, 3.5286e-02, -7.4466e-02, -8.0067e-02, -1.4698e-02, 1.6915e-01, -3.1115e-01, -8.8217e-02, -2.1416e-01, 2.3646e-02, -2.9833e-01, 8.3498e-02, 2.4778e-01, 2.5869e-01));
    r2 += mul(pv4_0, min16float4x4(1.4156e-01, 3.0637e-01, -7.2252e-01, 1.2189e-01, 2.0315e-01, -2.6105e-02, -3.5901e-01, 3.1325e-02, -1.0408e-01, -1.5466e-01, -1.2245e+00, 1.2166e+00, -5.8292e-01, -9.9680e-02, -4.1431e-01, -7.0557e-01));
    r2 += mul(pv4_1, min16float4x4(-1.9089e-01, 9.1783e-02, 5.1281e-02, 1.2323e-01, -3.9585e-02, 1.5418e-01, -3.0509e-01, -4.3843e-01, -4.3860e-01, 2.7857e-01, 5.0447e-01, -9.2337e-01, -3.5361e-01, 1.3083e-01, 1.2191e-01, 2.8461e-02));
    r2 += mul(pv4_2, min16float4x4(2.3284e-01, 1.0860e-01, 3.9897e-01, 2.1990e-01, -3.8083e-01, 7.4761e-01, -1.0378e-01, 2.2439e-01, 3.1142e-01, -3.7732e-01, 4.7195e-01, 1.1253e-01, -6.9510e-02, -9.4807e-02, -1.3372e-01, 2.3581e-01));
    min16float4 pv5_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(2, 1), SZ);
    min16float4 pv5_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(2, 1), SZ);
    min16float4 pv5_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(-6.9714e-02, -8.3009e-02, -1.7395e-01, 4.7043e-02, 1.9094e-02, -9.6493e-02, -9.5029e-02, 1.1295e-01, -2.4609e-01, 1.6650e-01, 2.4142e-01, 8.1044e-02, 7.2920e-02, 1.1688e-01, 3.7092e-02, 5.4421e-02));
    r0 += mul(pv5_1, min16float4x4(-5.7951e-02, 8.5610e-02, 8.7071e-02, -2.0359e-01, -6.3844e-02, 3.2603e-01, -1.5955e-02, -1.0915e-01, 2.4925e-01, -1.7536e-01, 3.6538e-02, 7.0368e-02, -4.7651e-02, -1.3635e-01, 7.0517e-02, 1.5895e-02));
    r0 += mul(pv5_2, min16float4x4(-6.2933e-02, 3.4018e-01, 2.1467e-01, -5.3426e-02, -2.2921e-01, -6.8943e-02, 4.0247e-01, 1.1411e-01, 9.3504e-02, -3.2581e-01, -4.2751e-02, 3.5520e-01, 8.4481e-02, -4.6149e-01, -5.3187e-02, 4.3922e-01));
    r1 += mul(pv5_0, min16float4x4(-7.4507e-02, 4.1574e-02, 2.2951e-01, 8.0728e-02, 3.3015e-03, -5.4989e-02, 1.9550e-01, 7.2258e-02, -1.8420e-01, -1.0002e-02, 1.1017e-01, 8.9610e-02, 9.1176e-02, 1.3423e-01, -6.8205e-01, -6.7669e-02));
    r1 += mul(pv5_1, min16float4x4(1.3969e-01, 2.1941e-01, 1.1650e-01, -1.4242e-01, -4.5635e-02, -2.6866e-01, -1.2685e-01, -7.9154e-03, 5.7184e-02, -1.1244e-01, -4.0422e-01, -2.6026e-02, 5.9227e-02, 4.0148e-01, 2.4880e-01, 8.2218e-02));
    r1 += mul(pv5_2, min16float4x4(1.0686e-01, 8.6598e-02, -3.1227e-02, -1.0697e-02, 2.1649e-02, -1.0941e-01, -5.0705e-01, 1.4450e-01, 1.1467e-01, -1.2056e-01, -1.5760e-01, 1.5135e-02, 3.2836e-02, -2.6047e-01, -1.2002e-01, 1.3511e-01));
    r2 += mul(pv5_0, min16float4x4(-1.1176e-02, 1.0733e-01, -1.2957e-01, -5.5889e-02, -7.4783e-02, 1.8538e-02, -1.1666e-01, -4.3453e-02, -4.0995e-01, 9.8802e-02, 1.3912e-01, 4.9033e-02, 3.6511e-01, 1.2706e-03, -5.7052e-02, 2.5777e-03));
    r2 += mul(pv5_1, min16float4x4(5.1882e-02, -2.5413e-02, -1.2743e-01, -3.2000e-02, -7.4600e-02, 4.4543e-02, 1.7100e-01, 3.3772e-02, 2.0242e-01, -2.7730e-02, 1.6266e-01, 1.2105e-01, 5.7579e-02, 7.0694e-02, -5.0330e-03, 7.7188e-02));
    r2 += mul(pv5_2, min16float4x4(-5.5332e-01, 1.4828e-02, 3.1488e-01, 9.6216e-02, -7.6225e-02, 6.0346e-02, -1.5825e-01, 9.7026e-02, -2.1941e-01, -7.8460e-02, 2.8448e-01, 3.8653e-02, 2.9362e-01, 5.1328e-03, -1.4176e-01, -7.2554e-02));
    min16float4 pv6_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(0, 2), SZ);
    min16float4 pv6_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(0, 2), SZ);
    min16float4 pv6_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(1.4379e-01, -2.5365e-01, -2.9163e-02, 1.1169e-01, -9.8141e-02, 6.1908e-02, -2.8691e-02, -1.1652e-01, 2.8916e-01, -4.6366e-01, 6.4112e-02, -4.0915e-01, 8.5004e-02, -1.2814e-01, 1.5074e-02, -1.7269e-02));
    r0 += mul(pv6_1, min16float4x4(-1.6328e-01, 2.7122e-01, -2.7319e-02, -9.7380e-02, 1.2971e-01, -4.6075e-01, 4.6086e-02, 7.1760e-02, 1.3783e-01, 1.4318e-01, -5.1484e-03, 3.6204e-02, -2.0901e-01, 3.0712e-01, -1.1678e-02, 2.2630e-02));
    r0 += mul(pv6_2, min16float4x4(-2.5502e-01, -2.6109e-02, 1.1907e-02, 8.6490e-03, -2.3169e-01, 4.3510e-02, -2.7518e-02, 1.6365e-01, 9.9621e-02, -8.0114e-02, 2.8398e-02, 2.3806e-03, 1.1130e-01, 1.4816e-01, -1.8563e-02, 5.3189e-02));
    r1 += mul(pv6_0, min16float4x4(1.6394e-01, 3.5075e-01, -4.4007e-02, 6.7061e-02, 6.4153e-02, 7.5490e-02, -7.7298e-02, 2.3481e-01, -2.8179e-02, -2.0726e-01, -4.8149e-02, 1.5936e-01, -2.6695e-03, -3.6975e-02, 1.2608e-02, 3.0186e-02));
    r1 += mul(pv6_1, min16float4x4(-9.4330e-03, -1.0607e-01, -1.5324e-02, 2.3827e-01, -5.0796e-02, 2.0342e-01, -5.0690e-02, -9.2514e-02, -9.1777e-03, -1.4207e-01, 4.3270e-02, -1.7392e-01, 2.2259e-01, -3.0398e-01, 1.4711e-02, 1.9893e-01));
    r1 += mul(pv6_2, min16float4x4(1.2558e-01, -1.0349e-01, -1.9001e-02, 4.7794e-02, 1.8969e-01, 2.5814e-01, -3.2946e-02, -3.0901e-01, -5.3218e-02, 5.5966e-03, -6.4028e-04, -8.2257e-02, 2.4480e-01, -1.3378e-01, -8.9112e-03, -5.0297e-02));
    r2 += mul(pv6_0, min16float4x4(-1.1570e-01, 6.0335e-02, 5.7247e-02, -3.7846e-02, 5.1925e-02, 7.2367e-02, -1.1021e-01, -7.6562e-02, -1.9860e-01, 1.2060e-01, 3.8878e-03, -1.3792e-01, -2.6657e-02, 3.3360e-03, 1.7019e-01, 5.9568e-02));
    r2 += mul(pv6_1, min16float4x4(1.4670e-01, 3.6643e-02, -1.6572e-01, -3.4588e-02, -1.0732e-01, 1.8048e-02, 6.0296e-02, -9.8658e-02, -7.7950e-02, -1.3207e-02, 7.0551e-03, 1.2241e-02, 1.4180e-01, 4.5923e-02, -1.7034e-01, 3.9160e-02));
    r2 += mul(pv6_2, min16float4x4(1.2394e-01, -1.9659e-02, -1.2586e-01, 2.8117e-02, -3.7547e-02, 2.3098e-02, -4.9034e-03, -3.9430e-02, -1.1352e-01, 4.0551e-02, 1.8257e-01, -4.0411e-02, -2.4253e-02, -2.1466e-02, -4.4555e-02, 6.2699e-02));
    min16float4 pv7_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(1, 2), SZ);
    min16float4 pv7_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(1, 2), SZ);
    min16float4 pv7_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(4.5859e-02, -3.9274e-02, 1.6341e-03, 8.5183e-02, 8.5315e-02, -5.4747e-02, 1.0058e-02, 2.0606e-01, 1.5870e-01, -1.6001e-01, 6.8770e-02, -1.4021e-02, 1.1432e-01, -1.4760e-01, 7.1213e-02, 1.1207e-01));
    r0 += mul(pv7_1, min16float4x4(-3.9894e-03, 2.4246e-01, 5.2611e-02, 2.4677e-01, 2.5380e-02, 7.6555e-02, -1.5454e-01, 1.6464e-01, 3.1471e-02, -1.0923e-01, -5.4795e-02, -5.3363e-02, -1.7218e-01, -7.1244e-02, 7.5857e-02, 2.6273e-02));
    r0 += mul(pv7_2, min16float4x4(-2.4557e-01, -1.9640e-02, -9.4293e-03, 5.1837e-02, -3.7033e-01, -2.0486e-01, 1.0751e-02, -4.5390e-02, 1.2959e-01, 3.8313e-01, 1.0371e-01, -9.1471e-02, 4.5273e-02, -4.4331e-01, 1.5147e-02, -2.0827e-01));
    r1 += mul(pv7_0, min16float4x4(3.0891e-01, -1.9949e-01, -6.2937e-02, 8.3617e-02, 4.1065e-01, 3.3532e-01, -1.0230e-02, 8.0124e-02, 4.6131e-01, -4.4135e-01, 9.2946e-02, 2.6674e-01, 5.3683e-02, -8.5577e-01, 1.3125e-01, -1.9597e-01));
    r1 += mul(pv7_1, min16float4x4(2.8902e-01, -3.7486e-01, 6.4229e-02, 1.2587e-02, -6.9321e-02, -7.4355e-02, -4.8530e-02, 1.6095e-02, -1.3818e-01, 6.5727e-01, -2.4631e-02, -1.2035e-01, 7.7554e-02, 3.8737e-02, 3.5207e-02, -3.6304e-03));
    r1 += mul(pv7_2, min16float4x4(-9.5573e-02, -2.4938e-02, 8.2121e-02, 9.5094e-02, -9.3821e-02, -6.9918e-02, 1.2338e-01, -1.4324e-01, 1.8830e-02, 1.0875e-01, -4.6645e-02, -1.5895e-01, -3.1033e-02, 3.2577e-01, 9.8448e-02, 1.1519e-01));
    r2 += mul(pv7_0, min16float4x4(9.4196e-03, -9.2268e-03, 1.9213e-01, -7.2158e-02, 4.9996e-03, -1.3338e-02, -3.9710e-03, -9.6055e-02, -6.7777e-02, -1.1921e-01, 6.9793e-01, 2.2656e-01, 1.6664e-01, 1.7340e-02, 1.9590e-01, 1.9025e-01));
    r2 += mul(pv7_1, min16float4x4(-2.0795e-01, 6.6631e-02, 3.2882e-01, 2.0488e-02, 6.0329e-02, 5.2570e-02, -1.4812e-01, 1.6728e-01, 1.0596e-01, -3.5687e-02, -6.1089e-01, 7.0825e-02, -5.9736e-02, -6.5654e-03, -1.9665e-01, -1.4028e-01));
    r2 += mul(pv7_2, min16float4x4(2.1825e-02, 5.2718e-02, 1.3511e-01, 1.0126e-01, -2.0660e-01, -1.0616e-01, 4.2413e-01, 9.4574e-02, 1.6177e-01, -2.3240e-01, -7.9371e-02, 2.3987e-01, 2.1592e-06, -7.3052e-02, -2.5586e-01, -8.0399e-02));
    min16float4 pv8_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(2, 2), SZ);
    min16float4 pv8_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(2, 2), SZ);
    min16float4 pv8_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(2.6473e-03, 6.3679e-03, -3.4048e-02, 5.2802e-02, 8.9470e-03, -1.9771e-02, -2.4417e-02, -3.1271e-02, -7.5452e-02, 1.9540e-01, -5.0587e-02, 1.0700e-01, -1.9556e-02, -1.3061e-02, -8.0556e-02, 1.0509e-01));
    r0 += mul(pv8_1, min16float4x4(-2.4164e-02, -8.4465e-02, 7.2972e-02, -5.9704e-03, -2.8043e-02, 2.6342e-01, -2.5255e-02, 7.0641e-02, 2.0265e-01, 8.1447e-02, -2.2877e-02, -9.4959e-03, -3.7399e-02, -2.2335e-02, 1.4486e-02, -7.5878e-02));
    r0 += mul(pv8_2, min16float4x4(-1.3743e-01, 9.3811e-02, 7.8595e-02, 1.6332e-03, 3.3349e-02, 2.9100e-01, 1.6726e-02, -7.1489e-02, 2.6303e-02, -1.6821e-01, -4.1218e-02, -2.5253e-02, 3.0672e-02, -1.2847e-01, -1.4691e-02, 1.4877e-02));
    r1 += mul(pv8_0, min16float4x4(1.7664e-01, -9.5597e-02, -1.2554e-03, -5.6254e-02, 1.8760e-02, -1.6829e-01, 1.8813e-03, -2.1917e-02, 3.0734e-01, 2.8314e-01, 1.0898e-01, -1.0295e-01, -6.5697e-02, 2.5144e-03, 1.3374e-02, 5.9741e-02));
    r1 += mul(pv8_1, min16float4x4(2.8579e-02, 3.1408e-01, -4.8289e-02, 9.9451e-03, -5.7473e-02, 1.3735e-02, -3.1532e-03, 9.6299e-02, -5.7510e-02, -2.4711e-01, 4.6007e-02, -2.3580e-02, -1.5811e-02, -1.9726e-01, -4.9024e-02, 5.5816e-03));
    r1 += mul(pv8_2, min16float4x4(-8.9934e-02, 3.0543e-01, -3.2703e-03, 1.1570e-01, -2.2153e-02, 9.2636e-02, 4.3740e-02, -6.8690e-02, 6.9042e-03, -2.9089e-01, 1.5893e-02, -1.4554e-01, 4.9182e-02, -3.0378e-01, 4.7854e-02, -6.3632e-02));
    r2 += mul(pv8_0, min16float4x4(6.5993e-02, -6.2804e-02, -1.1992e-03, -2.4176e-02, 1.9133e-03, -8.0526e-03, 6.2108e-02, 1.9149e-03, 7.5751e-02, -4.8092e-02, -1.9060e-01, 1.2713e-01, 3.9366e-02, -1.7827e-02, -5.0678e-03, 7.3859e-02));
    r2 += mul(pv8_1, min16float4x4(-1.3520e-02, 8.6104e-04, 8.7864e-03, -1.4124e-02, -4.2382e-02, 1.1833e-01, 3.3443e-02, 6.8544e-02, -1.0872e-02, -2.1958e-02, -6.7821e-02, 8.4882e-03, 3.8253e-02, 3.7424e-02, -1.7840e-01, -9.6159e-02));
    r2 += mul(pv8_2, min16float4x4(-1.3007e-01, 1.8584e-01, 2.2094e-01, 3.2386e-02, 1.1342e-01, -6.5350e-03, 4.8938e-03, 5.6678e-02, -7.3554e-02, -1.9871e-01, -1.4767e-01, -2.7801e-02, 1.0481e-02, -6.2327e-02, 3.3508e-02, 1.9292e-02));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    r2 = max(r2, 0.0);
    texL3_0[p] = r0;
    texL3_1[p] = r1;
    texL3_2[p] = r2;
}

//!PASS 10
//!IN texL3_0, texL3_1, texL3_2
//!OUT texResid
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass10(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texResid.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texResid.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.000854618207, -0.000973260554, -0.00466831867, -0.004738722);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL3_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL3_1, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_2 = (min16float4)LoadClamp(texL3_2, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(-5.9748e-02, 1.7178e-02, 9.8960e-03, 1.8521e-02, 1.0503e-02, 1.3181e-02, 1.9181e-02, 2.5707e-02, 6.0852e-03, 9.5738e-03, 3.1609e-02, -2.6105e-03, -1.0729e-01, -1.8538e-01, 6.1551e-02, -1.4622e-02));
    r0 += mul(pv0_1, min16float4x4(1.3177e-02, -2.7053e-03, 5.4454e-02, 6.8078e-03, 5.0622e-01, -2.5106e-01, 3.6487e-02, -1.3001e-01, 1.5675e-02, -1.5583e-02, 1.9173e-04, -2.5621e-03, 2.5009e-02, 2.2724e-02, -5.2011e-02, -1.0773e-02));
    r0 += mul(pv0_2, min16float4x4(3.7672e-02, 4.4659e-03, -1.9440e-03, -4.3080e-03, 2.5712e-02, 4.2244e-02, -1.5198e-02, 3.1620e-02, 4.5632e-02, -6.4574e-02, 2.7207e-02, -1.0927e-03, 1.8194e-02, -1.1710e-02, 7.0999e-03, 8.5714e-03));
    min16float4 pv1_0 = (min16float4)LoadClamp(texL3_0, int2(p) + int2(1, 0), SZ);
    min16float4 pv1_1 = (min16float4)LoadClamp(texL3_1, int2(p) + int2(1, 0), SZ);
    min16float4 pv1_2 = (min16float4)LoadClamp(texL3_2, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(1.5467e-01, -5.8004e-02, -9.1155e-02, -6.5245e-03, -3.7904e-01, 5.0612e-01, -4.1073e-02, -6.8630e-02, -4.0239e-02, -1.8265e-02, 7.2811e-03, -2.7984e-03, 1.0166e-01, 1.7658e-01, 1.0397e-01, 2.5778e-01));
    r0 += mul(pv1_1, min16float4x4(1.5118e-01, 2.6685e-01, 6.5708e-02, 1.2443e-01, 5.2768e-01, -8.2144e-01, 4.2294e-01, -3.7910e-01, -1.8968e-02, -4.7338e-03, -9.3893e-03, 5.7864e-04, -1.9542e-01, -7.1102e-02, -1.2037e-01, -1.4084e-01));
    r0 += mul(pv1_2, min16float4x4(-1.0075e-01, 1.7777e-02, 7.4322e-02, 4.2593e-02, 2.5464e-01, 2.9960e-02, 7.8313e-02, 3.1675e-02, 8.1201e-02, 1.3367e-01, -1.3924e-01, -9.7470e-02, -1.3566e-01, 5.7645e-02, 9.1904e-02, -2.4209e-02));
    min16float4 pv2_0 = (min16float4)LoadClamp(texL3_0, int2(p) + int2(2, 0), SZ);
    min16float4 pv2_1 = (min16float4)LoadClamp(texL3_1, int2(p) + int2(2, 0), SZ);
    min16float4 pv2_2 = (min16float4)LoadClamp(texL3_2, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(-2.0368e-02, 5.7813e-02, -1.6494e-02, -8.8547e-03, 7.6655e-02, -1.7995e-01, 7.5206e-02, 7.9039e-03, 2.5452e-03, 1.0211e-02, 8.8615e-03, 4.5429e-02, -5.3830e-02, -1.9408e-02, 2.3870e-03, 1.2841e-01));
    r0 += mul(pv2_1, min16float4x4(-6.5306e-02, -6.0304e-02, -2.5281e-02, -3.0611e-02, -9.0385e-02, 1.2159e-01, -6.9635e-02, 6.9268e-02, -1.7527e-02, -8.0679e-03, -2.8250e-03, -3.4650e-04, 4.8664e-02, -7.4944e-02, -8.1472e-03, -2.5807e-01));
    r0 += mul(pv2_2, min16float4x4(-1.4162e-02, 8.7255e-02, -1.0189e-03, -6.7132e-02, 5.5491e-02, 1.2978e-01, 1.2200e-02, 1.3398e-01, -5.2958e-02, 2.5210e-02, -5.1051e-04, -4.4528e-02, 1.3783e-02, -9.3391e-02, 9.5224e-03, 2.8086e-02));
    min16float4 pv3_0 = (min16float4)LoadClamp(texL3_0, int2(p) + int2(0, 1), SZ);
    min16float4 pv3_1 = (min16float4)LoadClamp(texL3_1, int2(p) + int2(0, 1), SZ);
    min16float4 pv3_2 = (min16float4)LoadClamp(texL3_2, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(1.9035e-01, -4.7859e-02, -1.4948e-01, 3.3527e-02, 3.3788e-01, -1.6711e-01, 5.9270e-02, -1.4891e-01, 4.1160e-01, -2.2645e-01, 5.6291e-02, -1.6156e-01, -5.1718e-01, -1.2949e-01, -7.1678e-01, -2.1776e-01));
    r0 += mul(pv3_1, min16float4x4(1.5854e-01, -2.9523e-02, 1.6369e-01, -5.0553e-02, -4.0708e-02, -1.2994e-01, 3.8476e-01, -2.2029e-01, 1.2421e-01, -5.7420e-03, -1.9661e-02, -4.8097e-02, -1.1044e-02, 1.1680e-01, 2.3610e-02, 1.0001e-01));
    r0 += mul(pv3_2, min16float4x4(1.0751e-01, -1.2455e-01, 1.2819e-01, -1.0222e-01, -1.5833e-01, -5.7218e-02, 1.3384e-01, 6.0507e-02, -3.5177e-01, 3.1007e-02, 4.2185e-01, -1.1878e-01, -2.3853e-03, 3.7593e-02, 2.0975e-02, -4.1653e-03));
    min16float4 pv4_0 = (min16float4)LoadClamp(texL3_0, int2(p) + int2(1, 1), SZ);
    min16float4 pv4_1 = (min16float4)LoadClamp(texL3_1, int2(p) + int2(1, 1), SZ);
    min16float4 pv4_2 = (min16float4)LoadClamp(texL3_2, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(-9.0935e-01, 1.8272e-02, 7.1535e-01, 6.5822e-02, -9.2400e-01, 6.5185e-01, -1.0933e+00, 1.3686e+00, -3.5986e-01, 1.2839e-01, -1.8428e-01, 4.6420e-01, 2.2645e-02, -1.2805e-01, -1.5591e-01, -4.8754e-01));
    r0 += mul(pv4_1, min16float4x4(3.4812e-01, 4.6522e-01, 5.7805e-01, 5.8703e-01, 1.6524e-03, 1.7545e-01, -2.1066e-02, -2.1532e-01, -2.0819e-02, 1.9166e-01, -8.8584e-02, -2.8957e-02, -2.5982e-02, -4.4116e-01, 4.6064e-02, -3.3821e-01));
    r0 += mul(pv4_2, min16float4x4(-8.0802e-01, 1.0824e+00, -9.5243e-01, 6.6475e-01, 1.3481e-01, -1.5088e-01, 3.9119e-01, 4.8883e-01, -1.1698e+00, -1.2895e+00, 9.9039e-01, 1.4577e+00, 6.1307e-01, 1.0033e-01, -5.7334e-01, -2.4344e-01));
    min16float4 pv5_0 = (min16float4)LoadClamp(texL3_0, int2(p) + int2(2, 1), SZ);
    min16float4 pv5_1 = (min16float4)LoadClamp(texL3_1, int2(p) + int2(2, 1), SZ);
    min16float4 pv5_2 = (min16float4)LoadClamp(texL3_2, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(1.3220e-01, -3.5984e-01, 2.2429e-02, 2.6293e-01, 1.5183e-01, -1.6026e-01, 1.7324e-01, -3.0222e-01, 1.0906e-01, -5.8726e-02, 9.9832e-02, -7.1988e-02, 2.8461e-01, 2.2879e-01, 9.5577e-02, -7.1059e-02));
    r0 += mul(pv5_1, min16float4x4(-1.6350e-01, -1.4614e-01, -6.9006e-02, 1.1383e-01, 1.0977e-02, -3.8558e-02, 3.7667e-02, -1.6438e-02, 4.5418e-02, -5.7440e-03, 2.7230e-02, -2.3135e-02, -5.2141e-01, -5.4501e-01, -1.8363e-01, 1.7772e-01));
    r0 += mul(pv5_2, min16float4x4(7.7774e-02, -2.0589e-01, 2.7865e-02, 6.0024e-02, 1.1556e-01, 4.3833e-01, -3.3144e-02, -2.3404e-01, 6.1825e-03, -1.7354e-01, -2.0003e-02, 1.3119e-01, -1.0497e-01, 1.9682e-01, -4.9283e-02, -1.3727e-01));
    min16float4 pv6_0 = (min16float4)LoadClamp(texL3_0, int2(p) + int2(0, 2), SZ);
    min16float4 pv6_1 = (min16float4)LoadClamp(texL3_1, int2(p) + int2(0, 2), SZ);
    min16float4 pv6_2 = (min16float4)LoadClamp(texL3_2, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(-7.0734e-02, -9.3603e-03, 7.0595e-02, 2.2452e-02, -5.4269e-02, -4.5769e-02, 1.5097e-01, -2.8972e-02, -9.0699e-02, -4.0620e-02, 3.3540e-01, -2.2236e-01, -2.0784e-02, -6.8610e-02, -4.8059e-02, -6.0442e-02));
    r0 += mul(pv6_1, min16float4x4(7.7749e-02, 8.2464e-02, 1.1246e-01, 9.4395e-02, 6.1241e-02, -6.2597e-03, 4.4966e-02, 1.9406e-02, 1.9332e-01, 9.3484e-02, -3.1845e-01, 1.6883e-02, 3.2970e-02, 1.8855e-02, 2.6711e-02, 3.4508e-03));
    r0 += mul(pv6_2, min16float4x4(1.0487e-02, 9.7607e-03, -3.6634e-02, 2.7621e-02, -2.8960e-01, -2.1456e-01, -4.2979e-01, -2.1374e-01, 5.7651e-02, -2.2006e-02, -8.4390e-02, -1.0549e-02, -1.2066e-01, 6.0612e-03, 1.1511e-01, -1.8651e-02));
    min16float4 pv7_0 = (min16float4)LoadClamp(texL3_0, int2(p) + int2(1, 2), SZ);
    min16float4 pv7_1 = (min16float4)LoadClamp(texL3_1, int2(p) + int2(1, 2), SZ);
    min16float4 pv7_2 = (min16float4)LoadClamp(texL3_2, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(6.9900e-02, -1.6835e-01, -6.5655e-02, 2.4354e-01, -8.3133e-02, 9.6671e-02, -1.3304e-02, -4.1135e-02, 3.5279e-01, 3.1705e-01, -2.4816e-01, -3.2271e-01, 2.8101e-01, 2.5076e-01, 9.2105e-02, 4.8442e-02));
    r0 += mul(pv7_1, min16float4x4(-2.0855e-01, -1.9863e-01, -1.3170e-01, -5.6194e-02, -7.9170e-02, -3.1703e-02, 3.4956e-02, -8.3194e-03, 1.2110e-01, 2.8872e-01, -3.6217e-02, -3.5352e-01, 1.3073e-01, 1.5426e-01, -1.1513e-02, -2.5739e-02));
    r0 += mul(pv7_2, min16float4x4(1.9076e-02, -1.0225e-01, -9.8204e-02, 1.9296e-01, -1.9495e-01, -1.6692e-01, -1.4260e-01, -2.7773e-01, 3.3726e-02, 1.1126e-01, -1.2029e-01, -5.6127e-02, -1.5452e-01, -1.4026e-01, 7.3775e-02, 2.1360e-01));
    min16float4 pv8_0 = (min16float4)LoadClamp(texL3_0, int2(p) + int2(2, 2), SZ);
    min16float4 pv8_1 = (min16float4)LoadClamp(texL3_1, int2(p) + int2(2, 2), SZ);
    min16float4 pv8_2 = (min16float4)LoadClamp(texL3_2, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(8.4538e-03, 1.2030e-01, -2.3949e-03, -1.5431e-01, -1.9876e-02, -2.5353e-03, -2.6466e-02, 7.6311e-02, 2.6322e-02, -1.9950e-02, -4.2713e-02, -1.0317e-02, -5.1018e-02, -1.7615e-02, -2.1589e-02, 7.9637e-03));
    r0 += mul(pv8_1, min16float4x4(2.8480e-02, 2.8422e-02, 1.8536e-02, -1.2390e-02, 2.2949e-04, -1.6660e-02, 2.6218e-03, -1.0161e-02, 1.9001e-02, -1.1914e-02, -7.7406e-03, -2.1508e-02, 6.0406e-02, 7.1093e-02, 7.1625e-02, 2.3865e-02));
    r0 += mul(pv8_2, min16float4x4(4.6861e-03, 6.3870e-02, 2.3502e-03, -1.2651e-01, -1.1254e-01, -1.9969e-01, -6.7793e-02, -1.9560e-02, 1.8743e-02, -5.6107e-03, 1.9637e-03, -4.6208e-02, -1.9352e-02, -8.0275e-02, 2.6400e-02, 1.9112e-02));
    texResid[p] = r0;
}

//!PASS 11
//!IN texYcgCo, texYPad, texBlurY
//!OUT texBase
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass11(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texBase.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    int2 PSZ = int2((int)GetOutputSize().x / 2 + 8, (int)GetOutputSize().y / 2 + 8);
    uint2 pp = p + uint2(8, 8);
    float4 ycg = BilinearExtrap(texYcgCo, int2((int)GetOutputSize().x / 2, (int)GetOutputSize().y / 2), p);
    float bY = BilinearBase(texBlurY, PSZ, 0, pp);
    texBase[p] = float4(bY, ycg.g, ycg.b, ycg.a);
}

//!PASS 12
//!IN texBase, texResid
//!OUT OUTPUT
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass12(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; OUTPUT.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint2 lr = p >> 1;
    int c = 2 * (int)(p.y & 1u) + (int)(p.x & 1u);
    float4 r4 = texResid.Load(int3(int2(lr), 0));
    float rv = c == 0 ? r4.r : (c == 1 ? r4.g : (c == 2 ? r4.b : r4.a));
    float4 base4 = texBase.Load(int3(int2(p), 0));
    float y = clamp(base4.r + rv, 0.0, 1.0);
    float cg = base4.g - 0.5;
    float co = base4.b - 0.5;
    float tmp = y - cg;
    float r = clamp(tmp + co, 0.0, 1.0);
    float g = clamp(y + cg, 0.0, 1.0);
    float b = clamp(tmp - co, 0.0, 1.0);
    OUTPUT[p] = float4(r, g, b, base4.a);
}
