//!MAGPIE EFFECT
//!VERSION 4
// MagpieFX shader generated by magpie_gen.py (nene2x project's own code).
// config: 3x3_8,1x1_4,3x3_10,3x3_6,1x1_4n
// base upscaler: EDI   channels: YCgCo luma   activation: ReLU
//!TEXTURE
Texture2D INPUT;
//!TEXTURE
//!WIDTH INPUT_WIDTH * 2
//!HEIGHT INPUT_HEIGHT * 2
Texture2D OUTPUT;
//!TEXTURE
//!WIDTH INPUT_WIDTH
//!HEIGHT INPUT_HEIGHT
//!FORMAT R16G16B16A16_FLOAT
Texture2D texYcgCo;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texYPad;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL2_2;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL3_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL3_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 6
//!HEIGHT INPUT_HEIGHT + 6
//!FORMAT R16G16B16A16_FLOAT
Texture2D texResid;
//!TEXTURE
//!WIDTH INPUT_WIDTH * 2
//!HEIGHT INPUT_HEIGHT * 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texBase;

//!COMMON

float4 LoadClamp(Texture2D<float4> tex, int2 pos, int2 size) {
    pos = clamp(pos, int2(0, 0), size - 1);
    return tex.Load(int3(pos, 0));
}

float4 BilinearExtrap(Texture2D<float4> tex, int2 size, uint2 p) {
    // Chroma/alpha upsample: infer.py's bil_up interpolates with tap weights
    // that go outside [0,1] at the border (linear extrapolation), so border
    // pixels do NOT replicate the edge texel — clamping them would make the
    // edge look clamped one texel early.
    float2 q = (float2(p) - 0.5) * 0.5;
    int2 f = (int2)floor(q);
    int2 i0 = clamp(f, int2(0, 0), size - 2);
    int2 i1 = i0 + 1;
    float2 t = q - (float2)i0;
    float4 a = tex.Load(int3(i0, 0));
    float4 b = tex.Load(int3(int2(i1.x, i0.y), 0));
    float4 c = tex.Load(int3(int2(i0.x, i1.y), 0));
    float4 d = tex.Load(int3(i1, 0));
    return a*(1.0-t.x)*(1.0-t.y) + b*t.x*(1.0-t.y) + c*(1.0-t.x)*t.y + d*t.x*t.y;
}

float EDI_Bilinear(Texture2D<float4> tex, int2 size, int2 pos, int comp) {
    // pos is in 2x OUTPUT space (up to 2*size-1), so clamp to the 2x bounds —
    // clamping to size-1 here force-clamped reads to the LR texture edge for
    // every pixel past the top-left quadrant (the "clamped copies" bug).
    pos = clamp(pos, int2(0, 0), size * 2 - 1);
    float ux = ((float)pos.y + 0.5) * 0.5;   // row
    float uy = ((float)pos.x + 0.5) * 0.5;   // col
    int ix = (int)floor(ux - 0.5) + 1;       // row index
    int iy = (int)floor(uy - 0.5) + 1;       // col index
    float s_a = LoadClamp(tex, int2(iy - 1, ix - 1), size)[comp];
    float s_b = LoadClamp(tex, int2(iy - 1, ix),     size)[comp];
    float s_c = LoadClamp(tex, int2(iy,     ix - 1), size)[comp];
    float s_d = LoadClamp(tex, int2(iy,     ix),     size)[comp];
    float tx = ux - (float)ix + 0.5;         // row weight
    float ty = uy - (float)iy + 0.5;         // col weight
    return s_a*(1.0-tx)*(1.0-ty) + s_b*tx*(1.0-ty) + s_c*(1.0-tx)*ty + s_d*tx*ty;
}
float EDI_Base(Texture2D<float4> tex, int2 size, int comp, uint2 p) {
    float ux = ((float)p.y + 0.5) * 0.5;   // row
    float uy = ((float)p.x + 0.5) * 0.5;   // col
    int ix = (int)floor(ux - 0.5) + 1;     // row index
    int iy = (int)floor(uy - 0.5) + 1;     // col index
    float s_a = LoadClamp(tex, int2(iy - 1, ix - 1), size)[comp];
    float s_b = LoadClamp(tex, int2(iy - 1, ix),     size)[comp];
    float s_c = LoadClamp(tex, int2(iy,     ix - 1), size)[comp];
    float s_d = LoadClamp(tex, int2(iy,     ix),     size)[comp];
    float tx = ux - (float)ix + 0.5;       // row weight
    float ty = uy - (float)iy + 0.5;       // col weight
    float dd = clamp((abs(s_c - s_b) - abs(s_d - s_a)) * 8.0, -1.0, 1.0) * 0.5 + 0.5;
    float iBS = (tx + ty < 1.0)
        ? s_c*ty + s_b*tx + s_a*(1.0 - (tx + ty))
        : s_c*(1.0-tx) + s_b*(1.0-ty) + s_d*(1.0 - ((1.0-tx) + (1.0-ty)));
    float iFS = (tx > ty)
        ? s_a*(1.0-tx) + s_d*ty + s_b*(1.0 - ((1.0-tx) + ty))
        : s_a*(1.0-ty) + s_d*tx + s_c*(1.0 - (tx + (1.0-ty)));
    float bil = EDI_Bilinear(tex, size, int2(p), comp);
    float ev = (round(dd) > 0.5) ? iFS : iBS;
    float mix = abs(dd - 0.5) * 2.0;
    float resv = (1.0 - mix) * bil + mix * ev;
    float hf = 0.5*(2.0/3.0)*bil - 0.5/6.0*(EDI_Bilinear(tex, size, int2(p) + int2(0, -2), comp)
        + EDI_Bilinear(tex, size, int2(p) + int2(-2, 0), comp)
        + EDI_Bilinear(tex, size, int2(p) + int2(0, 2), comp)
        + EDI_Bilinear(tex, size, int2(p) + int2(2, 0), comp));
    return resv + hf;
}


//!PASS 1
//!IN INPUT
//!OUT texYcgCo
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass1(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texYcgCo.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    float4 c = INPUT.Load(int3(int2(p), 0));
    float y = 0.25*c.r + 0.5*c.g + 0.25*c.b;
    float cg = -0.25*c.r + 0.5*c.g - 0.25*c.b + 0.5;
    float co = 0.5*c.r - 0.5*c.b + 0.5;
    texYcgCo[p] = float4(y, cg, co, c.a);
}

//!PASS 2
//!IN INPUT
//!OUT texYPad
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass2(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texYPad.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    float4 c = LoadClamp(INPUT, int2(p) - int2(3, 3), int2((int)GetInputSize().x, (int)GetInputSize().y));
    float y = 0.25*c.r + 0.5*c.g + 0.25*c.b;
    float cg = -0.25*c.r + 0.5*c.g - 0.25*c.b + 0.5;
    float co = 0.5*c.r - 0.5*c.b + 0.5;
    texYPad[p] = float4(y, cg, co, c.a);
}

//!PASS 3
//!IN texYPad
//!OUT texL0_0, texL0_1
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass3(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL0_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL0_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(0.057818912, 0.0443928987, 0.0980130062, 0.00270238146);
    min16float4 r1 = min16float4(-0.0148788868, -0.00515851099, -1.52627053e-05, -0.0058138282);
    min16float4 pv0_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(1.5680e-01, 6.1283e-02, 8.4896e-02, -1.4435e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv0_0, min16float4x4(-1.2629e-01, -4.2135e-02, -1.5886e-02, 1.2117e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv1_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(-7.5766e-03, 1.5226e-01, 2.3091e-01, -3.9447e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv1_0, min16float4x4(2.9515e-02, -2.6078e-01, -4.4607e-02, 1.5101e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv2_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(3.7968e-02, -2.8261e-02, 5.7575e-02, 6.7871e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv2_0, min16float4x4(9.5154e-02, -7.1111e-02, -2.0873e-02, -5.1330e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv3_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(-5.0371e-03, -1.4698e-01, -2.3741e-02, -3.6730e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv3_0, min16float4x4(-7.4605e-02, 4.3539e-02, -4.6555e-02, -2.5688e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv4_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(1.3168e-01, 4.6476e-01, -2.2637e-01, 2.9266e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv4_0, min16float4x4(-1.5704e-01, 2.3281e-01, 4.4687e-01, -2.9582e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv5_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(5.5974e-02, 1.6230e-01, 1.1048e-01, 1.9575e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv5_0, min16float4x4(3.9713e-01, -4.0857e-02, -2.8316e-01, 3.8614e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv6_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(1.5812e-01, 1.4079e-01, 1.0318e-01, 8.0699e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv6_0, min16float4x4(-1.1534e-01, 4.5357e-04, 1.1840e-02, 7.9139e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv7_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(2.0158e-01, -9.2694e-02, 7.6006e-02, -8.9232e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv7_0, min16float4x4(-6.8300e-02, 5.6860e-02, -2.1310e-02, 9.0633e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv8_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(-8.5018e-02, -1.1376e-01, -7.5146e-02, -2.5798e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv8_0, min16float4x4(5.9105e-02, 8.0488e-02, -5.2007e-03, -1.2467e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    texL0_0[p] = r0;
    texL0_1[p] = r1;
}

//!PASS 4
//!IN texL0_0, texL0_1
//!OUT texL1_0
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass4(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL1_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL1_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(0.000610134157, 0.628886521, 0.074392952, 0.0586664602);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(1.8582e-01, -2.7690e-01, 8.1088e-01, 4.4982e-01, -3.1254e-01, -6.7179e-01, -7.3982e-02, 1.4914e-02, 6.5798e-02, 8.7012e-01, -1.2802e+00, -8.9357e-01, 6.1934e-01, 1.1750e-01, 1.4685e+00, 9.6028e-01));
    r0 += mul(pv0_1, min16float4x4(5.6185e-01, -1.5335e-01, -3.1555e-01, 2.4254e-01, -5.3518e-01, 1.7130e-01, -7.2357e-01, -1.8704e-01, -2.1307e+00, -3.3736e-01, 3.2752e-01, 5.3728e-01, 4.6008e-01, 3.0448e-01, -3.5920e-01, 3.7641e-01));
    r0 = max(r0, 0.0);
    texL1_0[p] = r0;
}

//!PASS 5
//!IN texL1_0
//!OUT texL2_0, texL2_1, texL2_2
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass5(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL2_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL2_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.0496650599, -0.0359216332, -0.0185571834, -0.0206452068);
    min16float4 r1 = min16float4(0.0699743927, 0.0441078618, 0.0728692263, 0.0192893744);
    min16float4 r2 = min16float4(0.0710275248, -0.0448050499, 0.0, 0.0);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(-1.1507e-01, -1.4654e-01, -1.1276e-01, -1.1470e-01, -1.7833e-02, -4.4975e-01, 1.2848e-01, -2.7122e-01, -2.6357e-01, 7.1737e-02, -5.5543e-02, 2.0872e-02, 2.7523e-01, 2.1797e-01, 5.3989e-02, 3.8018e-01));
    r1 += mul(pv0_0, min16float4x4(5.9823e-02, -1.3113e-01, 3.5337e-02, -3.0417e-02, -5.4856e-02, 7.7296e-02, 4.5180e-02, 5.7007e-03, -1.3935e-02, -9.6637e-02, 6.8341e-02, -1.8800e-02, 1.3583e-02, 1.0829e-01, -5.2681e-02, 1.3247e-02));
    r2 += mul(pv0_0, min16float4x4(-9.9393e-02, -3.9964e-01, 0, 0, -8.6886e-02, 1.9921e-01, 0, 0, -3.7045e-02, -2.6100e-01, 0, 0, 5.3646e-02, 2.8954e-01, 0, 0));
    min16float4 pv1_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(-2.7862e-01, -3.3414e-01, 9.4943e-02, 2.0822e-01, -9.9039e-02, -5.5564e-01, -1.8814e-01, 4.7085e-03, -2.3128e-01, 2.4761e-01, 3.7210e-02, 2.6322e-01, 4.3978e-01, 2.7299e-01, -6.6508e-02, 1.6623e-01));
    r1 += mul(pv1_0, min16float4x4(4.0308e-02, 1.6472e-01, 3.9324e-02, -1.7202e-02, -1.6163e-01, -9.6483e-03, 2.2822e-01, -1.3362e-01, 9.5436e-02, 2.9237e-02, -1.2931e-01, -6.7731e-03, -9.6180e-02, -5.0380e-02, 1.0906e-01, 3.5300e-02));
    r2 += mul(pv1_0, min16float4x4(1.4242e-01, -1.0928e-01, 0, 0, 6.9639e-03, -1.5740e-01, 0, 0, 7.4638e-02, -5.3991e-02, 0, 0, -1.3627e-01, 1.3973e-01, 0, 0));
    min16float4 pv2_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(6.3820e-02, -1.6476e-01, 1.4012e-02, -3.1367e-01, -9.8778e-02, 7.8909e-02, -1.7085e-02, 7.4334e-02, -9.6516e-02, -4.5204e-01, 3.2378e-02, -2.3052e-01, 2.5823e-02, -8.1795e-02, -3.4632e-02, -7.2488e-02));
    r1 += mul(pv2_0, min16float4x4(-1.0499e-02, -5.2692e-02, -2.0632e-02, 3.4390e-02, -5.0394e-02, 9.4670e-02, 6.8290e-02, -3.3516e-02, -8.4756e-02, -5.9986e-02, 5.2029e-02, 3.8401e-02, 8.7878e-02, 7.2948e-02, -2.8995e-02, -5.8816e-02));
    r2 += mul(pv2_0, min16float4x4(-6.5891e-02, 5.3323e-02, 0, 0, 2.6831e-02, 3.6405e-02, 0, 0, -3.8855e-02, -3.0954e-03, 0, 0, 8.9879e-02, -5.8817e-02, 0, 0));
    min16float4 pv3_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(-7.6378e-02, -2.4918e-01, 5.6227e-02, -3.3571e-03, -4.4841e-02, -3.9654e-02, 4.3865e-01, -1.1274e-01, 8.9009e-02, -1.2897e-01, -1.1185e-01, -2.4346e-01, -1.4308e-01, 4.0270e-02, 2.1147e-01, 5.7819e-03));
    r1 += mul(pv3_0, min16float4x4(-1.7291e-02, -9.6726e-02, 2.4512e-01, 1.5742e-02, -1.2107e-01, 1.0420e-01, 5.4279e-02, 2.4568e-01, 7.7720e-02, -1.0228e-01, 1.4799e-01, -1.5714e-02, -7.1331e-02, 4.3771e-03, -6.5182e-02, -2.5710e-03));
    r2 += mul(pv3_0, min16float4x4(5.0200e-02, -4.1280e-01, 0, 0, -4.9592e-01, -4.1290e-02, 0, 0, 4.7702e-01, -5.6542e-02, 0, 0, -4.8695e-01, -1.1630e-01, 0, 0));
    min16float4 pv4_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(2.3059e-01, 2.2807e-02, 3.6980e-02, -2.2700e-01, 1.3056e-01, -5.5273e-02, -5.2537e-01, -4.6042e-02, -2.0975e-01, 8.3085e-02, 3.2280e-01, -1.1767e-01, -4.7883e-01, -9.7902e-02, 3.1615e-02, -1.2243e-01));
    r1 += mul(pv4_0, min16float4x4(3.0675e-01, 1.6050e-01, -7.8411e-02, -1.5694e-03, 3.9091e-01, -2.8453e-01, -5.1144e-02, 1.6230e-01, 2.5061e-01, 2.9143e-01, -2.1436e-01, 2.3897e-02, -1.0451e-01, -1.1076e-01, 1.0617e-02, 2.1216e-01));
    r2 += mul(pv4_0, min16float4x4(4.4871e-02, 1.2455e-01, 0, 0, 3.0166e-01, -2.9323e-01, 0, 0, 4.0251e-01, -4.3453e-01, 0, 0, -4.3077e-02, 1.4250e-01, 0, 0));
    min16float4 pv5_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(-1.1835e-01, -6.2450e-01, 3.2933e-02, 4.5590e-03, 9.5154e-03, -4.5742e-02, 4.5473e-02, -4.3898e-02, -5.1888e-02, 2.3111e-01, 4.9922e-02, -1.2514e-01, 5.4233e-02, -1.3381e-02, -5.0085e-02, 4.2329e-04));
    r1 += mul(pv5_0, min16float4x4(-7.5387e-02, -1.0239e-01, -3.7758e-03, 4.3174e-03, 2.3790e-01, 3.5504e-02, -1.7250e-02, 9.4998e-02, 1.3181e-01, 7.3342e-02, -3.5093e-02, 2.0985e-02, -8.1018e-02, 5.5791e-02, 7.2362e-02, -2.5062e-02));
    r2 += mul(pv5_0, min16float4x4(-8.6681e-02, 1.2373e-01, 0, 0, 7.1219e-02, 2.3927e-01, 0, 0, 6.7824e-04, 1.5834e-01, 0, 0, 1.0551e-01, -1.0268e-01, 0, 0));
    min16float4 pv6_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(1.1078e-01, 2.8390e-01, 3.1632e-02, -2.5783e-01, 1.9022e-02, -4.4796e-01, 7.9222e-03, -1.4717e-01, 2.7377e-01, 4.8748e-01, -8.3398e-03, 7.5000e-02, -1.8928e-01, 2.7444e-02, -6.9022e-02, 7.0099e-02));
    r1 += mul(pv6_0, min16float4x4(-2.6485e-01, 4.1784e-02, -2.4098e-01, -5.5255e-02, -7.8491e-02, -1.3175e-03, -1.6531e-01, -8.2821e-02, -1.8079e-02, 3.4805e-02, 6.7491e-02, 1.1769e-01, 9.1653e-02, 1.1961e-02, 1.0720e-01, -1.4012e-02));
    r2 += mul(pv6_0, min16float4x4(-2.9299e-02, -9.4257e-02, 0, 0, 8.5766e-02, 1.8377e-01, 0, 0, -3.3710e-01, -1.0814e-01, 0, 0, 1.0382e-01, 1.4625e-01, 0, 0));
    min16float4 pv7_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(-8.4030e-04, -3.6130e-01, 1.3720e-02, 9.3760e-02, 7.2785e-02, 4.9401e-02, 8.8048e-02, -2.3219e-01, 4.9331e-01, -1.8840e-01, 6.8951e-02, 1.6613e-01, -3.9162e-02, 1.1105e-01, 7.0121e-02, -1.4381e-01));
    r1 += mul(pv7_0, min16float4x4(1.1117e-01, 6.8183e-02, 6.7284e-02, -3.7954e-02, 2.6325e-01, 2.2455e-01, 1.2216e-01, 5.8967e-02, 2.0601e-01, 4.1373e-01, -1.5219e-01, 3.6398e-02, -9.8806e-02, 5.3123e-02, -1.1492e-01, -5.2593e-03));
    r2 += mul(pv7_0, min16float4x4(1.4039e-01, 7.4017e-02, 0, 0, -1.6392e-02, -2.4915e-02, 0, 0, 3.2329e-02, 1.9883e-01, 0, 0, -1.5494e-01, -1.6323e-01, 0, 0));
    min16float4 pv8_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(-1.1252e-01, -3.1766e-01, 5.9226e-03, 1.4353e-01, 1.0560e-01, -1.4868e-01, 5.0222e-02, -8.3926e-02, 7.1723e-02, -3.3679e-01, 3.7532e-02, 4.2380e-02, 1.1193e-01, -4.4618e-01, -1.9729e-02, -1.3177e-01));
    r1 += mul(pv8_0, min16float4x4(-1.8630e-01, -1.2717e-02, -1.0592e-01, 4.9606e-02, -1.1717e-01, -2.9921e-04, -9.1434e-02, -3.6018e-02, -1.2697e-01, 1.1704e-01, -1.7525e-01, 1.8655e-02, 3.4844e-01, 3.1428e-02, 1.6734e-01, -4.0329e-02));
    r2 += mul(pv8_0, min16float4x4(2.6633e-02, 8.0768e-03, 0, 0, -9.1859e-04, -7.7877e-02, 0, 0, 3.1448e-02, 9.3242e-03, 0, 0, -2.2298e-02, 4.1873e-02, 0, 0));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    r2 = max(r2, 0.0);
    texL2_0[p] = r0;
    texL2_1[p] = r1;
    texL2_2[p] = r2;
}

//!PASS 6
//!IN texL2_0, texL2_1, texL2_2
//!OUT texL3_0, texL3_1
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass6(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL3_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL3_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.0178978089, -0.00982257724, -0.0197831411, -0.00701207994);
    min16float4 r1 = min16float4(-0.0234597959, -0.0498659275, 0.0, 0.0);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(7.6276e-02, 3.0259e-02, 7.0474e-03, 7.7361e-02, 9.1251e-03, 9.5508e-02, -4.1384e-01, -1.1129e-01, -1.1199e-02, 1.0447e-02, -5.6762e-02, -1.1981e-02, -1.5971e-02, 4.9918e-01, -3.6713e-01, -7.6595e-02));
    r0 += mul(pv0_1, min16float4x4(-8.9835e-02, 7.1298e-02, 6.7777e-02, -2.1165e-01, 5.5628e-02, 1.7215e-01, -8.7178e-03, -3.7965e-02, 2.5290e-02, 1.0754e-01, -1.4255e-02, -4.4327e-02, 6.4336e-02, -8.7203e-03, 3.4942e-02, 1.5349e-01));
    r0 += mul(pv0_2, min16float4x4(7.9826e-02, 4.9884e-02, -6.8043e-02, 7.6279e-02, -2.3390e-01, -1.1146e-01, -9.6181e-02, -1.3206e-01, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv0_0, min16float4x4(3.6688e-02, 5.2045e-03, 0, 0, -3.6279e-01, -2.1599e-01, 0, 0, 3.7675e-02, -7.1412e-02, 0, 0, -1.1697e-01, -3.8704e-03, 0, 0));
    r1 += mul(pv0_1, min16float4x4(1.7801e-01, -2.7946e-01, 0, 0, 2.0384e-01, -7.7940e-02, 0, 0, 5.6642e-02, -1.1194e-01, 0, 0, -1.9269e-01, 1.5175e-01, 0, 0));
    r1 += mul(pv0_2, min16float4x4(-3.4205e-02, 1.4836e-02, 0, 0, -1.4032e-01, -1.0158e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv1_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(1, 0), SZ);
    min16float4 pv1_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(1, 0), SZ);
    min16float4 pv1_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(-2.5525e-02, 9.5863e-02, -8.6792e-02, 6.4773e-02, 1.4750e-01, 1.6420e-02, -1.3683e-01, 3.9329e-01, 6.1071e-03, -2.1353e-03, -6.6879e-02, -4.5147e-02, -2.0645e-01, 5.0953e-01, 4.9602e-02, -2.4484e-02));
    r0 += mul(pv1_1, min16float4x4(1.4879e-01, -2.1442e-01, -1.5836e-01, -1.7607e-02, -4.6451e-02, -1.4832e-01, -1.7270e-01, 1.7345e-02, -1.1393e-01, -3.2929e-01, -1.2985e-01, 2.7556e-02, -1.6408e-03, -1.5515e-01, 1.3472e-01, 1.2029e-01));
    r0 += mul(pv1_2, min16float4x4(-7.1249e-02, -3.6193e-02, -1.1216e-01, -1.8363e-02, -1.1335e-01, 6.5824e-02, -1.0414e-01, 1.8582e-01, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv1_0, min16float4x4(-3.1314e-02, 8.3279e-02, 0, 0, 1.1240e-01, 1.6597e-01, 0, 0, -6.3555e-02, 1.5172e-01, 0, 0, -1.4547e-02, -7.5460e-02, 0, 0));
    r1 += mul(pv1_1, min16float4x4(-2.4946e-01, 2.5702e-01, 0, 0, -3.4875e-02, -2.1410e-01, 0, 0, -2.9962e-01, 3.1714e-01, 0, 0, 3.0310e-02, 6.1490e-02, 0, 0));
    r1 += mul(pv1_2, min16float4x4(-5.0375e-02, -6.1886e-02, 0, 0, -1.9232e-02, -1.3537e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv2_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(2, 0), SZ);
    min16float4 pv2_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(2, 0), SZ);
    min16float4 pv2_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(-4.0526e-02, -3.9186e-02, 5.5306e-02, 1.5351e-01, 1.7537e-01, 4.5665e-02, 3.0124e-01, 5.3118e-02, -1.6722e-01, -1.1445e-01, 3.1965e-01, 2.8311e-02, -6.0580e-02, 3.2518e-01, -2.4826e-02, 8.2539e-02));
    r0 += mul(pv2_1, min16float4x4(-1.2914e-01, 1.1661e-01, -5.6139e-03, -1.7155e-01, 3.4070e-02, -6.1092e-03, -2.0487e-01, -1.0652e-01, 1.0679e-01, 1.3304e-01, 1.8244e-01, 5.9240e-02, 2.2247e-01, -7.3403e-02, -2.4465e-01, 6.7215e-02));
    r0 += mul(pv2_2, min16float4x4(-5.5333e-02, -4.0255e-03, 1.5097e-01, 6.1708e-02, 4.8418e-02, 7.4520e-02, -6.7294e-02, 5.3251e-02, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv2_0, min16float4x4(2.8568e-02, -4.3296e-02, 0, 0, 6.3852e-02, 4.5889e-01, 0, 0, -7.5510e-03, 1.0286e-01, 0, 0, 2.2060e-01, -2.0181e-01, 0, 0));
    r1 += mul(pv2_1, min16float4x4(1.2336e-01, -2.2041e-01, 0, 0, -2.6714e-02, -1.2744e-01, 0, 0, 9.3602e-02, -8.4447e-02, 0, 0, -1.1932e-01, -1.2810e-01, 0, 0));
    r1 += mul(pv2_2, min16float4x4(1.3870e-02, 1.8337e-02, 0, 0, 7.1309e-02, -4.1618e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv3_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(0, 1), SZ);
    min16float4 pv3_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(0, 1), SZ);
    min16float4 pv3_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(-8.8276e-02, -1.7721e-01, -4.7318e-02, -7.2815e-02, -2.8214e-01, -1.1914e-01, 2.4595e-01, 2.9689e-01, 2.4562e-02, 9.5929e-02, 3.4847e-01, 6.2636e-03, 2.9743e-01, -2.1019e-02, 1.9455e-01, -1.1735e-03));
    r0 += mul(pv3_1, min16float4x4(2.4507e-02, -7.1209e-03, 2.0751e-01, 1.8443e-01, 2.3295e-01, 2.9098e-01, -1.7526e-01, 1.7372e-01, -1.7408e-01, -1.0511e-01, -5.3764e-02, -1.8846e-01, -3.8771e-02, -6.4111e-02, -6.7758e-02, -4.5254e-02));
    r0 += mul(pv3_2, min16float4x4(6.6232e-02, 2.4471e-02, -2.1364e-01, -2.9564e-02, 9.1849e-02, 1.8460e-02, 3.9737e-01, 8.6577e-02, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv3_0, min16float4x4(-7.5097e-02, 1.2603e-01, 0, 0, 1.0355e-01, -2.7944e-01, 0, 0, -1.8620e-02, -1.2659e-01, 0, 0, 2.7586e-01, 2.4173e-02, 0, 0));
    r1 += mul(pv3_1, min16float4x4(-2.6947e-01, -6.6685e-02, 0, 0, -8.5440e-03, -1.1375e-01, 0, 0, 1.3022e-01, -1.8023e-01, 0, 0, -2.2460e-02, -9.9977e-02, 0, 0));
    r1 += mul(pv3_2, min16float4x4(1.7378e-02, 8.7080e-03, 0, 0, 2.4096e-01, 2.8855e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv4_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(1, 1), SZ);
    min16float4 pv4_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(1, 1), SZ);
    min16float4 pv4_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(1.2419e+00, -4.2268e-01, -5.0872e-01, 1.4092e-01, -3.5854e-01, 1.6666e-03, -3.5160e-01, -1.1914e-01, 9.7960e-01, 4.5190e-01, -1.4652e+00, 3.5692e-01, -2.1539e-01, -2.1543e-01, 3.6656e-01, 3.0237e-01));
    r0 += mul(pv4_1, min16float4x4(-3.5057e-01, -2.1012e-01, 9.1694e-02, 3.2203e-01, -2.9306e-01, 6.6846e-01, 3.3836e-01, -3.5437e-01, 9.0341e-02, 1.0602e-01, -4.6763e-01, -3.1375e-01, -2.9121e-02, -3.1916e-01, 2.3229e-01, 3.8045e-01));
    r0 += mul(pv4_2, min16float4x4(4.3362e-01, 2.3100e-01, -5.4545e-02, 2.3084e-01, 6.6779e-01, 1.1247e-01, -5.8017e-01, -8.4364e-01, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv4_0, min16float4x4(6.0753e-01, -4.0936e-01, 0, 0, 1.9487e-01, -1.4184e-01, 0, 0, 2.0426e-01, 1.0333e+00, 0, 0, 1.6664e-01, -1.2994e-01, 0, 0));
    r1 += mul(pv4_1, min16float4x4(-1.1025e-01, 2.9929e-01, 0, 0, 2.8331e-01, 1.8257e-01, 0, 0, 2.8132e-01, 2.0873e-01, 0, 0, 5.3219e-02, -1.0707e-01, 0, 0));
    r1 += mul(pv4_2, min16float4x4(4.9287e-01, -1.3590e-01, 0, 0, -3.0544e-01, -2.0773e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv5_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(2, 1), SZ);
    min16float4 pv5_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(2, 1), SZ);
    min16float4 pv5_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(9.2790e-02, -8.0977e-02, -1.1317e-01, -1.4304e-01, 1.3346e-01, -1.9400e-01, -1.4596e-01, -2.3624e-01, 4.5544e-02, -3.8364e-02, 5.7480e-01, 6.8209e-03, -4.0704e-01, -1.6023e-01, 7.8175e-02, 1.4529e-01));
    r0 += mul(pv5_1, min16float4x4(-5.2200e-02, 2.0211e-01, -1.4978e-02, -1.9398e-01, -1.8674e-01, -1.3280e-01, -1.4473e-01, 2.6895e-01, -3.0401e-02, -1.6638e-01, 2.7242e-01, 9.5662e-02, -5.1579e-01, -1.1529e-01, -3.7474e-01, 2.6611e-01));
    r0 += mul(pv5_2, min16float4x4(5.4969e-01, -2.1541e-02, 6.5365e-01, -3.5700e-01, -6.5732e-02, 1.3729e-01, -7.7073e-02, -3.7681e-01, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv5_0, min16float4x4(-1.5327e-01, -1.6529e-01, 0, 0, 8.5222e-02, -1.2689e-01, 0, 0, 1.7843e-02, 1.2558e-01, 0, 0, 2.8558e-01, 1.0064e-01, 0, 0));
    r1 += mul(pv5_1, min16float4x4(1.4052e-01, -1.7895e-01, 0, 0, -1.6750e-01, -6.1755e-02, 0, 0, -1.3987e-01, 1.7578e-01, 0, 0, -5.3411e-02, -1.1407e-01, 0, 0));
    r1 += mul(pv5_2, min16float4x4(-1.9909e-01, 6.9063e-01, 0, 0, 2.4233e-02, 1.0739e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv6_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(0, 2), SZ);
    min16float4 pv6_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(0, 2), SZ);
    min16float4 pv6_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(-6.7837e-02, -9.7116e-02, -1.0282e-01, 7.0199e-02, -1.6460e-01, -7.2156e-02, 1.4327e-01, 3.0340e-02, -3.3137e-02, -7.5468e-02, -8.9396e-04, 2.3372e-02, -4.9778e-01, -9.6065e-02, 1.3055e-01, -1.3424e-01));
    r0 += mul(pv6_1, min16float4x4(9.8420e-02, 1.3223e-01, 3.4263e-02, 5.0831e-02, 9.3328e-02, -1.4817e-01, 1.0061e-01, -1.2644e-01, 1.6038e-01, -5.1294e-02, -7.9372e-02, 6.2648e-02, -2.3262e-01, 1.2200e-01, 7.2507e-02, -8.9816e-02));
    r0 += mul(pv6_2, min16float4x4(-1.3416e-02, 4.7917e-02, -7.5859e-02, 2.4311e-03, -1.0081e-01, -5.7736e-02, 3.5299e-01, 4.7671e-02, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv6_0, min16float4x4(5.8614e-02, 7.9633e-02, 0, 0, 3.3067e-01, 1.2182e-01, 0, 0, -3.7691e-02, -1.0930e-01, 0, 0, 6.6637e-02, 1.4071e-01, 0, 0));
    r1 += mul(pv6_1, min16float4x4(1.0772e-01, 2.6473e-01, 0, 0, 1.4159e-03, -8.5169e-02, 0, 0, -6.4084e-02, -1.4082e-01, 0, 0, 1.6909e-02, 5.5633e-02, 0, 0));
    r1 += mul(pv6_2, min16float4x4(-6.9749e-03, 3.5062e-02, 0, 0, -1.5114e-01, -5.8920e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv7_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(1, 2), SZ);
    min16float4 pv7_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(1, 2), SZ);
    min16float4 pv7_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(-2.9346e-01, 1.5918e-01, -3.6114e-01, 2.3433e-01, 4.7194e-01, 3.2936e-01, -2.6812e-01, -1.9735e-01, 1.6677e-02, -8.2879e-02, -2.2584e-01, -9.5250e-03, 1.4385e-02, 3.9630e-02, -1.5083e-01, 1.9388e-01));
    r0 += mul(pv7_1, min16float4x4(2.7241e-01, 2.9537e-02, 3.8222e-01, -6.5736e-02, -3.8985e-02, -1.0679e-01, 9.7267e-02, -2.5664e-02, -1.2836e-01, -7.9025e-02, -2.0250e-01, 2.9106e-01, 3.3162e-01, 4.1718e-01, 5.1455e-02, -4.9297e-01));
    r0 += mul(pv7_2, min16float4x4(3.7209e-01, 5.4621e-01, 1.2242e-01, 9.7464e-02, -9.7218e-01, -7.9065e-01, -3.2278e-01, 3.5858e-01, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv7_0, min16float4x4(-2.1040e-01, -4.6600e-01, 0, 0, -3.2932e-01, 2.7960e-01, 0, 0, 7.3167e-02, 2.2498e-01, 0, 0, 6.8547e-01, 8.4458e-02, 0, 0));
    r1 += mul(pv7_1, min16float4x4(9.6852e-02, 2.0927e-01, 0, 0, -6.0750e-02, 1.2074e-01, 0, 0, -2.0550e-02, 4.6368e-02, 0, 0, -1.0817e-01, -1.9930e-01, 0, 0));
    r1 += mul(pv7_2, min16float4x4(4.0803e-02, 2.1350e-01, 0, 0, -8.3727e-02, 1.5284e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv8_0 = (min16float4)LoadClamp(texL2_0, int2(p) + int2(2, 2), SZ);
    min16float4 pv8_1 = (min16float4)LoadClamp(texL2_1, int2(p) + int2(2, 2), SZ);
    min16float4 pv8_2 = (min16float4)LoadClamp(texL2_2, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(-1.3631e-01, 6.4993e-02, 1.5274e-01, 4.1259e-02, 4.8697e-02, 1.5060e-01, 1.1258e-02, -1.1510e-01, -2.7903e-02, 3.8863e-02, 3.3886e-01, -4.1229e-03, -8.3979e-02, -8.6365e-02, -2.2606e-01, 1.4488e-02));
    r0 += mul(pv8_1, min16float4x4(-3.8372e-02, 1.5068e-01, -2.7192e-02, -5.1739e-02, 1.6855e-01, -2.1852e-01, -1.7317e-01, 5.9470e-02, 1.2935e-01, -1.0229e-01, 3.0714e-01, 1.7524e-01, 3.1453e-01, -4.1509e-02, -8.6481e-03, -1.6827e-01));
    r0 += mul(pv8_2, min16float4x4(1.7626e-01, 1.4858e-01, 4.7743e-01, 2.5719e-01, -3.9078e-01, -2.2868e-01, -2.9482e-01, -9.5739e-02, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv8_0, min16float4x4(8.9604e-02, 2.2506e-01, 0, 0, 3.4016e-01, -1.0054e-01, 0, 0, -3.5506e-02, 1.1797e-01, 0, 0, 1.0406e-02, -6.3538e-02, 0, 0));
    r1 += mul(pv8_1, min16float4x4(1.6897e-02, 7.6672e-03, 0, 0, -6.1576e-02, -1.9515e-01, 0, 0, 2.3821e-02, 1.7894e-01, 0, 0, 2.6264e-01, 3.7286e-01, 0, 0));
    r1 += mul(pv8_2, min16float4x4(1.2420e-01, 5.0798e-01, 0, 0, -8.5162e-02, -6.2226e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    texL3_0[p] = r0;
    texL3_1[p] = r1;
}

//!PASS 7
//!IN texL3_0, texL3_1
//!OUT texResid
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass7(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texResid.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texResid.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(0.0, 0.0, 0.0, 0.0);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL3_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL3_1, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(3.2111e-01, 6.3908e-01, -4.1159e-01, -7.5636e-01, -3.3884e-01, -6.6244e-01, 1.1937e+00, 4.3265e-01, 7.5575e-01, -7.6726e-01, 6.2306e-01, -1.0824e+00, -8.2904e-01, -7.6262e-01, 2.1276e-01, 3.2876e-01));
    r0 += mul(pv0_1, min16float4x4(1.1288e+00, -3.5073e-01, -4.4730e-01, 3.5624e-01, -4.6231e-01, 5.2942e-01, -6.0185e-01, 6.2039e-01, 0, 0, 0, 0, 0, 0, 0, 0));
    texResid[p] = r0;
}

//!PASS 8
//!IN texYcgCo, texYPad
//!OUT texBase
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass8(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texBase.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    int2 PSZ = int2((int)GetOutputSize().x / 2 + 6, (int)GetOutputSize().y / 2 + 6);
    uint2 pp = p + uint2(6, 6);
    float4 ycg = BilinearExtrap(texYcgCo, int2((int)GetOutputSize().x / 2, (int)GetOutputSize().y / 2), p);
    float bY = EDI_Base(texYPad, PSZ, 0, pp);
    texBase[p] = float4(bY, ycg.g, ycg.b, ycg.a);
}

//!PASS 9
//!IN texBase, texResid
//!OUT OUTPUT
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass9(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; OUTPUT.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint2 lr = p >> 1;
    int c = 2 * (int)(p.y & 1u) + (int)(p.x & 1u);
    float4 r4 = texResid.Load(int3(int2(lr), 0));
    float rv = c == 0 ? r4.r : (c == 1 ? r4.g : (c == 2 ? r4.b : r4.a));
    float4 base4 = texBase.Load(int3(int2(p), 0));
    float y = clamp(base4.r + rv, 0.0, 1.0);
    float cg = base4.g - 0.5;
    float co = base4.b - 0.5;
    float tmp = y - cg;
    float r = clamp(tmp + co, 0.0, 1.0);
    float g = clamp(y + cg, 0.0, 1.0);
    float b = clamp(tmp - co, 0.0, 1.0);
    OUTPUT[p] = float4(r, g, b, base4.a);
}
