//!MAGPIE EFFECT
//!VERSION 4
// MagpieFX shader generated by magpie_gen.py (nene2x project's own code).
// config: b,3x3_12,1x1_8,1x1_4
// base upscaler: bilinear   channels: YCgCo luma   activation: ReLU
//!TEXTURE
Texture2D INPUT;
//!TEXTURE
//!WIDTH INPUT_WIDTH * 2
//!HEIGHT INPUT_HEIGHT * 2
Texture2D OUTPUT;
//!TEXTURE
//!WIDTH INPUT_WIDTH
//!HEIGHT INPUT_HEIGHT
//!FORMAT R16G16B16A16_FLOAT
Texture2D texYcgCo;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 2
//!HEIGHT INPUT_HEIGHT + 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texYPad;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 2
//!HEIGHT INPUT_HEIGHT + 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 2
//!HEIGHT INPUT_HEIGHT + 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 2
//!HEIGHT INPUT_HEIGHT + 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL0_2;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 2
//!HEIGHT INPUT_HEIGHT + 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_0;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 2
//!HEIGHT INPUT_HEIGHT + 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texL1_1;
//!TEXTURE
//!WIDTH INPUT_WIDTH + 2
//!HEIGHT INPUT_HEIGHT + 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texResid;
//!TEXTURE
//!WIDTH INPUT_WIDTH * 2
//!HEIGHT INPUT_HEIGHT * 2
//!FORMAT R16G16B16A16_FLOAT
Texture2D texBase;

//!COMMON

float4 LoadClamp(Texture2D<float4> tex, int2 pos, int2 size) {
    pos = clamp(pos, int2(0, 0), size - 1);
    return tex.Load(int3(pos, 0));
}

float4 BilinearExtrap(Texture2D<float4> tex, int2 size, uint2 p) {
    // Chroma/alpha upsample: infer.py's bil_up interpolates with tap weights
    // that go outside [0,1] at the border (linear extrapolation), so border
    // pixels do NOT replicate the edge texel — clamping them would make the
    // edge look clamped one texel early.
    float2 q = (float2(p) - 0.5) * 0.5;
    int2 f = (int2)floor(q);
    int2 i0 = clamp(f, int2(0, 0), size - 2);
    int2 i1 = i0 + 1;
    float2 t = q - (float2)i0;
    float4 a = tex.Load(int3(i0, 0));
    float4 b = tex.Load(int3(int2(i1.x, i0.y), 0));
    float4 c = tex.Load(int3(int2(i0.x, i1.y), 0));
    float4 d = tex.Load(int3(i1, 0));
    return a*(1.0-t.x)*(1.0-t.y) + b*t.x*(1.0-t.y) + c*(1.0-t.x)*t.y + d*t.x*t.y;
}

float BilinearBase(Texture2D<float4> tex, int2 size, int comp, uint2 p) {
    int x = (int)p.x, y = (int)p.y;
    int x0 = (p.x & 1u) == 0u ? x / 2 - 1 : x / 2;
    int x1 = (p.x & 1u) == 0u ? x / 2 : x / 2 + 1;
    int y0 = (p.y & 1u) == 0u ? y / 2 - 1 : y / 2;
    int y1 = (p.y & 1u) == 0u ? y / 2 : y / 2 + 1;
    float wx0 = (p.x & 1u) == 0u ? 0.25 : 0.75;
    float wx1 = (p.x & 1u) == 0u ? 0.75 : 0.25;
    float wy0 = (p.y & 1u) == 0u ? 0.25 : 0.75;
    float wy1 = (p.y & 1u) == 0u ? 0.75 : 0.25;
    int2 c0 = clamp(int2(x0, y0), int2(0, 0), size - 1);
    int2 c1 = clamp(int2(x1, y0), int2(0, 0), size - 1);
    int2 c2 = clamp(int2(x0, y1), int2(0, 0), size - 1);
    int2 c3 = clamp(int2(x1, y1), int2(0, 0), size - 1);
    return wy0*wx0*LoadClamp(tex, c0, size)[comp] + wy0*wx1*LoadClamp(tex, c1, size)[comp]
         + wy1*wx0*LoadClamp(tex, c2, size)[comp] + wy1*wx1*LoadClamp(tex, c3, size)[comp];
}


//!PASS 1
//!IN INPUT
//!OUT texYcgCo
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass1(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texYcgCo.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    float4 c = INPUT.Load(int3(int2(p), 0));
    float y = 0.25*c.r + 0.5*c.g + 0.25*c.b;
    float cg = -0.25*c.r + 0.5*c.g - 0.25*c.b + 0.5;
    float co = 0.5*c.r - 0.5*c.b + 0.5;
    texYcgCo[p] = float4(y, cg, co, c.a);
}

//!PASS 2
//!IN INPUT
//!OUT texYPad
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass2(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texYPad.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    float4 c = LoadClamp(INPUT, int2(p) - int2(1, 1), int2((int)GetInputSize().x, (int)GetInputSize().y));
    float y = 0.25*c.r + 0.5*c.g + 0.25*c.b;
    float cg = -0.25*c.r + 0.5*c.g - 0.25*c.b + 0.5;
    float co = 0.5*c.r - 0.5*c.b + 0.5;
    texYPad[p] = float4(y, cg, co, c.a);
}

//!PASS 3
//!IN texYPad
//!OUT texL0_0, texL0_1, texL0_2
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass3(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL0_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL0_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(0.146822304, -0.00378242065, 0.0688923299, 0.0381330997);
    min16float4 r1 = min16float4(-0.000283147645, -0.00374504784, -0.0087021403, 0.00547763985);
    min16float4 r2 = min16float4(-0.0023715084, -0.000628898735, 0.0737913549, -0.00216646283);
    min16float4 pv0_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(-2.7908e-02, 3.2875e-02, -1.0576e-01, -1.0659e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv0_0, min16float4x4(-2.4326e-04, -4.7251e-02, -3.7670e-02, -4.3970e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv0_0, min16float4x4(-2.6146e-02, -4.3821e-02, -3.1715e-02, 8.7955e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv1_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 0), SZ);
    r0 += mul(pv1_0, min16float4x4(-1.0461e-01, -5.4348e-02, 4.9731e-03, 2.1775e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv1_0, min16float4x4(-3.0896e-02, -1.8005e-01, -2.5856e-01, 1.9634e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv1_0, min16float4x4(4.3262e-02, 3.1617e-02, 1.5785e-01, 3.5505e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv2_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 0), SZ);
    r0 += mul(pv2_0, min16float4x4(-4.5209e-02, 3.4154e-02, -2.0766e-02, -2.3878e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv2_0, min16float4x4(2.5253e-02, 2.9896e-01, 5.3194e-02, 8.7818e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv2_0, min16float4x4(-1.7089e-02, -1.6801e-02, -2.4865e-02, -6.5654e-03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv3_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 1), SZ);
    r0 += mul(pv3_0, min16float4x4(-2.7343e-01, -8.1110e-02, 1.0135e-01, -3.5387e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv3_0, min16float4x4(-2.7795e-01, -3.3426e-03, 1.9930e-01, 2.2953e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv3_0, min16float4x4(2.1170e-02, -1.9918e-01, 1.3275e-01, -1.8458e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv4_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 1), SZ);
    r0 += mul(pv4_0, min16float4x4(3.7296e-01, 4.3653e-01, 5.3417e-01, -1.0806e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv4_0, min16float4x4(-8.7020e-02, -1.5830e-01, 1.4377e-01, -5.5819e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv4_0, min16float4x4(5.1357e-01, 4.0365e-01, -4.1765e-01, -2.6643e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv5_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 1), SZ);
    r0 += mul(pv5_0, min16float4x4(-2.0171e-03, 2.9485e-02, 1.1860e-01, -5.4540e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv5_0, min16float4x4(3.7327e-02, 3.2875e-02, -2.1593e-01, 2.1545e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv5_0, min16float4x4(-2.8192e-01, -1.3128e-02, 3.0705e-01, 4.3920e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv6_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(0, 2), SZ);
    r0 += mul(pv6_0, min16float4x4(6.8982e-02, -1.0553e-01, 7.2692e-02, 6.5014e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv6_0, min16float4x4(1.4526e-01, -1.0107e-02, -8.8745e-02, 2.1580e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv6_0, min16float4x4(9.4368e-03, 2.7822e-02, 9.7685e-02, -6.0561e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv7_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(1, 2), SZ);
    r0 += mul(pv7_0, min16float4x4(-2.2454e-02, -1.2042e-01, -1.4776e-01, -1.5427e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv7_0, min16float4x4(2.1910e-01, 4.2978e-02, 3.5874e-01, 4.1700e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv7_0, min16float4x4(-2.7432e-01, -2.0706e-01, 1.0436e-01, 6.8476e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    min16float4 pv8_0 = (min16float4)LoadClamp(texYPad, int2(p) + int2(2, 2), SZ);
    r0 += mul(pv8_0, min16float4x4(1.0745e-01, -1.6154e-01, 3.1555e-02, 2.4886e-01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r1 += mul(pv8_0, min16float4x4(-3.1207e-02, 1.1027e-02, -1.4482e-01, 3.6937e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r2 += mul(pv8_0, min16float4x4(1.7541e-02, 1.8860e-02, 7.3837e-02, -3.4445e-02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    r2 = max(r2, 0.0);
    texL0_0[p] = r0;
    texL0_1[p] = r1;
    texL0_2[p] = r2;
}

//!PASS 4
//!IN texL0_0, texL0_1, texL0_2
//!OUT texL1_0, texL1_1
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass4(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texL1_0.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texL1_0.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(-0.0122798216, -0.0655981153, 0.0426515155, 0.0266303457);
    min16float4 r1 = min16float4(-0.0317386612, -0.0457524285, -0.0766769275, 0.0718977898);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL0_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL0_1, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_2 = (min16float4)LoadClamp(texL0_2, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(-9.0364e-02, 4.9170e-01, -4.5549e-01, -2.5184e-01, -1.3256e-01, -1.0948e-01, -5.6524e-01, -9.2522e-01, -5.0958e-01, -3.0666e-01, -4.4233e-01, -4.3611e-01, 1.5183e-01, -4.0750e-01, 1.7110e-01, -4.8275e-01));
    r0 += mul(pv0_1, min16float4x4(6.0513e-02, -7.6407e-01, -3.8661e-01, 1.7995e-01, 1.8234e-01, 4.3422e-01, 2.0672e-01, -3.1798e-01, -2.3999e-01, 4.0550e-01, 1.0101e+00, -6.8570e-01, 1.0804e-01, -2.5136e+00, -4.1154e-01, 2.5049e-01));
    r0 += mul(pv0_2, min16float4x4(6.8022e-01, 5.7005e-01, -1.3820e-01, 8.1457e-01, -6.4454e-01, 6.1843e-01, -3.3031e-01, -7.8033e-01, 7.3766e-01, 4.2407e-01, 6.8867e-01, 7.4705e-01, -3.7083e-01, -2.4888e-01, 5.8576e-01, 3.4051e-01));
    r1 += mul(pv0_0, min16float4x4(4.0058e-02, 4.5168e-01, 4.9042e-01, -6.3892e-01, -4.3952e-01, 8.3763e-02, 7.2339e-01, -1.2282e-01, -6.4204e-01, 3.4128e-01, -3.8693e-01, -4.6034e-01, -1.3179e-01, -1.3470e-01, -2.6337e-02, -6.3158e-02));
    r1 += mul(pv0_1, min16float4x4(-2.1747e-01, -8.7544e-02, -1.4668e-02, 1.1165e-01, 2.9431e-01, -6.3563e-02, -5.6199e-02, -3.2958e-01, 3.7640e-01, -5.4949e-02, 1.6230e-01, 2.1416e-01, 8.6794e-01, 4.2439e-01, -2.0636e+00, -3.9700e-01));
    r1 += mul(pv0_2, min16float4x4(-7.3521e-01, 7.4751e-02, 6.5872e-01, 5.1740e-01, 9.6995e-01, 7.5082e-02, -2.5204e-01, 3.9831e-01, 9.5982e-01, -5.5992e-01, 4.6370e-01, 7.6955e-01, 2.0663e-01, 1.3696e-03, -3.7797e-01, 4.3795e-01));
    r0 = max(r0, 0.0);
    r1 = max(r1, 0.0);
    texL1_0[p] = r0;
    texL1_1[p] = r1;
}

//!PASS 5
//!IN texL1_0, texL1_1
//!OUT texResid
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass5(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texResid.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint cw, ch; texResid.GetDimensions(cw, ch);
    int2 SZ = int2((int)cw, (int)ch);
    min16float4 r0 = min16float4(7.89254045e-06, -2.08599431e-06, -1.07596861e-05, -1.58952957e-06);
    min16float4 pv0_0 = (min16float4)LoadClamp(texL1_0, int2(p) + int2(0, 0), SZ);
    min16float4 pv0_1 = (min16float4)LoadClamp(texL1_1, int2(p) + int2(0, 0), SZ);
    r0 += mul(pv0_0, min16float4x4(1.4954e+00, -7.7480e-01, 4.2867e-02, -1.4510e+00, 8.7828e-02, 1.3048e+00, -1.3277e+00, 2.6029e-01, 3.3245e-01, -1.7368e+00, 1.4893e+00, -8.4591e-02, -6.4640e-01, -1.1870e+00, 4.5887e-01, 9.4197e-01));
    r0 += mul(pv0_1, min16float4x4(-1.4076e+00, 8.7596e-01, -8.7127e-01, 5.6340e-01, 1.4075e+00, 2.5834e-01, 1.1559e+00, -3.0979e-01, -1.4763e+00, -6.1200e-01, 5.9951e-01, 1.6342e+00, 1.0854e+00, 1.4356e+00, -1.1373e+00, -1.3792e+00));
    texResid[p] = r0;
}

//!PASS 6
//!IN texYcgCo, texYPad
//!OUT texBase
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass6(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; texBase.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    int2 PSZ = int2((int)GetOutputSize().x / 2 + 2, (int)GetOutputSize().y / 2 + 2);
    uint2 pp = p + uint2(2, 2);
    float4 ycg = BilinearExtrap(texYcgCo, int2((int)GetOutputSize().x / 2, (int)GetOutputSize().y / 2), p);
    float bY = BilinearBase(texYPad, PSZ, 0, pp);
    texBase[p] = float4(bY, ycg.g, ycg.b, ycg.a);
}

//!PASS 7
//!IN texBase, texResid
//!OUT OUTPUT
//!BLOCK_SIZE 8
//!NUM_THREADS 64
void Pass7(uint2 blockStart, uint3 threadId) {
    uint2 p = blockStart + Rmp8x8(threadId.x);
    uint ow, oh; OUTPUT.GetDimensions(ow, oh);
    if (p.x >= ow || p.y >= oh) return;
    uint2 lr = p >> 1;
    int c = 2 * (int)(p.y & 1u) + (int)(p.x & 1u);
    float4 r4 = texResid.Load(int3(int2(lr), 0));
    float rv = c == 0 ? r4.r : (c == 1 ? r4.g : (c == 2 ? r4.b : r4.a));
    float4 base4 = texBase.Load(int3(int2(p), 0));
    float y = clamp(base4.r + rv, 0.0, 1.0);
    float cg = base4.g - 0.5;
    float co = base4.b - 0.5;
    float tmp = y - cg;
    float r = clamp(tmp + co, 0.0, 1.0);
    float g = clamp(y + cg, 0.0, 1.0);
    float b = clamp(tmp - co, 0.0, 1.0);
    OUTPUT[p] = float4(r, g, b, base4.a);
}
